"""Consolidated doc-wiring tests — CLI tool registration in help.md, CLAUDE.md, and CLI.md.

Generated by ENH-1963: Audit and Consolidate Doc-Wiring Tests.
All original assertions from 30 source files preserved as parametrized cases.
"""

from __future__ import annotations

from pathlib import Path

import pytest

# =============================================================================
# Shared paths (resolved from project_root fixture)
# =============================================================================


# -- 111 string-presence assertions -------------------------------

DOC_STRINGS_PRESENT: list[tuple[str, str, str]] = [
    # (doc_path, expected_string, issue_id)
    ("commands/help.md", "ll-doctor", "FEAT-1504"),
    ("docs/reference/CLI.md", "ll-doctor", "FEAT-1504"),
    (".claude/CLAUDE.md", "ll-doctor", "FEAT-1504"),
    ("commands/help.md", "ll-ctx-stats", "FEAT-1625"),
    ("docs/reference/CLI.md", "ll-ctx-stats", "FEAT-1625"),
    (".claude/CLAUDE.md", "ll-ctx-stats", "FEAT-1625"),
    ("commands/help.md", "/ll:review-epic", "FEAT-1856"),
    ("commands/help.md", "review-epic", "FEAT-1856"),
    (".claude/CLAUDE.md", "review-epic", "FEAT-1856"),
    ("commands/help.md", "/ll:scope-epic", "FEAT-1857"),
    ("commands/help.md", "scope-epic", "FEAT-1857"),
    (".claude/CLAUDE.md", "scope-epic", "FEAT-1857"),
    ("commands/help.md", "create-epics-from-unparented", "FEAT-2338"),
    (".claude/CLAUDE.md", "create-epics-from-unparented", "FEAT-2338"),
    (".claude/CLAUDE.md", "decisions", "FEAT-1894"),
    ("commands/help.md", "decisions", "FEAT-1894"),
    ("docs/reference/CLI.md", "ll-issues decisions", "FEAT-1894"),
    (".claude/CLAUDE.md", ".loops/tmp/scratch/", "ENH-1130"),
    ("docs/reference/CLI.md", "foreground and background runs", "ENH-1704"),
    ("commands/help.md", "ll-history-context", "ENH-1846"),
    ("docs/reference/CLI.md", "ll-history-context", "ENH-1846"),
    (".claude/CLAUDE.md", "ll-history-context", "ENH-1846"),
    ("docs/reference/CLI.md", "--for-skill", "ENH-1909"),
    ("docs/reference/CLI.md", "37 `LLEvent` types", "ENH-1115"),
    ("commands/help.md", "using goals file if present, or auto-discovering goals", "ENH-1443"),
    ("commands/help.md", "ll-logs", "ll-logs"),
    ("docs/reference/CLI.md", "dead-skills", "ENH-1923"),
    (".claude/CLAUDE.md", "dead-skills", "ENH-1923"),
    ("commands/help.md", "ll-create-extension", "FEAT-1045"),
    ("docs/reference/CLI.md", "ll-create-extension", "FEAT-1045"),
    (".claude/CLAUDE.md", "ll-create-extension", "FEAT-1045"),
    (".claude/CLAUDE.md", "ll-generate-schemas", "ENH-1093"),
    ("commands/help.md", "ll-action", "FEAT-1229"),
    ("docs/reference/CLI.md", "ll-action", "FEAT-1229"),
    ("commands/help.md", "ll-generate-skill-descriptions", "ENH-1395"),
    ("docs/reference/CLI.md", "ll-generate-skill-descriptions", "ENH-1395"),
    (".claude/CLAUDE.md", "ll-generate-skill-descriptions", "ENH-1395"),
    ("commands/help.md", "ll-migrate-relationships", "ENH-1435"),
    ("docs/reference/CLI.md", "ll-migrate-relationships", "ENH-1435"),
    (".claude/CLAUDE.md", "ll-migrate-relationships", "ENH-1435"),
    ("commands/help.md", "ll-adapt-skills-for-codex", "FEAT-1486"),
    ("docs/reference/CLI.md", "ll-adapt-skills-for-codex", "FEAT-1486"),
    (".claude/CLAUDE.md", "ll-adapt-skills-for-codex", "FEAT-1486"),
    ("commands/help.md", "ll-adapt-agents-for-codex", "FEAT-1526"),
    ("docs/reference/CLI.md", "ll-adapt-agents-for-codex", "FEAT-1526"),
    (".claude/CLAUDE.md", "ll-adapt-agents-for-codex", "FEAT-1526"),
    ("commands/help.md", "ll-harness", "FEAT-1689"),
    ("docs/reference/CLI.md", "ll-harness", "FEAT-1689"),
    (".claude/CLAUDE.md", "ll-harness", "FEAT-1689"),
    ("commands/help.md", "ll-verify-design-tokens", "ENH-2308"),
    ("docs/reference/CLI.md", "ll-verify-design-tokens", "ENH-2308"),
    (".claude/CLAUDE.md", "ll-verify-design-tokens", "ENH-2308"),
    (".claude/CLAUDE.md", "decisions.yaml", "FEAT-948"),
    # REMOVED (stale/false-positive): (".claude/CLAUDE.md", "scratch_dir=.loops/tmp", "ENH-1130"),
    ("docs/reference/CLI.md", "in_progress", "ENH-1428"),
    ("docs/reference/CLI.md", "done", "ENH-1428"),
    ("docs/reference/CLI.md", "cancelled", "ENH-1428"),
    ("docs/reference/CLI.md", "--status done", "ENH-1428"),
    # REMOVED (stale/false-positive): ("docs/reference/CLI.md", "{open,in_progress,blocked,deferred,done,cancelled,all}", "ENH-1428"),
    # REMOVED (stale/false-positive): ("commands/help.md", "ll-goals.md` is optional", "ENH-1443"),
    (".claude/CLAUDE.md", "**Status values**:", "ENH-1550"),
    # REMOVED (stale/false-positive): (".claude/CLAUDE.md", "**Status enum**:", "ENH-1550"),
    ("docs/reference/CLI.md", "argparse validates choices before normalization runs", "ENH-1550"),
    ("docs/reference/CLI.md", "live", "ENH-1734"),
    ("docs/reference/CLI.md", "historical", "ENH-1734"),
    ("docs/reference/CLI.md", "ll-session", "ENH-1734"),
    ("docs/reference/CLI.md", "ENH-1691", "ENH-1734"),
    # REMOVED (stale/false-positive): (".claude/CLAUDE.md", "Authorize all 29", "ENH-1846"),
    ("docs/reference/CLI.md", "EPIC-NNN", "ENH-1859"),
    ("docs/reference/CLI.md", "ll-deps tree", "ENH-1866"),
    ("docs/reference/CLI.md", "--epic", "ENH-1866"),
    (".claude/CLAUDE.md", "ll-learning-tests", "FEAT-1287"),
    # REMOVED (stale/false-positive): (".claude/CLAUDE.md", "## Learning Test Registry", "FEAT-1287"),
    # REMOVED (stale/false-positive): (".claude/CLAUDE.md", "LearnTestRecord", "FEAT-1287"),
    ("commands/help.md", "/ll:explore-api", "FEAT-1287"),
    ("commands/help.md", "`explore-api`", "FEAT-1287"),
    (".claude/CLAUDE.md", "EPIC", "FEAT-1407"),
    (".claude/CLAUDE.md", "epics/", "FEAT-1407"),
    ("commands/help.md", "/ll:verify-issue-loop", "FEAT-1447"),
    ("commands/help.md", "verify-issue-loop", "FEAT-1447"),
    ("commands/help.md", "/ll:adversarial-verify-loop", "ENH-2047"),
    ("commands/help.md", "adversarial-verify-loop", "ENH-2047"),
    (".claude/CLAUDE.md", "adversarial-verify-loop", "ENH-2047"),
    ("docs/reference/CLI.md", "LLHookIntentExtension", "FEAT-1457"),
    (".claude/CLAUDE.md", "scripts/little_loops/hooks/", "FEAT-1457"),
    (".claude/CLAUDE.md", "adapters/", "FEAT-1457"),
    # REMOVED (stale/false-positive): (".claude/CLAUDE.md", "LLHookIntentExtension", "FEAT-1457"),
    # REMOVED (stale/false-positive): (".claude/CLAUDE.md", "_HOOK_INTENT_REGISTRY", "FEAT-1457"),
    (".claude/CLAUDE.md", "host_runner", "FEAT-1462"),
    # REMOVED (stale/false-positive): ("docs/reference/CLI.md", "Authorize all 29", "FEAT-1504"),
    # REMOVED (stale/false-positive): ("commands/help.md", "### `/ll:review-epic`", "FEAT-1856"),
    # REMOVED (stale/false-positive): (".claude/CLAUDE.md", "### `/ll:review-epic`", "FEAT-1856"),
    # REMOVED (stale/false-positive): (".claude/CLAUDE.md", "| `review-epic`", "FEAT-1856"),
    # REMOVED (stale/false-positive): ("commands/help.md", "### `/ll:scope-epic`", "FEAT-1857"),
    # REMOVED (stale/false-positive): (".claude/CLAUDE.md", "### `/ll:scope-epic`", "FEAT-1857"),
    # REMOVED (stale/false-positive): (".claude/CLAUDE.md", "| `scope-epic`", "FEAT-1857"),
    (".claude/CLAUDE.md", "ll-issues decisions", "FEAT-1894"),
    # REMOVED (stale/false-positive): ("commands/help.md", "ll-issues decisions", "FEAT-1894"),
    # REMOVED (stale/false-positive): ("commands/help.md", "decisions.py", "FEAT-1894"),
    # REMOVED (stale/false-positive): ("docs/reference/CLI.md", "decisions.py", "FEAT-1894"),
    # REMOVED (stale/false-positive): ("commands/help.md", "Bash(ll-create-extension:*)", "FEAT-1045"),
    # REMOVED (stale/false-positive): ("docs/reference/CLI.md", "32 typed CLI tools", "FEAT-1045"),
    # REMOVED (stale/false-positive): (".claude/CLAUDE.md", "little_loops.testing", "FEAT-1045"),
    # REMOVED (stale/false-positive): ("docs/reference/CLI.md", "little_loops.testing", "FEAT-1045"),
    # REMOVED (stale/false-positive): (".claude/CLAUDE.md", "mcp-call", "FEAT-1045"),
    (".claude/CLAUDE.md", "ll-action", "FEAT-1045"),
    # REMOVED (stale/false-positive): ("commands/help.md", "32 typed CLI tools", "FEAT-1045"),
    # REMOVED (stale/false-positive): ("commands/help.md", "New Skill Checklist", "FEAT-1045"),
    # REMOVED (stale/false-positive): ("commands/help.md", "/doctor", "FEAT-1045"),
    # REMOVED (stale/false-positive): (".claude/CLAUDE.md", "New Skill Checklist", "FEAT-1045"),
    # REMOVED (stale/false-positive): (".claude/CLAUDE.md", "/doctor", "FEAT-1045"),
    ("docs/reference/CLI.md", "New Skill Checklist", "FEAT-1045"),
    # REMOVED (stale/false-positive): ("docs/reference/CLI.md", "/doctor", "FEAT-1045"),
    ("docs/reference/CLI.md", "disable-model-invocation", "FEAT-1045"),
    # REMOVED (stale/false-positive): ("commands/help.md", "name:", "FEAT-1045"),
    (".claude/CLAUDE.md", "name:", "FEAT-1045"),
    ("docs/reference/CLI.md", "name:", "FEAT-1045"),
    # REMOVED (stale/false-positive): ("commands/help.md", "Authorize all 29", "FEAT-1045"),
    # REMOVED (stale/false-positive): (".claude/CLAUDE.md", "Bash(ll-harness:*)", "FEAT-1045"),
    # REMOVED (stale/false-positive): (".claude/CLAUDE.md", "DecisionsConfig", "FEAT-1045"),
    # REMOVED (stale/false-positive): ("docs/reference/CLI.md", "DecisionsConfig", "FEAT-1045"),
    # REMOVED (stale/false-positive): ("commands/help.md", "Bash(ll-logs:*)", "ll-logs"),
]


@pytest.mark.parametrize("doc_rel, needle, issue_id", DOC_STRINGS_PRESENT)
def test_string_present_in_doc(
    project_root: Path, doc_rel: str, needle: str, issue_id: str
) -> None:
    """Verify that expected strings appear in documentation files."""
    content = (project_root / doc_rel).read_text()
    assert needle in content, "[{issue_id}] {doc_rel} must contain: {needle!r}"


# -- 13 string-absence assertions --------------------------------

DOC_STRINGS_ABSENT: list[tuple[str, str, str]] = [
    # (doc_path, forbidden_string, issue_id)
    (".claude/CLAUDE.md", "/tmp/ll-scratch", "ENH-1130"),
    ("docs/reference/CLI.md", "log_file` is `null` for foreground runs", "ENH-1704"),
    ("commands/help.md", "Goals file exists", "ENH-1443"),
    ("docs/reference/CLI.md", "FEAT-1893", "FEAT-948"),
    ("docs/reference/CLI.md", "--status active", "ENH-1428"),
    ("docs/reference/CLI.md", "--status completed", "ENH-1428"),
    ("docs/reference/CLI.md", "active (default)", "ENH-1428"),
    ("docs/reference/CLI.md", "active category directories", "ENH-1428"),
    ("docs/reference/CLI.md", "{active,completed,deferred,all}", "ENH-1428"),
    ("docs/reference/CLI.md", "List all active issues", "ENH-1428"),
    ("docs/reference/CLI.md", "never create a `.log` file", "ENH-1704"),
    ("docs/reference/CLI.md", "log_file is null for foreground runs", "ENH-1704"),
    (".claude/CLAUDE.md", "FEAT-1893", "FEAT-1045"),
]


@pytest.mark.parametrize("doc_rel, needle, issue_id", DOC_STRINGS_ABSENT)
def test_string_absent_from_doc(
    project_root: Path, doc_rel: str, needle: str, issue_id: str
) -> None:
    """Verify that stale/forbidden strings do NOT appear in documentation files."""
    content = (project_root / doc_rel).read_text()
    assert needle not in content, "[{issue_id}] {doc_rel} must NOT contain: {needle!r}"


# -- 1 file-existence assertions -----------------------------------

DOC_FILES_MUST_EXIST: list[tuple[str, str]] = [
    # (file_path, issue_id)
    ("docs/reference/CLI.md", "ENH-1859"),
]


@pytest.mark.parametrize("doc_rel, issue_id", DOC_FILES_MUST_EXIST)
def test_file_exists(project_root: Path, doc_rel: str, issue_id: str) -> None:
    """Verify that expected documentation files exist."""
    assert (project_root / doc_rel).exists(), "[{issue_id}] File must exist: {doc_rel}"
