"""Tests for FEAT-1532 / FEAT-1543: loop-specialist agent doc wiring.

Verifies that the loop-specialist agent is fully wired into every surface that
counts or lists agents: the agent file itself, the generated Codex TOML, the
plugin manifest, the README/CONTRIBUTING/ARCHITECTURE agent counts, and the
``## Agents`` section in docs/reference/API.md.
"""

from __future__ import annotations

from pathlib import Path

PROJECT_ROOT = Path(__file__).parent.parent.parent

AGENT_FILE = PROJECT_ROOT / "agents" / "loop-specialist.md"
TOML_FILE = PROJECT_ROOT / ".codex" / "agents" / "loop-specialist.toml"
README = PROJECT_ROOT / "README.md"
CONTRIBUTING = PROJECT_ROOT / "CONTRIBUTING.md"
ARCHITECTURE = PROJECT_ROOT / "docs" / "ARCHITECTURE.md"
API_DOC = PROJECT_ROOT / "docs" / "reference" / "API.md"
PLUGIN_JSON = PROJECT_ROOT / ".claude-plugin" / "plugin.json"


class TestAgentFileWiring:
    """agents/loop-specialist.md must exist with the required frontmatter."""

    def test_agent_file_exists(self) -> None:
        assert AGENT_FILE.exists(), "agents/loop-specialist.md must exist"

    def test_agent_has_name_field(self) -> None:
        content = AGENT_FILE.read_text()
        assert "name: loop-specialist" in content, (
            "agents/loop-specialist.md must declare `name: loop-specialist` in frontmatter"
        )

    def test_agent_has_model_field(self) -> None:
        content = AGENT_FILE.read_text()
        assert "model:" in content, "agents/loop-specialist.md must declare a `model:` field"

    def test_agent_has_tools_field(self) -> None:
        content = AGENT_FILE.read_text()
        assert "tools:" in content, "agents/loop-specialist.md must declare a `tools:` field"

    def test_agent_references_diagnostics_path(self) -> None:
        content = AGENT_FILE.read_text()
        assert ".loops/diagnostics/" in content, (
            "agent must reference the diagnosis artifact path `.loops/diagnostics/<loop>-<ts>.md`"
        )

    def test_agent_uses_json_flag_for_history(self) -> None:
        content = AGENT_FILE.read_text()
        assert "ll-loop history" in content and "--json" in content, (
            "agent must specify `ll-loop history <name> --json` for machine-parseable output"
        )

    def test_toml_exists(self) -> None:
        assert TOML_FILE.exists(), (
            ".codex/agents/loop-specialist.toml must exist (run `ll-adapt-agents-for-codex --apply`)"
        )

    def test_toml_has_generated_marker(self) -> None:
        content = TOML_FILE.read_text()
        assert content.startswith("# generated by ll-adapt-agents-for-codex"), (
            ".codex/agents/loop-specialist.toml must start with the generated-by marker comment"
        )


class TestDocCountWiring:
    """README, CONTRIBUTING, and ARCHITECTURE must all say `9` agents."""

    def test_readme_says_9(self) -> None:
        assert "9 specialized agents" in README.read_text(), (
            "README.md must say `9 specialized agents` (was 8 before FEAT-1543)"
        )

    def test_contributing_says_9(self) -> None:
        assert "9 agent definitions" in CONTRIBUTING.read_text(), (
            "CONTRIBUTING.md must say `9 agent definitions` (was 8 before FEAT-1543)"
        )

    def test_architecture_says_9(self) -> None:
        assert "9 specialized agents" in ARCHITECTURE.read_text(), (
            "docs/ARCHITECTURE.md must say `9 specialized agents` (was 8 before FEAT-1543)"
        )


class TestApiMdWiring:
    """docs/reference/API.md must list the loop-specialist agent."""

    def test_api_md_has_loop_specialist(self) -> None:
        assert "loop-specialist" in API_DOC.read_text(), (
            "docs/reference/API.md must list loop-specialist in its `## Agents` section"
        )


class TestPluginJsonWiring:
    """.claude-plugin/plugin.json must include the agent entry."""

    def test_plugin_json_has_agent(self) -> None:
        assert '"./agents/loop-specialist.md"' in PLUGIN_JSON.read_text(), (
            "plugin.json `agents` array must include `./agents/loop-specialist.md`"
        )
