"""Tests for /ll:verify-issue-loop skill artifacts.

Since /ll:verify-issue-loop is a prompt-based skill (markdown instructions
for Claude), we test:

1. Expected emitted YAML structure for a multi-criterion issue
2. Linear pass-routing: on_yes chains forward, final on_yes -> done
3. Shared failure routing: every verify state's on_no -> failed
4. Both done and failed are terminal: true
5. Generated YAML passes FSM validation via load_and_validate + validate_fsm
"""

from __future__ import annotations

import sys
from pathlib import Path

import pytest
import yaml

from little_loops.fsm.validation import ValidationSeverity, load_and_validate, validate_fsm

# ---------------------------------------------------------------------------
# Fixture — module-scope inline YAML representing expected emitted output
# for a 3-criterion issue. Mirrors VARIANT_A_YAML in test_create_eval_from_issues.
# ---------------------------------------------------------------------------

VERIFY_YAML_3_CRITERIA = """
name: verify-feat-919-add-json-schema-generation
category: verification
description: |
  Verification loop for FEAT-919: Add JSON schema generation.
  Walks each acceptance criterion in order; fails fast on any criterion that fails.
  Generated by /ll:verify-issue-loop.
initial: verify-criterion-1
max_iterations: 20
timeout: 1800

states:
  verify-criterion-1:
    action: >
      Verify acceptance criterion 1 for FEAT-919: The schema builder accepts a
      sample input object without errors. Inspect the implementation, run any
      commands needed, and gather concrete evidence about whether the criterion
      holds. Report what you observed.
    action_type: prompt
    timeout: 300
    evaluate:
      type: llm_structured
      prompt: >
        Does the implementation satisfy criterion 1 of FEAT-919?

        Criterion: The schema builder accepts a sample input object without errors.

        Answer YES only if the evidence clearly shows the criterion is met.
        Answer NO if the criterion is not met or evidence is missing/ambiguous.
        Provide a one-sentence reason citing the observed evidence.
    on_yes: verify-criterion-2
    on_no: failed

  verify-criterion-2:
    action: >
      Verify acceptance criterion 2 for FEAT-919: A valid, readable JSON schema
      is returned. Inspect the implementation, run any commands needed, and
      gather concrete evidence about whether the criterion holds. Report what
      you observed.
    action_type: prompt
    timeout: 300
    evaluate:
      type: llm_structured
      prompt: >
        Does the implementation satisfy criterion 2 of FEAT-919?

        Criterion: A valid, readable JSON schema is returned.

        Answer YES only if the evidence clearly shows the criterion is met.
        Answer NO if the criterion is not met or evidence is missing/ambiguous.
        Provide a one-sentence reason citing the observed evidence.
    on_yes: verify-criterion-3
    on_no: failed

  verify-criterion-3:
    action: >
      Verify acceptance criterion 3 for FEAT-919: The generated schema validates
      a representative sample without errors. Inspect the implementation, run
      any commands needed, and gather concrete evidence about whether the
      criterion holds. Report what you observed.
    action_type: prompt
    timeout: 300
    evaluate:
      type: llm_structured
      prompt: >
        Does the implementation satisfy criterion 3 of FEAT-919?

        Criterion: The generated schema validates a representative sample without errors.

        Answer YES only if the evidence clearly shows the criterion is met.
        Answer NO if the criterion is not met or evidence is missing/ambiguous.
        Provide a one-sentence reason citing the observed evidence.
    on_yes: done
    on_no: failed

  done:
    terminal: true

  failed:
    terminal: true
"""


# ---------------------------------------------------------------------------
# Structural Tests — single-issue verification loop shape
# ---------------------------------------------------------------------------


class TestVerifyLoopSingleIssue:
    """Structural tests for a single-issue verification loop (3 criteria)."""

    @pytest.fixture
    def loop(self) -> dict:
        return yaml.safe_load(VERIFY_YAML_3_CRITERIA)

    def test_parses_as_yaml(self, loop: dict) -> None:
        assert isinstance(loop, dict)

    def test_initial_state_is_first_verify_criterion(self, loop: dict) -> None:
        assert loop.get("initial") == "verify-criterion-1"

    def test_category_is_verification(self, loop: dict) -> None:
        assert loop.get("category") == "verification"

    def test_has_all_verify_criterion_states(self, loop: dict) -> None:
        states = loop.get("states", {})
        for n in (1, 2, 3):
            assert f"verify-criterion-{n}" in states, f"missing verify-criterion-{n}"

    def test_verify_states_are_prompt_type(self, loop: dict) -> None:
        states = loop["states"]
        for n in (1, 2, 3):
            state = states[f"verify-criterion-{n}"]
            assert state.get("action_type") == "prompt"

    def test_verify_states_have_llm_structured_evaluator(self, loop: dict) -> None:
        states = loop["states"]
        for n in (1, 2, 3):
            evaluate = states[f"verify-criterion-{n}"].get("evaluate", {})
            assert evaluate.get("type") == "llm_structured"

    def test_verify_state_prompts_are_substantive(self, loop: dict) -> None:
        states = loop["states"]
        for n in (1, 2, 3):
            prompt = states[f"verify-criterion-{n}"].get("evaluate", {}).get("prompt", "")
            assert len(prompt) > 20, f"llm_structured prompt for criterion {n} too short"

    def test_non_final_states_route_on_yes_to_next_criterion(self, loop: dict) -> None:
        states = loop["states"]
        assert states["verify-criterion-1"].get("on_yes") == "verify-criterion-2"
        assert states["verify-criterion-2"].get("on_yes") == "verify-criterion-3"

    def test_final_state_routes_on_yes_to_done(self, loop: dict) -> None:
        states = loop["states"]
        assert states["verify-criterion-3"].get("on_yes") == "done"

    def test_every_verify_state_routes_on_no_to_failed(self, loop: dict) -> None:
        states = loop["states"]
        for n in (1, 2, 3):
            assert states[f"verify-criterion-{n}"].get("on_no") == "failed"

    def test_has_terminal_done_state(self, loop: dict) -> None:
        states = loop.get("states", {})
        assert "done" in states
        assert states["done"].get("terminal") is True

    def test_has_terminal_failed_state(self, loop: dict) -> None:
        states = loop.get("states", {})
        assert "failed" in states
        assert states["failed"].get("terminal") is True

    def test_no_discover_state(self, loop: dict) -> None:
        """Single-issue scope — no multi-issue discover/advance states."""
        assert "discover" not in loop.get("states", {})

    def test_no_advance_state(self, loop: dict) -> None:
        """Single-issue scope — no multi-issue discover/advance states."""
        assert "advance" not in loop.get("states", {})

    def test_no_check_invariants(self, loop: dict) -> None:
        """Verification loops do not include check_invariants (diff size gate)."""
        assert "check_invariants" not in loop.get("states", {})

    def test_no_check_stall(self, loop: dict) -> None:
        assert "check_stall" not in loop.get("states", {})


# ---------------------------------------------------------------------------
# Validation Tests — generated YAML passes FSM validation
# ---------------------------------------------------------------------------


class TestVerifyLoopValidation:
    """Tests that generated YAML passes ll-loop validate (via load_and_validate)."""

    @pytest.fixture
    def loops_dir(self, tmp_path: Path) -> Path:
        loops = tmp_path / ".loops"
        loops.mkdir()
        return loops

    def test_passes_fsm_validation(
        self, loops_dir: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        """3-criterion verify YAML passes FSM structural validation."""
        path = loops_dir / "verify-feat-919-add-json-schema-generation.yaml"
        path.write_text(VERIFY_YAML_3_CRITERIA)
        monkeypatch.chdir(loops_dir.parent)

        fsm, _ = load_and_validate(path)
        errors = validate_fsm(fsm)
        hard_errors = [e for e in errors if e.severity == ValidationSeverity.ERROR]
        assert not hard_errors, f"FSM errors: {[str(e) for e in hard_errors]}"

    def test_passes_via_cli(self, loops_dir: Path, monkeypatch: pytest.MonkeyPatch) -> None:
        """3-criterion verify YAML passes ll-loop validate CLI (exit 0)."""
        name = "verify-feat-919-add-json-schema-generation"
        (loops_dir / f"{name}.yaml").write_text(VERIFY_YAML_3_CRITERIA)
        monkeypatch.chdir(loops_dir.parent)

        with pytest.MonkeyPatch.context() as mp:
            mp.setattr(sys, "argv", ["ll-loop", "validate", name])
            from little_loops.cli import main_loop

            result = main_loop()

        assert result == 0
