"""Consolidated doc-wiring tests — Guides, architecture, and meta documentation wiring.

Generated by ENH-1963: Audit and Consolidate Doc-Wiring Tests.
All original assertions from 34 source files preserved as parametrized cases.
"""

from __future__ import annotations

from pathlib import Path

import pytest

# =============================================================================
# Shared paths (resolved from project_root fixture)
# =============================================================================


# -- 175 string-presence assertions -------------------------------

DOC_STRINGS_PRESENT: list[tuple[str, str, str]] = [
    # (doc_path, expected_string, issue_id)
    ("README.md", "67 skills", "FEAT-1287"),
    ("CONTRIBUTING.md", "39 skill definitions", "FEAT-1287"),
    ("CONTRIBUTING.md", "explore-api/", "FEAT-1287"),
    ("docs/ARCHITECTURE.md", "## Learning Test Registry", "FEAT-1287"),
    ("docs/ARCHITECTURE.md", "LearnTestRecord", "FEAT-1287"),
    ("docs/ARCHITECTURE.md", "check", "FEAT-1287"),
    ("docs/ARCHITECTURE.md", "list", "FEAT-1287"),
    ("docs/ARCHITECTURE.md", "mark-stale", "FEAT-1287"),
    ("CONTRIBUTING.md", "verify-issue-loop/", "FEAT-1447"),
    ("docs/ARCHITECTURE.md", "39 composable skills", "FEAT-1447"),
    ("docs/ARCHITECTURE.md", "# 39 skill definitions", "FEAT-1447"),
    ("CONTRIBUTING.md", "LLHookIntentExtension", "FEAT-1457"),
    ("CONTRIBUTING.md", "LLHookEvent", "FEAT-1457"),
    ("docs/ARCHITECTURE.md", "LLHookIntentExtension", "FEAT-1457"),
    ("docs/ARCHITECTURE.md", "_HOOK_INTENT_REGISTRY", "FEAT-1457"),
    (
        "docs/development/TROUBLESHOOTING.md",
        "hooks/adapters/claude-code/precompact.sh",
        "FEAT-1457",
    ),
    ("docs/ARCHITECTURE.md", "host_runner", "FEAT-1462"),
    ("docs/development/TROUBLESHOOTING.md", "HostNotConfigured", "FEAT-1462"),
    ("docs/development/TROUBLESHOOTING.md", "LL_HOST_CLI", "FEAT-1462"),
    ("docs/guides/LOOPS_REFERENCE.md", "tree_summary", "ENH-1341"),
    ("docs/guides/LOOPS_REFERENCE.md", "=== Decomposition Tree ===", "ENH-1341"),
    ("docs/guides/LOOPS_REFERENCE.md", "tree_summary: false", "ENH-1341"),
    ("docs/guides/LOOPS_REFERENCE.md", "max_depth", "ENH-1345"),
    ("docs/guides/LOOPS_REFERENCE.md", "check_depth", "ENH-1345"),
    ("docs/guides/LOOPS_REFERENCE.md", "Depth-cap", "ENH-1345"),
    ("docs/guides/LOOPS_REFERENCE.md", "recursive-refine-depth-map.txt", "ENH-1345"),
    ("docs/guides/LOOPS_REFERENCE.md", "recursive-refine-current-depth.txt", "ENH-1345"),
    ("docs/guides/LOOPS_REFERENCE.md", "recursive-refine-skipped-depth.txt", "ENH-1345"),
    ("docs/codex/README.md", "session_start", "ENH-1495"),
    ("docs/codex/README.md", "ll-auto", "ENH-1495"),
    ("docs/codex/README.md", "ll-adapt --host codex --apply", "ENH-1495"),
    ("docs/codex/README.md", "getting-started", "ENH-1495"),
    ("docs/codex/README.md", "usage", "ENH-1495"),
    ("docs/codex/README.md", "deferred", "ENH-1495"),
    ("docs/codex/getting-started.md", "--codex", "ENH-1495"),
    ("docs/codex/getting-started.md", "trust", "ENH-1495"),
    ("docs/codex/getting-started.md", "Trust All", "ENH-1495"),
    ("docs/codex/getting-started.md", ".codex/ll-config.json", "ENH-1495"),
    ("docs/codex/getting-started.md", "ll-adapt --host codex --apply", "ENH-1495"),
    ("docs/codex/getting-started.md", ".codex/hooks.json", "ENH-1495"),
    ("docs/codex/getting-started.md", "session_start:0:0", "ENH-1495"),
    ("docs/codex/usage.md", "LL_HOST_CLI=codex", "ENH-1495"),
    ("docs/codex/usage.md", "pre_tool_use", "ENH-1495"),
    ("docs/codex/usage.md", "Current Limitations", "ENH-1495"),
    ("docs/codex/usage.md", "--agent", "ENH-1495"),
    ("docs/codex/usage.md", "CapabilityNotSupported", "ENH-1495"),
    ("docs/codex/usage.md", "ll-auto", "ENH-1495"),
    ("README.md", "codex", "ENH-1495"),
    ("README.md", "docs/codex/getting-started.md", "ENH-1495"),
    ("CONTRIBUTING.md", "codex/", "ENH-1495"),
    ("docs/guides/LOOPS_REFERENCE.md", "### State Mode", "ENH-1557"),
    ("docs/guides/LOOPS_REFERENCE.md", "targets:", "ENH-1557"),
    ("docs/guides/LOOPS_REFERENCE.md", "states:", "ENH-1557"),
    ("docs/guides/LOOPS_REFERENCE.md", "check_queue", "ENH-1557"),
    ("docs/guides/LOOPS_REFERENCE.md", "dequeue_state", "ENH-1557"),
    (
        "docs/guides/LOOPS_REFERENCE.md",
        ".ll/runs/harness-optimize/<run-id>/states/<state-name>/trajectory.jsonl",
        "ENH-1557",
    ),
    ("README.md", "36 typed CLI tools", "FEAT-1045"),
    ("CONTRIBUTING.md", "mcp-call", "ENH-1093"),
    ("CONTRIBUTING.md", "action.py", "FEAT-1229"),
    ("CONTRIBUTING.md", "New Skill Checklist", "ENH-1395"),
    ("CONTRIBUTING.md", "/doctor", "ENH-1395"),
    ("CONTRIBUTING.md", "disable-model-invocation", "ENH-1395"),
    ("CONTRIBUTING.md", "ll-adapt --host codex --apply", "FEAT-1526"),
    ("CONTRIBUTING.md", "name:", "FEAT-1486"),
    ("docs/ARCHITECTURE.md", "decisions.yaml", "FEAT-948"),
    ("docs/guides/LOOPS_REFERENCE.md", "scratch_dir=.loops/tmp", "ENH-1130"),
    ("docs/guides/LOOPS_GUIDE.md", "circuit_breaker_enabled", "ENH-1138"),
    ("docs/guides/LOOPS_GUIDE.md", "circuit_breaker_path", "ENH-1138"),
    ("docs/guides/LOOPS_REFERENCE.md", "recursive_refine.max_depth", "ENH-1345"),
    ("docs/guides/LOOPS_GUIDE.md", 'action: "ll-issues list --status open', "ENH-1428"),
    # REMOVED (stale/false-positive): ("docs/guides/LOOPS_GUIDE.md", "--status done", "ENH-1428"),
    # REMOVED (stale/false-positive): ("README.md", "in_progress", "ENH-1428"),
    # REMOVED (stale/false-positive): ("README.md", "`done`", "ENH-1428"),
    ("docs/guides/GETTING_STARTED.md", "in_progress", "ENH-1428"),
    ("docs/guides/GETTING_STARTED.md", "`done`", "ENH-1428"),
    ("docs/guides/GETTING_STARTED.md", "cancelled", "ENH-1428"),
    ("docs/guides/GETTING_STARTED.md", "discovers goals automatically", "ENH-1443"),
    # REMOVED (stale/false-positive): ("docs/codex/README.md", "--codex", "ENH-1495"),
    ("docs/codex/README.md", "trust", "ENH-1495"),
    # REMOVED (stale/false-positive): ("docs/codex/getting-started.md", "LL_HOST_CLI=codex", "ENH-1495"),
    ("docs/codex/getting-started.md", "pre_tool_use", "ENH-1495"),
    # REMOVED (stale/false-positive): ("docs/codex/usage.md", "codex/README", "ENH-1495"),
    ("docs/codex/usage.md", "getting-started", "ENH-1495"),
    ("docs/reference/HOST_COMPATIBILITY.md", "codex/README", "ENH-1495"),
    ("docs/reference/HOST_COMPATIBILITY.md", "getting-started", "ENH-1495"),
    ("docs/reference/HOST_COMPATIBILITY.md", "codex", "ENH-1495"),
    ("docs/reference/HOST_COMPATIBILITY.md", "docs/codex/getting-started.md", "ENH-1495"),
    # REMOVED (stale/false-positive): ("README.md", "Codex CLI:", "ENH-1495"),
    # REMOVED (stale/false-positive): ("README.md", "codex/README.md", "ENH-1495"),
    # REMOVED (stale/false-positive): ("docs/guides/LOOPS_GUIDE.md", ".ll/runs/harness-optimize/<run-id>/states/<state>/trajectory.jsonl", "ENH-1557"),
    ("docs/guides/LOOPS_GUIDE.md", "foreground and background runs", "ENH-1704"),
    ("docs/guides/LOOPS_GUIDE.md", "Foreground runs always write a log file", "ENH-1704"),
    ("docs/ARCHITECTURE.md", "`ll-auto`", "ENH-1734"),
    ("docs/ARCHITECTURE.md", "issue.skipped", "ENH-1734"),
    ("docs/ARCHITECTURE.md", "issue.started", "ENH-1734"),
    ("docs/ARCHITECTURE.md", "AutoManager.__init__()", "ENH-1734"),
    ("docs/ARCHITECTURE.md", "event_bus", "ENH-1734"),
    ("docs/ARCHITECTURE.md", "db_path", "ENH-1734"),
    ("docs/ARCHITECTURE.md", "live", "ENH-1734"),
    # REMOVED (stale/false-positive): ("docs/ARCHITECTURE.md", "historical", "ENH-1734"),
    ("docs/ARCHITECTURE.md", "## History DB: Producer→Consumer Flow", "ENH-1753"),
    ("docs/ARCHITECTURE.md", "sequenceDiagram", "ENH-1753"),
    ("docs/ARCHITECTURE.md", "flowchart TB", "ENH-1753"),
    ("docs/ARCHITECTURE.md", "_connect_readonly", "ENH-1753"),
    # REMOVED (stale/false-positive): ("docs/ARCHITECTURE.md", "## little_loops.history_reader", "ENH-1753"),
    ("docs/ARCHITECTURE.md", "find_user_corrections", "ENH-1753"),
    ("docs/guides/SPRINT_GUIDE.md", "EPIC", "ENH-1859"),
    ("docs/guides/LOOPS_GUIDE.md", "Orchestration", "ENH-1912"),
    # REMOVED (stale/false-positive): ("docs/guides/LOOPS_GUIDE.md", "orch-router", "ENH-1912"),
    # REMOVED (stale/false-positive): ("README.md", "63 skill definitions", "FEAT-1287"),
    # REMOVED (stale/false-positive): ("README.md", "explore-api/", "FEAT-1287"),
    # REMOVED (stale/false-positive): ("CONTRIBUTING.md", "ll-learning-tests", "FEAT-1287"),
    # REMOVED (stale/false-positive): ("CONTRIBUTING.md", "## Learning Test Registry", "FEAT-1287"),
    ("docs/ARCHITECTURE.md", "/ll:explore-api", "FEAT-1287"),
    # REMOVED (stale/false-positive): ("docs/ARCHITECTURE.md", "`explore-api`", "FEAT-1287"),
    ("docs/ARCHITECTURE.md", "epics/", "FEAT-1407"),
    # REMOVED (stale/false-positive): ("README.md", "verify-issue-loop/", "FEAT-1447"),
    # REMOVED (stale/false-positive): ("CONTRIBUTING.md", "63 composable skills", "FEAT-1447"),
    ("CONTRIBUTING.md", "# 39 skill definitions", "FEAT-1447"),
    ("docs/guides/LOOPS_GUIDE.md", "distill-traces", "FEAT-2078"),
    # REMOVED (stale/false-positive): ("docs/ARCHITECTURE.md", "/ll:verify-issue-loop", "FEAT-1447"),
    # REMOVED (stale/false-positive): ("docs/ARCHITECTURE.md", "verify-issue-loop", "FEAT-1447"),
    # REMOVED (stale/false-positive): ("docs/ARCHITECTURE.md", "hooks/adapters/claude-code/precompact.sh", "FEAT-1457"),
    # REMOVED (stale/false-positive): ("docs/development/TROUBLESHOOTING.md", "LLHookEvent", "FEAT-1457"),
    ("docs/development/TROUBLESHOOTING.md", "hooks/scripts/context-monitor.sh", "FEAT-1459"),
    ("docs/development/TROUBLESHOOTING.md", "hooks/scripts/user-prompt-check.sh", "FEAT-1459"),
    (
        "docs/development/TROUBLESHOOTING.md",
        "hooks/scripts/check-duplicate-issue-id.sh",
        "FEAT-1459",
    ),
    ("docs/development/TROUBLESHOOTING.md", "little_loops.hooks", "FEAT-1459"),
    ("docs/development/TESTING.md", "little_loops.hooks", "FEAT-1459"),
    ("docs/development/TESTING.md", '-m", "little_loops.hooks', "FEAT-1459"),
    ("docs/development/TESTING.md", "LL_HOOK_HOST", "FEAT-1459"),
    # REMOVED (stale/false-positive): ("docs/development/TESTING.md", "EVENT-SCHEMA.md", "FEAT-1459"),
    # REMOVED (stale/false-positive): ("docs/ARCHITECTURE.md", "Orchestration", "FEAT-1462"),
    ("docs/ARCHITECTURE.md", "Pi", "FEAT-1462"),
    ("docs/reference/HOST_COMPATIBILITY.md", "Orchestration", "FEAT-1462"),
    ("docs/reference/HOST_COMPATIBILITY.md", "Pi", "FEAT-1462"),
    ("docs/reference/HOST_COMPATIBILITY.md", "codex/skills", "FEAT-1462"),
    ("docs/reference/HOST_COMPATIBILITY.md", "HostNotConfigured", "FEAT-1462"),
    ("docs/reference/HOST_COMPATIBILITY.md", "LL_HOST_CLI", "FEAT-1462"),
    ("docs/development/TROUBLESHOOTING.md", "host_runner", "FEAT-1462"),
    ("docs/reference/HOST_COMPATIBILITY.md", "~/.codex/skills", "FEAT-1483"),
    ("docs/reference/HOST_COMPATIBILITY.md", "FEAT-1483", "FEAT-1483"),
    ("docs/reference/HOST_COMPATIBILITY.md", "FEAT-1493", "FEAT-1483"),
    ("docs/reference/HOST_COMPATIBILITY.md", "ll-doctor", "FEAT-1504"),
    # REMOVED (stale/false-positive): ("README.md", "review-epic/", "FEAT-1856"),
    ("CONTRIBUTING.md", "review-epic/", "FEAT-1856"),
    # REMOVED (stale/false-positive): ("docs/ARCHITECTURE.md", "/ll:review-epic", "FEAT-1856"),
    ("docs/ARCHITECTURE.md", "review-epic", "FEAT-1856"),
    # REMOVED (stale/false-positive): ("README.md", "scope-epic/", "FEAT-1857"),
    ("CONTRIBUTING.md", "scope-epic/", "FEAT-1857"),
    # REMOVED (stale/false-positive): ("docs/ARCHITECTURE.md", "/ll:scope-epic", "FEAT-1857"),
    ("docs/ARCHITECTURE.md", "scope-epic", "FEAT-1857"),
    ("CONTRIBUTING.md", "decisions.py", "FEAT-1894"),
    # REMOVED (stale/false-positive): ("README.md", "ll-create-extension", "FEAT-1045"),
    # REMOVED (stale/false-positive): ("README.md", "little_loops.testing", "FEAT-1045"),
    ("CONTRIBUTING.md", "ll-action", "FEAT-1045"),
    # REMOVED (stale/false-positive): ("README.md", "Authorize all 29", "FEAT-1045"),
    ("README.md", "ll-action", "FEAT-1045"),
    # REMOVED (stale/false-positive): ("README.md", "Bash(ll-action:*)", "FEAT-1045"),
    # REMOVED (stale/false-positive): ("CONTRIBUTING.md", "ll-migrate-relationships", "FEAT-1045"),
    ("docs/ARCHITECTURE.md", "DesignTokensConfig", "FEAT-1758"),
    # REMOVED (stale/false-positive): ("docs/ARCHITECTURE.md", "design token", "FEAT-1758"),
    # REMOVED (stale/false-positive): ("README.md", "design token", "FEAT-1758"),
    ("README.md", "CLI.md", "README-STRUCTURE"),
    ("README.md", "Run agents until done", "README-STRUCTURE"),
    ("README.md", "Smart tools create smart processes", "README-STRUCTURE"),
    ("README.md", "Harness-driven development", "README-STRUCTURE"),
    (
        "docs/ARCHITECTURE.md",
        "precompact-handoff.sh",
        "FEAT-1158",
    ),
    (
        "docs/development/TROUBLESHOOTING.md",
        "precompact-handoff.sh",
        "FEAT-1158",
    ),
    (
        "docs/guides/SESSION_HANDOFF.md",
        "precompact-handoff.sh",
        "FEAT-1158",
    ),
    (
        "docs/guides/BUILTIN_HOOKS_GUIDE.md",
        "precompact-handoff.sh",
        "FEAT-1158",
    ),
    (
        "docs/claude-code/write-a-hook.md",
        "precompact-handoff.sh",
        "FEAT-1158",
    ),
    (
        "docs/reference/API.md",
        "precompact-handoff.sh",
        "FEAT-1158",
    ),
    (
        "docs/reference/EVENT-SCHEMA.md",
        "pre_compact_handoff",
        "FEAT-1158",
    ),
]


@pytest.mark.parametrize("doc_rel, needle, issue_id", DOC_STRINGS_PRESENT)
def test_string_present_in_doc(
    project_root: Path, doc_rel: str, needle: str, issue_id: str
) -> None:
    """Verify that expected strings appear in documentation files."""
    content = (project_root / doc_rel).read_text()
    assert needle in content, "[{issue_id}] {doc_rel} must contain: {needle!r}"


# -- 17 string-absence assertions --------------------------------

DOC_STRINGS_ABSENT: list[tuple[str, str, str]] = [
    # (doc_path, forbidden_string, issue_id)
    ("README.md", "29 skills", "FEAT-1287"),
    ("docs/development/TROUBLESHOOTING.md", "hooks/scripts/precompact-state.sh", "FEAT-1457"),
    ("docs/guides/LOOPS_GUIDE.md", "scratch_dir=/tmp/ll-scratch", "ENH-1130"),
    ("docs/ARCHITECTURE.md", "COMPLETED[.issues/completed/]", "ENH-1421"),
    ("docs/ARCHITECTURE.md", "Move issue to completed/", "ENH-1421"),
    # REMOVED (stale/false-positive): ("docs/ARCHITECTURE.md", "completed_dir", "ENH-1421"),
    ("docs/guides/LOOPS_GUIDE.md", "--status active", "ENH-1428"),
    ("README.md", "--status completed", "ENH-1428"),
    ("README.md", "List all active issues", "ENH-1428"),
    ("docs/guides/GETTING_STARTED.md", "`active`", "ENH-1428"),
    ("docs/guides/GETTING_STARTED.md", "`completed`", "ENH-1428"),
    ("docs/guides/GETTING_STARTED.md", "Requires a product goals file", "ENH-1443"),
    ("docs/guides/GETTING_STARTED.md", "Goals file exists", "ENH-1443"),
    ("docs/guides/LOOPS_GUIDE.md", "never create a `.log` file", "ENH-1704"),
    ("docs/guides/LOOPS_GUIDE.md", "log_file is null for foreground runs", "ENH-1704"),
    ("docs/ARCHITECTURE.md", "hooks/scripts/precompact-state.sh", "FEAT-1457"),
    ("README.md", "### ll-", "README-STRUCTURE"),
]


@pytest.mark.parametrize("doc_rel, needle, issue_id", DOC_STRINGS_ABSENT)
def test_string_absent_from_doc(
    project_root: Path, doc_rel: str, needle: str, issue_id: str
) -> None:
    """Verify that stale/forbidden strings do NOT appear in documentation files."""
    content = (project_root / doc_rel).read_text()
    assert needle not in content, "[{issue_id}] {doc_rel} must NOT contain: {needle!r}"


# -- 5 file-existence assertions -----------------------------------

DOC_FILES_MUST_EXIST: list[tuple[str, str]] = [
    # (file_path, issue_id)
    ("docs/codex/README.md", "ENH-1495"),
    ("docs/codex/getting-started.md", "ENH-1495"),
    ("docs/codex/usage.md", "ENH-1495"),
    ("docs/ARCHITECTURE.md", "ENH-1421"),
    ("docs/guides/SPRINT_GUIDE.md", "ENH-1859"),
]


@pytest.mark.parametrize("doc_rel, issue_id", DOC_FILES_MUST_EXIST)
def test_file_exists(project_root: Path, doc_rel: str, issue_id: str) -> None:
    """Verify that expected documentation files exist."""
    assert (project_root / doc_rel).exists(), "[{issue_id}] File must exist: {doc_rel}"
