"""Tests for FEAT-1857: scope-epic skill wiring and doc count updates.

Asserts that the scope-epic skill file exists, documentation surfaces reference it,
config-schema.json declares the epics.scope block, and skill counts are bumped.
"""

from __future__ import annotations

import json
from pathlib import Path

PROJECT_ROOT = Path(__file__).parent.parent.parent

README = PROJECT_ROOT / "README.md"
CONTRIBUTING = PROJECT_ROOT / "CONTRIBUTING.md"
ARCHITECTURE = PROJECT_ROOT / "docs" / "ARCHITECTURE.md"
HELP_CMD = PROJECT_ROOT / "commands" / "help.md"
CLAUDE_MD = PROJECT_ROOT / ".claude" / "CLAUDE.md"
COMMANDS_MD = PROJECT_ROOT / "docs" / "reference" / "COMMANDS.md"
CONFIG_SCHEMA = PROJECT_ROOT / "config-schema.json"
SKILL_SCOPE_EPIC = PROJECT_ROOT / "skills" / "scope-epic" / "SKILL.md"
OPENAI_YAML = PROJECT_ROOT / "skills" / "scope-epic" / "agents" / "openai.yaml"


class TestScopeEpicSkillExists:
    """skills/scope-epic/SKILL.md and agents/openai.yaml must exist."""

    def test_skill_file_exists(self) -> None:
        assert SKILL_SCOPE_EPIC.exists(), "skills/scope-epic/SKILL.md must be created (FEAT-1857)"

    def test_openai_yaml_exists(self) -> None:
        assert OPENAI_YAML.exists(), (
            "skills/scope-epic/agents/openai.yaml must be generated by ll-adapt-skills-for-codex"
        )


class TestReadmeSkillCount:
    """README.md hero page must reflect 63 skills."""

    def test_skill_count_updated(self) -> None:
        content = README.read_text()
        assert "63 skills" in content, "README.md must show '63 skills'"


class TestContributingWiring:
    """CONTRIBUTING.md must reflect 63 skills and list scope-epic/ in the skills tree."""

    def test_skill_count_updated(self) -> None:
        content = CONTRIBUTING.read_text()
        assert "63 skill definitions" in content, (
            "CONTRIBUTING.md skill count line must show '63 skill definitions'"
        )

    def test_scope_epic_in_skills_tree(self) -> None:
        content = CONTRIBUTING.read_text()
        assert "scope-epic/" in content, "CONTRIBUTING.md skills tree must include 'scope-epic/'"


class TestArchitectureSkillCount:
    """docs/ARCHITECTURE.md must reflect 63 skills in both the Mermaid node and tree."""

    def test_mermaid_skill_count_updated(self) -> None:
        content = ARCHITECTURE.read_text()
        assert "63 composable skills" in content, (
            "ARCHITECTURE.md Mermaid node must show '63 composable skills'"
        )

    def test_tree_skill_count_updated(self) -> None:
        content = ARCHITECTURE.read_text()
        assert "# 63 skill definitions" in content, (
            "ARCHITECTURE.md directory tree must show '# 63 skill definitions'"
        )


class TestHelpCommandWiring:
    """commands/help.md must list /ll:scope-epic in the command reference and quick table."""

    def test_scope_epic_command_listed(self) -> None:
        content = HELP_CMD.read_text()
        assert "/ll:scope-epic" in content, (
            "commands/help.md must include /ll:scope-epic in the command reference"
        )

    def test_scope_epic_in_quick_reference(self) -> None:
        content = HELP_CMD.read_text()
        assert "scope-epic" in content, (
            "commands/help.md quick-reference Issue Discovery must include scope-epic"
        )


class TestClaudeMdWiring:
    """CLAUDE.md Commands & Skills section must mention scope-epic."""

    def test_scope_epic_in_claude_md(self) -> None:
        content = CLAUDE_MD.read_text()
        assert "scope-epic" in content, (
            ".claude/CLAUDE.md Commands & Skills section must mention scope-epic"
        )


class TestCommandsMdWiring:
    """docs/reference/COMMANDS.md must have a /ll:scope-epic section and Quick Reference row."""

    def test_scope_epic_section_exists(self) -> None:
        content = COMMANDS_MD.read_text()
        assert "### `/ll:scope-epic`" in content, (
            "docs/reference/COMMANDS.md must include ### `/ll:scope-epic` section"
        )

    def test_scope_epic_in_quick_reference_table(self) -> None:
        content = COMMANDS_MD.read_text()
        assert "| `scope-epic`" in content, (
            "docs/reference/COMMANDS.md Quick Reference table must include scope-epic row"
        )


class TestConfigSchemaWiring:
    """config-schema.json must declare epics.scope with min_children and max_children."""

    def test_epics_scope_in_schema(self) -> None:
        data = json.loads(CONFIG_SCHEMA.read_text())
        root_props = data["properties"]
        assert "epics" in root_props, (
            "epics top-level property is not declared in config-schema.json"
        )
        epics = root_props["epics"]
        assert epics["type"] == "object"
        epics_props = epics["properties"]
        assert "scope" in epics_props, (
            "epics.scope sub-object is not declared in config-schema.json"
        )
        scope = epics_props["scope"]
        assert scope["type"] == "object"
        scope_props = scope["properties"]
        assert scope_props["min_children"]["type"] == "integer"
        assert scope_props["min_children"]["minimum"] == 1
        assert scope_props["min_children"]["default"] == 3
        assert scope_props["max_children"]["type"] == "integer"
        assert scope_props["max_children"]["minimum"] == 1
        assert scope_props["max_children"]["default"] == 8
