"""Consolidated doc-wiring tests — Individual skill and command file documentation wiring.

Generated by ENH-1963: Audit and Consolidate Doc-Wiring Tests.
All original assertions from 31 source files preserved as parametrized cases.
"""

from __future__ import annotations

import importlib.resources
import re
from pathlib import Path

import pytest

# =============================================================================
# Shared paths (resolved from project_root fixture)
# =============================================================================

# Resolve via importlib.resources so tests work in both editable installs and
# non-editable wheel installs (the schema now ships inside the package, not at
# the repo root). Precedent: test_config_schema.py:16.
CONFIG_SCHEMA_PATH = importlib.resources.files("little_loops").joinpath("config-schema.json")


# -- 149 string-presence assertions -------------------------------

DOC_STRINGS_PRESENT: list[tuple[str, str, str]] = [
    # (doc_path, expected_string, issue_id)
    ("skills/capture-issue/SKILL.md", "**Status enum**:", "ENH-1550"),
    ("skills/format-issue/SKILL.md", "**Status enum**:", "ENH-1550"),
    ("skills/manage-issue/SKILL.md", "**Status enum**:", "ENH-1550"),
    ("commands/ready-issue.md", "**Status enum**:", "ENH-1550"),
    ("commands/refine-issue.md", "**Status enum**:", "ENH-1550"),
    # ENH-2992: refine must surface the human path into /ll:reconcile-issue —
    # the pipeline diagram, the Step 6.7 gate, and the NEXT STEPS block.
    ("commands/refine-issue.md", "/ll:reconcile-issue", "ENH-2992"),
    ("commands/refine-issue.md", "superseded_marker_count", "ENH-2992"),
    ("commands/create-sprint.md", "ll-issues list --json", "BUG-1649"),
    ("skills/create-loop/reference.md", "circuit_breaker_enabled", "circuit-breaker"),
    ("skills/create-loop/reference.md", "circuit_breaker_path", "circuit-breaker"),
    ("skills/create-loop/loop-types.md", "circuit_breaker_enabled", "circuit-breaker"),
    ("skills/create-loop/loop-types.md", "circuit_breaker_path", "circuit-breaker"),
    ("commands/align-issues.md", "--issues", "ENH-1362"),
    ("commands/align-issues.md", "arguments:", "ENH-1362"),
    ("commands/align-issues.md", "name: issues", "ENH-1362"),
    ("commands/align-issues.md", "Bash(ll-issues:*)", "ENH-1362"),
    ("commands/align-issues.md", 'ISSUES_ARG="${issues:-}', "ENH-1362"),
    ("commands/align-issues.md", "ll-issues path", "ENH-1362"),
    ("commands/align-issues.md", "not found (skipping)", "ENH-1362"),
    ("commands/align-issues.md", "None of the specified issue IDs", "ENH-1362"),
    ("commands/tradeoff-review-issues.md", 'argument-hint: "[issue-ids]', "ENH-1363"),
    ("commands/tradeoff-review-issues.md", "arguments:", "ENH-1363"),
    ("commands/tradeoff-review-issues.md", "name: issues", "ENH-1363"),
    ("commands/tradeoff-review-issues.md", "Bash(ll-issues:*)", "ENH-1363"),
    ("commands/tradeoff-review-issues.md", "ll-issues path", "ENH-1363"),
    ("commands/tradeoff-review-issues.md", "not found (skipping)", "ENH-1363"),
    ("commands/scan-product.md", "sole responsible party for deduplication", "ENH-1403"),
    ("skills/product-analyzer/SKILL.md", "## Examples", "ENH-1404"),
    ("commands/manage-release.md", "status: done", "ENH-1421"),
    ("commands/manage-release.md", "completed_at", "ENH-1421"),
    ("skills/manage-issue/SKILL.md", "status: done", "ENH-1421"),
    ("skills/manage-issue/SKILL.md", "status:", "ENH-1421"),
    # REMOVED (self-referential — old doc-wiring file no longer exists after ENH-1963 consolidation):
    # ("scripts/tests/test_feat1172_doc_wiring.py", "status\" in row.lower() or \"frontmatter\" in row.lower()", "ENH-1421"),
    ("skills/issue-size-review/SKILL.md", "parent: [PARENT-ID]", "ENH-1433"),
    # REMOVED (stale/false-positive): ("skills/issue-size-review/SKILL.md", "parent: EPIC-NNN", "ENH-1433"),
    ("skills/confidence-check/SKILL.md", "parent: EPIC-NNN", "ENH-1433"),
    ("skills/manage-issue/SKILL.md", "parent: EPIC-NNN", "ENH-1433"),
    # REMOVED (stale/false-positive): ("skills/manage-issue/SKILL.md", "| `parent`", "ENH-1433"),
    ("skills/product-analyzer/SKILL.md", "goals_content_missing", "ENH-1442"),
    ("commands/scan-product.md", "config.product.goals_discovery.max_files", "ENH-1442"),
    ("commands/scan-product.md", "config.product.goals_discovery.required_files", "ENH-1442"),
    ("mkdocs.yml", "Codex CLI:", "ENH-1495"),
    ("mkdocs.yml", "codex/README.md", "ENH-1495"),
    ("mkdocs.yml", "codex/getting-started.md", "ENH-1495"),
    ("mkdocs.yml", "codex/usage.md", "ENH-1495"),
    ("docs/index.md", "codex/README.md", "ENH-1495"),
    ("docs/index.md", "codex/getting-started.md", "ENH-1495"),
    ("docs/index.md", "codex/usage.md", "ENH-1495"),
    ("docs/index.md", "codex/", "ENH-1495"),
    (
        "docs/reference/loops.md",
        "${context.run_dir}/states/<state>/trajectory.jsonl",
        "ENH-1557",
    ),
    ("docs/reference/loops.md", "STATE_NAME", "ENH-1557"),
    ("docs/reference/loops.md", "EXAMPLES_FILE", "ENH-1557"),
    ("docs/reference/loops.md", "dequeue_state", "ENH-1557"),
    ("docs/reference/loops.md", "check_queue", "ENH-1557"),
    ("skills/create-loop/loop-types.md", "timeout: 1500", "ENH-1639"),
    ("skills/create-loop/loop-types.md", "MCP calls", "ENH-1639"),
    # REMOVED (stale/false-positive): ("skills/create-loop/loop-types.md", "MCP tool calls", "ENH-1639"),
    ("docs/generalized-fsm-loop.md", "MCP tool calls", "ENH-1639"),
    ("docs/generalized-fsm-loop.md", "1500", "ENH-1639"),
    ("docs/generalized-fsm-loop.md", "default_timeout", "ENH-1639"),
    ("docs/generalized-fsm-loop.md", "MCP", "ENH-1639"),
    ("docs/guides/AUTOMATIC_HARNESSING_GUIDE.md", "MCP", "ENH-1639"),
    ("docs/guides/AUTOMATIC_HARNESSING_GUIDE.md", "1500", "ENH-1639"),
    (str(CONFIG_SCHEMA_PATH), "issue.completed", "ENH-1734"),
    (str(CONFIG_SCHEMA_PATH), "AutoManager", "ENH-1734"),
    ("commands/review-sprint.md", "3f: EPIC Context", "ENH-1859"),
    ("commands/review-sprint.md", "ll-sprint show EPIC-", "ENH-1859"),
    ("commands/review-sprint.md", "ll-deps tree", "ENH-1859"),
    ("commands/review-sprint.md", "ll-sprint edit", "ENH-1859"),
    ("commands/review-sprint.md", "5d", "ENH-1859"),
    ("commands/review-sprint.md", "EPIC", "ENH-1859"),
    ("skills/map-dependencies/SKILL.md", "ll-deps tree --epic", "ENH-1866"),
    ("skills/create-loop/SKILL.md", "Orch: Router (dynamic dispatch)", "ENH-1912"),
    ("skills/create-loop/SKILL.md", "route", "ENH-1912"),
    ("skills/create-loop/SKILL.md", "orch-router", "ENH-1912"),
    # REMOVED (stale/false-positive): ("skills/create-loop/SKILL.md", "Route / compose / supervise", "ENH-1912"),
    # REMOVED (stale): ("skills/create-loop/SKILL.md", "For \"Route / compose / supervise other loops", "ENH-1912"),
    ("skills/create-loop/templates.md", "Route / compose / supervise", "ENH-1912"),
    ("skills/create-loop/templates.md", 'For "Route / compose / supervise other loops', "ENH-1912"),
    ("skills/create-loop/templates.md", "loop-router", "ENH-1912"),
    # REMOVED (stale/false-positive): ("skills/create-loop/templates.md", "## Orchestration Loops", "ENH-1912"),
    # REMOVED (stale/false-positive): ("skills/create-loop/templates.md", "Orch Router Questions", "ENH-1912"),
    ("skills/create-loop/loop-types.md", "## Orchestration Loops", "ENH-1912"),
    ("skills/create-loop/loop-types.md", "Orch Router Questions", "ENH-1912"),
    ("skills/create-loop/loop-types.md", "captured.chosen.output", "ENH-1912"),
    ("skills/create-loop/loop-types.md", "EPIC-1811", "ENH-1912"),
    ("skills/create-loop/loop-types.md", "Orchestration", "ENH-1912"),
    (".issues/epics/P2-EPIC-1707-history-db-as-agent-context-layer.md", "ENH-1909", "ENH-1916"),
    (".issues/epics/P2-EPIC-1707-history-db-as-agent-context-layer.md", "ENH-1911", "ENH-1916"),
    (".issues/epics/P2-EPIC-1707-history-db-as-agent-context-layer.md", "ENH-1913", "ENH-1916"),
    (".issues/epics/P2-EPIC-1707-history-db-as-agent-context-layer.md", "ENH-1914", "ENH-1916"),
    (".issues/epics/P2-EPIC-1707-history-db-as-agent-context-layer.md", "ENH-1916", "ENH-1916"),
    # REMOVED (stale/false-positive): (".issues/epics/P2-EPIC-1707-history-db-as-agent-context-layer.md", "| `history` |", "ENH-1916"),
    (".issues/epics/P2-EPIC-1707-history-db-as-agent-context-layer.md", "`history`", "ENH-1916"),
    ("skills/manage-issue/SKILL.md", "completed_at", "FEAT-1172"),
    ("skills/manage-issue/SKILL.md", 'date -u +"%Y-%m-%dT%H:%M:%SZ', "FEAT-1172"),
    ("skills/manage-issue/SKILL.md", "update_frontmatter", "FEAT-1172"),
    ("commands/create-sprint.md", "--for-skill create-sprint", "ENH-1909"),
    ("skills/scope-epic/SKILL.md", "--for-skill scope-epic", "ENH-1909"),
    ("skills/manage-issue/SKILL.md", "--for-skill manage-issue", "ENH-1909"),
    ("skills/review-epic/SKILL.md", "--for-skill review-epic", "ENH-1909"),
    ("skills/explore-api/SKILL.md", "description:", "FEAT-1287"),
    ("skills/explore-api/SKILL.md", "argument-hint:", "FEAT-1287"),
    ("skills/explore-api/SKILL.md", "ll-learning-tests", "FEAT-1287"),
    ("skills/explore-api/SKILL.md", "--assume", "FEAT-1287"),
    # REMOVED (stale/false-positive): ("skills/explore-api/SKILL.md", "63 skills", "FEAT-1287"),
    # REMOVED (stale/false-positive): ("skills/explore-api/SKILL.md", "63 skill definitions", "FEAT-1287"),
    ("skills/capture-issue/SKILL.md", "EPIC", "FEAT-1407"),
    ("skills/capture-issue/SKILL.md", "epics/", "FEAT-1407"),
    ("commands/normalize-issues.md", "EPIC", "FEAT-1407"),
    ("commands/normalize-issues.md", "epics/", "FEAT-1407"),
    ("skills/format-issue/SKILL.md", "EPIC", "FEAT-1407"),
    ("skills/format-issue/SKILL.md", "epics/", "FEAT-1407"),
    ("skills/issue-workflow/SKILL.md", "epics/", "FEAT-1407"),
    ("skills/issue-workflow/SKILL.md", "EPIC", "FEAT-1407"),
    ("scripts/little_loops/cli/create_extension.py", "LLHookIntentExtension", "FEAT-1457"),
    # REMOVED (stale/false-positive): ("scripts/little_loops/cli/create_extension.py", "hooks/adapters/", "FEAT-1457"),
    ("skills/workflow-automation-proposer/SKILL.md", "LLHookIntentExtension", "FEAT-1457"),
    ("skills/workflow-automation-proposer/SKILL.md", "hooks/adapters/", "FEAT-1457"),
    # REMOVED (stale/false-positive): ("skills/workflow-automation-proposer/SKILL.md", "adapters/claude-code/precompact.sh", "FEAT-1457"),
    ("skills/audit-claude-config/SKILL.md", "hooks/adapters/", "FEAT-1457"),
    ("skills/audit-claude-config/SKILL.md", "scripts/little_loops/hooks/", "FEAT-1457"),
    # REMOVED (stale/false-positive): ("skills/audit-claude-config/SKILL.md", "hooks/adapters/claude-code/", "FEAT-1457"),
    ("docs/claude-code/write-a-hook.md", "LLHookEvent", "FEAT-1457"),
    ("docs/claude-code/write-a-hook.md", "LLHookResult", "FEAT-1457"),
    ("docs/claude-code/write-a-hook.md", "LLHookIntentExtension", "FEAT-1457"),
    ("docs/claude-code/write-a-hook.md", "provided_hook_intents", "FEAT-1457"),
    ("docs/claude-code/write-a-hook.md", "ll-create-extension", "FEAT-1457"),
    ("docs/claude-code/write-a-hook.md", "flowchart LR", "FEAT-1457"),
    # REMOVED (stale/false-positive): ("docs/claude-code/write-a-hook.md", "write-a-hook.md", "FEAT-1457"),
    ("docs/claude-code/automate-workflows-with-hooks.md", "flowchart LR", "FEAT-1457"),
    ("docs/claude-code/automate-workflows-with-hooks.md", "write-a-hook.md", "FEAT-1457"),
    # REMOVED (stale/false-positive): ("docs/claude-code/automate-workflows-with-hooks.md", "Claude Code:", "FEAT-1457"),
    # REMOVED (stale/false-positive): ("docs/claude-code/automate-workflows-with-hooks.md", "claude-code/write-a-hook.md", "FEAT-1457"),
    ("mkdocs.yml", "Claude Code:", "FEAT-1457"),
    ("mkdocs.yml", "claude-code/write-a-hook.md", "FEAT-1457"),
    ("mkdocs.yml", "claude-code/hooks-reference.md", "FEAT-1457"),
    ("mkdocs.yml", "claude-code/automate-workflows-with-hooks.md", "FEAT-1457"),
    ("docs/index.md", "claude-code/write-a-hook.md", "FEAT-1457"),
    ("docs/claude-code/hooks-reference.md", "Intent model", "FEAT-1459"),
    ("docs/claude-code/hooks-reference.md", "write-a-hook.md", "FEAT-1459"),
    ("docs/claude-code/hooks-reference.md", "EVENT-SCHEMA.md", "FEAT-1459"),
    ("docs/claude-code/hooks-reference.md", "LLHookEvent", "FEAT-1459"),
    ("docs/claude-code/hooks-reference.md", "LLHookResult", "FEAT-1459"),
    ("docs/claude-code/write-a-hook.md", "EVENT-SCHEMA.md", "FEAT-1459"),
    ("thoughts/research/codex-command-discovery.md", "~/.codex/skills", "FEAT-1483"),
    ("thoughts/research/codex-command-discovery.md", "stable", "FEAT-1483"),
    ("thoughts/research/codex-command-discovery.md", "codex/skills", "FEAT-1483"),
    ("hooks/adapters/codex/README.md", "codex/skills", "FEAT-1483"),
    ("hooks/adapters/codex/README.md", "FEAT-1483", "FEAT-1483"),
    ("agents/loop-specialist.md", "name: loop-specialist", "FEAT-1532"),
    ("agents/loop-specialist.md", "model:", "FEAT-1532"),
    ("agents/loop-specialist.md", "tools:", "FEAT-1532"),
    ("agents/loop-specialist.md", ".loops/diagnostics/", "FEAT-1532"),
    ("agents/loop-specialist.md", "ll-loop history", "FEAT-1532"),
    ("skills/create-loop/loop-types.md", "assumption_gate", "ENH-2215"),
    ("skills/create-loop/loop-types.md", "assumption-firewall", "ENH-2215"),
    ("skills/create-loop/SKILL.md", "Policy router (decision table)", "ENH-2299"),
    ("skills/create-loop/loop-types.md", "## Policy Router Questions", "ENH-2299"),
    ("skills/create-loop/templates.md", "policy-router", "ENH-2299"),
    ("docs/reference/COMMANDS.md", "policy-router", "ENH-2299"),
    # BUG-2408: manage-issue Phase 4 "Verify" must require a foreground-blocking final
    # test run and forbid the background-then-await-wakeup idiom. Headless `claude -p`
    # turns have no interactive wakeup/notification, so backgrounding the result-blocking
    # final suite strands the work uncommitted before Phase 5. A whole-file DOC_STRINGS_ABSENT
    # check is unsuitable here because the forbidding prose itself names the bad idioms
    # ("scheduled wakeup" / "completion notification"); assert the guidance is PRESENT instead.
    ("skills/manage-issue/SKILL.md", "foreground-blocking", "BUG-2408"),
    ("skills/manage-issue/SKILL.md", "scheduled wakeup", "BUG-2408"),
    # BUG-2423: each hardened decisions-guardrail `list` read now gates on the
    # decisions-log file so the sole clean-empty case (absent file) is handled up
    # front; a real query failure is no longer laundered into a clean "no rules" pass.
    ("skills/format-issue/SKILL.md", "[ -f .ll/decisions.yaml ]", "BUG-2423"),
    ("commands/ready-issue.md", "[ -f .ll/decisions.yaml ]", "BUG-2423"),
    ("commands/verify-issues.md", "[ -f .ll/decisions.yaml ]", "BUG-2423"),
    ("skills/improve-claude-md/SKILL.md", "[ -f .ll/decisions.yaml ]", "BUG-2423"),
    # /ll:spike skill registration (FEAT-2567)
    # REMOVED (FEAT-2940: commands/help.md is now generated by ll-help, no static catalog to assert on): ("commands/help.md", "spike", "FEAT-2567"),
    (".claude/CLAUDE.md", "spike", "FEAT-2567"),
    # ENH-2996: Wiring Phase entries are unnumbered bullets, matching the
    # sibling Phase-8a subsections' convention.
    ("skills/wire-issue/SKILL.md", "- Update `path/to/caller.py`", "ENH-2996"),
    # ENH-3049: wire-issue gains the ENH-2995 contradiction-marking carve-out —
    # same marker prefix and three-section scope, wire's own provenance rule.
    ("skills/wire-issue/SKILL.md", "⚠ Superseded", "ENH-3049"),
    ("skills/wire-issue/SKILL.md", "Implementation Steps", "ENH-3049"),
    ("skills/wire-issue/SKILL.md", "Files to Modify", "ENH-3049"),
    ("skills/wire-issue/SKILL.md", "Acceptance Criteria", "ENH-3049"),
    ("skills/wire-issue/SKILL.md", "this pass is appending", "ENH-3049"),
    ("skills/wire-issue/SKILL.md", "never delete", "ENH-3049"),
    # ENH-3049: refine's refutation test gains a contradiction-driven branch
    # alongside the existing finding-driven one.
    ("commands/refine-issue.md", "Contradiction-driven", "ENH-3049"),
    # ENH-3049: reconcile-issue becomes a routine post-wire step in the guide.
    ("docs/guides/ISSUE_MANAGEMENT_GUIDE.md", "/ll:reconcile-issue", "ENH-3049"),
    # ENH-3049: COMMANDS.md's wire-issue entry names the annotation behavior.
    ("docs/reference/COMMANDS.md", "may additionally **annotate**", "ENH-3049"),
    # ENH-3045: both wire and refine emit the same bare `### Behavior Parity`
    # heading doctrine; this is the only test surface for the capability-search
    # and claim-grounding doctrine, which is pure prose with no Python path.
    ("skills/wire-issue/SKILL.md", "### Behavior Parity", "ENH-3045"),
    ("skills/wire-issue/behavior-parity.md", "### Behavior Parity", "ENH-3045"),
    ("commands/refine-issue.md", "### Behavior Parity", "ENH-3045"),
    ("commands/refine-issue.md", "Capability-search and claim-grounding", "ENH-3045"),
    # ENH-3050: refine's Program Design gains a Decision Rules slot, and wire
    # gains gate-consumer and conditional-branch MISSING_WIRING categories.
    ("commands/refine-issue.md", "### Decision Rules", "ENH-3050"),
    ("skills/wire-issue/SKILL.md", "gate_consumers", "ENH-3050"),
    ("skills/wire-issue/SKILL.md", "conditional_branches", "ENH-3050"),
    ("docs/reference/COMMANDS.md", "gate_consumers", "ENH-3050"),
    # ENH-3126: verify-issues gains graph-assisted anchor drift and
    # negative-claim checks, gated behind Bash(ll-code:*).
    ("commands/verify-issues.md", "Bash(ll-code:*)", "ENH-3126"),
    # ENH-3238: verify-issues gains a causal/identity-claim rule so a
    # consequence merely consistent with a stated cause is not accepted as
    # sufficient to confirm it.
    ("commands/verify-issues.md", "Causal / identity claims", "ENH-3238"),
    # BUG-3260: codebase-locator (Layer A) must require a per-path evidence
    # citation, and wire-issue's evidence-confirmation.md (Layer B) must grep
    # that citation before a path enters MISSING_WIRING or the Integration Map.
    ("agents/codebase-locator.md", "cite the symbol or pattern your Grep matched", "BUG-3260"),
    (
        "skills/wire-issue/evidence-confirmation.md",
        "one targeted Grep for the match string",
        "BUG-3260",
    ),
]


# BUG-2650: the LL_VERIFY_GATE skipif quarantine (added by BUG-2649) is removed.
# Root-cause: the gate's checkout -> xdist-subprocess -> project_root read is
# deterministic (git worktree add is synchronous; the read resolves off the
# path-collected conftest, not cwd/PYTHONPATH). A 60x stress probe of that exact
# path produced 0 false-negatives; the lone historical failure was a stale
# EPIC-integration tip, not a nondeterministic read. Guarded by
# test_worktree_utils.py::TestVerifyEpicBranchBeforeMerge
# ::test_gate_read_is_deterministic_on_present_needle.
@pytest.mark.parametrize("doc_rel, needle, issue_id", DOC_STRINGS_PRESENT)
def test_string_present_in_doc(
    project_root: Path, doc_rel: str, needle: str, issue_id: str
) -> None:
    """Verify that expected strings appear in documentation files."""
    content = (project_root / doc_rel).read_text()
    assert needle in content, f"[{issue_id}] {doc_rel} must contain: {needle!r}"


# -- 17 string-absence assertions --------------------------------

DOC_STRINGS_ABSENT: list[tuple[str, str, str]] = [
    # (doc_path, forbidden_string, issue_id)
    ("agents/codebase-analyzer.md", "file:line", "ENH-1299"),
    ("agents/codebase-pattern-finder.md", "file:line", "ENH-1299"),
    ("skills/wire-issue/SKILL.md", "file:line", "ENH-1299"),
    ("skills/manage-issue/templates.md", "file:line", "ENH-1299"),
    ("commands/refine-issue.md", "file:line", "ENH-1299"),
    ("skills/product-analyzer/SKILL.md", "Remove findings marked as duplicates", "ENH-1403"),
    ("commands/scan-product.md", "Remove findings marked as duplicates", "ENH-1403"),
    ("skills/issue-size-review/SKILL.md", "parent_issue:", "ENH-1433"),
    ("skills/issue-size-review/SKILL.md", "parent_issue: EPIC-NNN", "ENH-1433"),
    ("skills/confidence-check/SKILL.md", "parent_issue: EPIC-NNN", "ENH-1433"),
    ("skills/manage-issue/SKILL.md", "parent_issue: EPIC-NNN", "ENH-1433"),
    ("skills/manage-issue/SKILL.md", "| `parent_issue`", "ENH-1433"),
    ("skills/product-analyzer/SKILL.md", "goals_file_missing", "ENH-1442"),
    ("skills/product-analyzer/SKILL.md", "Goals file not found", "ENH-1442"),
    ("commands/scan-product.md", "Goals file not found", "ENH-1442"),
    ("docs/reference/loops.md", ".loops/tmp/harness-optimize-trajectory.jsonl", "ENH-1557"),
    ("skills/explore-api/SKILL.md", "29 skills", "FEAT-1287"),
    ("agents/consistency-checker.md", "| hooks/prompts/optimize-prompt-hook.md |", "ENH-2291"),
    (
        ".codex/agents/consistency-checker.toml",
        "| hooks/prompts/optimize-prompt-hook.md |",
        "ENH-2291",
    ),
    # BUG-2423: decisions-guardrail `list` reads must not swallow CLI errors via
    # `2>/dev/null || true` (collapses argparse exit 2 into a clean "no rules" pass).
    # Needles are scoped to each specific guardrail invocation so unrelated future
    # `2>/dev/null || true` usage elsewhere is not caught.
    ("skills/format-issue/SKILL.md", "--active-only 2>/dev/null || true", "BUG-2423"),
    ("skills/format-issue/SKILL.md", "--type exception 2>/dev/null || true", "BUG-2423"),
    ("commands/ready-issue.md", "--active-only --format json 2>/dev/null || true", "BUG-2423"),
    ("commands/ready-issue.md", "--type exception 2>/dev/null || true", "BUG-2423"),
    ("commands/verify-issues.md", "--active-only 2>/dev/null || true", "BUG-2423"),
    (
        "skills/improve-claude-md/SKILL.md",
        "decisions list --type rule 2>/dev/null | grep",
        "BUG-2423",
    ),
    # ENH-2996: Wiring Phase entries must not continue the parent
    # Implementation Steps list's numbering.
    ("skills/wire-issue/SKILL.md", "N+1. Update", "ENH-2996"),
    # ENH-3049: wire may only insert markers, never delete one — refine's
    # "Bounded marker-removal right" (ENH-2995) does not port to wire.
    ("skills/wire-issue/SKILL.md", "Bounded marker-removal right", "ENH-3049"),
]


@pytest.mark.parametrize("doc_rel, needle, issue_id", DOC_STRINGS_ABSENT)
def test_string_absent_from_doc(
    project_root: Path, doc_rel: str, needle: str, issue_id: str
) -> None:
    """Verify that stale/forbidden strings do NOT appear in documentation files."""
    content = (project_root / doc_rel).read_text()
    assert needle not in content, f"[{issue_id}] {doc_rel} must NOT contain: {needle!r}"


# -- 19 file-existence assertions -----------------------------------

DOC_FILES_MUST_EXIST: list[tuple[str, str]] = [
    # (file_path, issue_id)
    ("commands/align-issues.md", "ENH-1362"),
    ("commands/tradeoff-review-issues.md", "ENH-1363"),
    ("skills/product-analyzer/SKILL.md", "ENH-1402"),
    ("commands/manage-release.md", "ENH-1421"),
    ("skills/manage-issue/SKILL.md", "ENH-1421"),
    # REMOVED (self-referential — old doc-wiring file no longer exists after ENH-1963 consolidation):
    # ("scripts/tests/test_feat1172_doc_wiring.py", "ENH-1421"),
    ("commands/review-sprint.md", "ENH-1859"),
    ("skills/ll-go-no-go/SKILL.md", "ENH-1888"),
    ("skills/ll-capture-issue/SKILL.md", "ENH-1888"),
    ("skills/explore-api/SKILL.md", "FEAT-1287"),
    ("skills/verify-issue-loop/SKILL.md", "FEAT-1447"),
    ("docs/claude-code/write-a-hook.md", "FEAT-1457"),
    ("thoughts/research/codex-command-discovery.md", "FEAT-1483"),
    ("agents/loop-specialist.md", "FEAT-1532"),
    (".codex/agents/loop-specialist.toml", "FEAT-1532"),
    ("skills/review-epic/SKILL.md", "FEAT-1856"),
    ("skills/review-epic/agents/openai.yaml", "FEAT-1856"),
    ("skills/scope-epic/SKILL.md", "FEAT-1857"),
    ("skills/scope-epic/agents/openai.yaml", "FEAT-1857"),
]


@pytest.mark.parametrize("doc_rel, issue_id", DOC_FILES_MUST_EXIST)
def test_file_exists(project_root: Path, doc_rel: str, issue_id: str) -> None:
    """Verify that expected documentation files exist."""
    assert (project_root / doc_rel).exists(), "[{issue_id}] File must exist: {doc_rel}"


# ENH-3062: replaces the ENH-2996 hardcoded (source, mirror) pair list above
# (removed) with a gate parametrized over the adapter's own registry, so a
# newly added command or skill is covered the moment it is adapted — no
# test-side list to keep in sync. Scoped per the issue's Host / Artifact
# Coverage Matrix: a uniform "0 adapted" assertion is wrong for 3 of 6
# `_EMITTER_MAP` hosts (see the two exclusion tests below).
GATED_HOSTS = ["gemini", "kimi-code", "qwen", "codex", "omp"]
"""Hosts whose skill/command/agent mirrors this gate holds to `0 adapted`.

Excludes `claude-code` (see `test_claude_code_excluded_from_mirror_gate`) and
never touches `process_mcp_config` for any host (see
`test_mcp_config_excluded_from_mirror_gate`). `omp` is gated but its mirror
root isn't git-tracked in this repo, so the check below is presence-guarded
rather than run unconditionally (matches `test_skill_mirrors_carry_companions`).
"""


def _host_output_dirs(project_root: Path, host: str) -> tuple[Path, Path, Path, Path]:
    """Mirror `main_adapt()`'s own path derivation (`cli/adapt.py`)."""
    from little_loops.adapters.capabilities import HOST_CAPABILITIES

    skills_dir = project_root / "skills"
    commands_dir = project_root / "commands"
    agents_dir = project_root / "agents"
    capability_entry = HOST_CAPABILITIES.get(host)
    config_dir = (capability_entry.config_dir if capability_entry else None) or ".codex"
    agent_output_dir = project_root / config_dir / "agents"
    return skills_dir, commands_dir, agents_dir, agent_output_dir


@pytest.mark.parametrize("host", GATED_HOSTS)
@pytest.mark.parametrize("kind", ["skills", "commands", "agents"])
def test_host_artifacts_are_not_stale(project_root: Path, host: str, kind: str) -> None:
    """`ll-adapt --host <host> --dry-run` must report 0 adapted (ENH-3062).

    Content-compares the adapter's own generated output against the on-disk
    mirror for every artifact kind, replacing the ENH-2996 hardcoded pair
    list — coverage now tracks `_EMITTER_MAP` directly.
    """
    from little_loops.adapters.core import (
        process_agents,
        process_commands,
        process_skills,
        resolve_emitter,
    )

    if host == "omp" and not (project_root / ".omp").exists():
        return  # no tracked mirror for this host in this repo

    emitter = resolve_emitter(host)
    skills_dir, commands_dir, agents_dir, agent_output_dir = _host_output_dirs(project_root, host)

    if kind == "skills":
        adapted, _skipped, _errors = process_skills(emitter, skills_dir, apply=False, quiet=True)
    elif kind == "commands":
        adapted, _skipped, _errors = process_commands(
            emitter, commands_dir, skills_dir, apply=False, quiet=True
        )
    else:
        adapted, _skipped, _errors = process_agents(
            emitter, agents_dir, agent_output_dir, apply=False, quiet=True
        )

    assert adapted == 0, (
        f"{host}'s {kind} mirror is stale ({adapted} artifact(s) would be "
        f"rewritten). Regenerate with: ll-adapt --host {host} --apply"
    )


def test_gate_detects_present_but_drifted_codex_command_bridge(tmp_path: Path) -> None:
    """Gate catches drift, not just missing artifacts (ENH-3062 AC6).

    Reproduces the false-negative class that motivated this issue: a codex
    command bridge (`skills/ll-<stem>/`) that exists on disk with content
    that no longer matches its generator, via the same `process_commands`
    call `test_host_artifacts_are_not_stale` uses — not just the underlying
    emitter unit.
    """
    from little_loops.adapters.core import process_commands, resolve_emitter

    commands_dir = tmp_path / "commands"
    commands_dir.mkdir()
    skills_dir = tmp_path / "skills"
    skills_dir.mkdir()
    (commands_dir / "my-cmd.md").write_text(
        "---\ndescription: Original description.\n---\n\n# My Cmd\n"
    )
    emitter = resolve_emitter("codex")
    adapted, _skipped, _errors = process_commands(
        emitter, commands_dir, skills_dir, apply=True, quiet=True
    )
    assert adapted == 1  # baseline bridge created

    # Source changes; bridge is present but stale (not regenerated).
    (commands_dir / "my-cmd.md").write_text(
        "---\ndescription: Updated description.\n---\n\n# My Cmd\n"
    )

    adapted, _skipped, _errors = process_commands(
        emitter, commands_dir, skills_dir, apply=False, quiet=True
    )
    assert adapted == 1, "gate failed to detect a present-but-drifted codex command bridge"


def test_claude_code_excluded_from_mirror_gate() -> None:
    """`claude-code`'s skill/command/agent emitters are no-op stubs (ENH-3062 AC3).

    `capabilities.py:163-180` sets `skill_output_format=None` etc. for this
    host — `emit_skill`/`emit_command`/`emit_agent` always return `"skipped"`
    with nothing to compare, so parametrizing it into `GATED_HOSTS` would be a
    vacuous pass, not real coverage. Only `emit_mcp_config` does anything for
    `claude-code`, and that path is excluded for a separate reason — see
    `test_mcp_config_excluded_from_mirror_gate`.
    """
    from little_loops.adapters.claude_code import ClaudeCodeEmitter

    assert ClaudeCodeEmitter().emit_skill.__doc__ is not None


def test_mcp_config_excluded_from_mirror_gate() -> None:
    """`process_mcp_config` is never called by this gate, for any host (ENH-3062 AC3).

    None of the three `emit_mcp_config` destinations is a tracked mirror this
    gate could meaningfully hold to "0 adapted": `claude-code` targets
    repo-root `.mcp.json` (`{"mcpServers": {}}` in this source repo — reports
    `adapted` forever, correctly); `codex` reads/writes the operator's real
    `$CODEX_HOME/config.toml` and would report `adapted` against an isolated
    empty home on first run; and no other host's mcp path is git-tracked
    either. Excluding it here also means the `CODEX_HOME` isolation this gate
    would otherwise need (`TestCodexEmitterEmitMcpConfig._config_path`,
    `test_adapters.py`) is moot — nothing in this file touches
    `process_mcp_config`.
    """
    import inspect

    from little_loops.adapters.core import process_mcp_config

    assert "output_dir" in inspect.signature(process_mcp_config).parameters


# BUG-3163: skill mirrors are only usable if ENH-494 companion files ride
# along with SKILL.md — adapted bodies reference companions by relative path,
# and end-user projects have no skills/ source tree to recover from. Guard
# every mirrored skill (not a pinned list) so new skills are covered on day
# one. Reuses the emitter's own companion rule so test and emitter cannot
# drift apart. BUG-3164 extends the guard to every SKILL.md-mirroring host:
# - .kimi-code/skills/ also holds command-bridged ll-* skills with no skills/
#   source directory — skip those rather than flagging them as offenders.
# - .omp/skills/ is not tracked in this repo, so the exists() guard makes its
#   case vacuous here; omp's real coverage is the emitter unit tests in
#   test_adapters.py (TestMirrorEmitterSkillCompanions).
SKILL_MIRROR_ROOTS = [".qwen", ".kimi-code", ".gemini", ".omp"]


@pytest.mark.parametrize("mirror_root_name", SKILL_MIRROR_ROOTS)
def test_skill_mirrors_carry_companions(project_root: Path, mirror_root_name: str) -> None:
    """<host>/skills/<name>/ must carry source companions, byte-identical."""
    from little_loops.adapters.core import _iter_skill_companions

    mirror_root = project_root / mirror_root_name / "skills"
    if not mirror_root.exists():
        return  # no tracked mirror for this host in this repo (e.g. .omp)
    source_root = project_root / "skills"
    offenders: list[str] = []
    for mirror_skill_md in sorted(mirror_root.glob("*/SKILL.md")):
        name = mirror_skill_md.parent.name
        source_dir = source_root / name
        if not (source_dir / "SKILL.md").is_file():
            continue  # command-bridged skill with no skills/ source (kimi ll-*)
        wanted = set(_iter_skill_companions(source_dir))
        present = set(_iter_skill_companions(mirror_skill_md.parent))
        for rel in sorted(wanted - present):
            offenders.append(f"{name}: missing companion {rel}")
        for rel in sorted(present - wanted):
            offenders.append(f"{name}: stale companion {rel}")
        for rel in sorted(wanted & present):
            if (mirror_skill_md.parent / rel).read_bytes() != (source_dir / rel).read_bytes():
                offenders.append(f"{name}: drifted companion {rel}")
    assert not offenders, (
        f"Companion drift in {mirror_root_name}/skills mirrors: "
        + "; ".join(offenders)
        + f". Regenerate with: ll-adapt --host {mirror_root_name.lstrip('.')} --apply"
    )


# FEAT-3077 AC7 / BUG-3209: pin the `run_in_background: true` carve-out inventory
# so a future skill/command author can't silently add a new background-launch
# site without updating the recorded decision. BUG-3209 Key Decision 2 (Option A)
# removed the last carve-out (go-no-go/SKILL.md:174) and widened the scanned
# corpus from skills/ only to skills/**/*.md + commands/*.md, so the allowlist
# is renamed off its skills-only prefix and is empty until a new carve-out is
# deliberately recorded (FEAT-3077-style rationale required).
RUN_IN_BACKGROUND_TRUE_ALLOWLIST: set[str] = set()

# BUG-3209: a "spawn site" is a markdown paragraph containing both a spawn
# marker and an imperative spawn verb. Markers are deliberately broad — the
# corpus mixes "Task tool"/"Agent tool" phrasing with looser forms ("Task
# call", "sub-agent") — because under-matching here silently exempts a real
# spawn site from the run_in_background check.
_SPAWN_MARKERS: tuple[str, ...] = (
    "Agent tool",
    "Task tool",
    "`Agent`",
    "Task call",
    "Task calls",
    "Task agent",
    "subagent_type",
    "subagent",
    "sub-agent",
    "sub-agents",
)
_SPAWN_VERB_RE = re.compile(r"\b(Launch|Spawn|Dispatch|Invoke|Run)\b", re.IGNORECASE)
_AGENT_WORD_RE = re.compile(r"\bagents?\b", re.IGNORECASE)

# (path-relative-to-project-root, line-substring) pairs that match the
# candidate criteria but are descriptive/flag-documentation prose, not an
# actual spawn instruction. Each entry is a known false positive, not a
# catch-all — a new one must be justified the same way these were.
SPAWN_DETECTOR_EXEMPT: frozenset[tuple[str, str]] = frozenset(
    {
        # Checklist prose naming the Task tool as an "established mechanism",
        # not a spawn — confidence-check has no Agent/Task spawn site at all.
        (
            "skills/confidence-check/SKILL.md",
            "Integration points use established mechanisms",
        ),
        # Flag/usage documentation, not the operative spawn instruction
        # (which is qualified at scan-codebase.md:95/97/101).
        (
            "commands/scan-codebase.md",
            "Spawn a single combined scan agent instead of 3 parallel agents",
        ),
        # Frontmatter `description:` string and usage-block flag docs, not
        # the operative spawn instruction (qualified at audit-architecture.md:68).
        (
            "commands/audit-architecture.md",
            'description: "Optional flags: --deep (spawn sub-agents',
        ),
        (
            "commands/audit-architecture.md",
            "use the Task tool to launch analysis agents in parallel",
        ),
        (
            "commands/audit-architecture.md",
            "`--deep` - Spawn sub-agents for thorough analysis",
        ),
        # Recovery instruction to the *user* ("Manually run: ..."), not a tool call.
        (
            "commands/analyze-workflows.md",
            "Manually run: spawn workflow-pattern-analyzer agent",
        ),
        # Consequence-of-proceeding warning inside a size guard, not an instruction
        # to spawn — the operative instruction is the qualified spawn at :123.
        (
            "skills/audit-docs/SKILL.md",
            "will spawn many subagent batches",
        ),
        # Phase-intro topic sentence restating what the phase does; the operative,
        # qualified spawn instruction follows a few lines later under "Research Tasks".
        (
            "skills/manage-issue/SKILL.md",
            "Before creating an implementation plan, spawn parallel sub-agents",
        ),
        # Section-intro topic sentence; the operative, qualified spawn instruction is
        # the triage-gated one under "3.0 Triage the research axes first" below it.
        (
            "commands/refine-issue.md",
            "Spawn parallel sub-agents to gather comprehensive context about the issue's subject matter",
        ),
        # Flag/usage documentation bullet, not the operative spawn instruction
        # (which is qualified at ready-issue.md:89-95, "Spawn Validation Agents").
        (
            "commands/ready-issue.md",
            "Use sub-agents for comprehensive validation (verifies file paths",
        ),
    }
)

# Pinned inventory of known spawn sites (BUG-3209 Summary table), as
# (path-relative-to-project-root, line). The detector's candidate set must
# remain a superset of this inventory — this is what catches a detector that
# stops flagging a known site as opposed to one that flags it but finds it
# satisfied (see test_spawn_detector_candidate_set_is_superset_of_known_inventory).
SPAWN_SITE_INVENTORY: frozenset[tuple[str, int]] = frozenset(
    {
        ("skills/audit-docs/SKILL.md", 122),
        ("skills/audit-claude-config/SKILL.md", 118),
        ("skills/audit-claude-config/SKILL.md", 223),
        ("skills/audit-claude-config/wave1-prompts.md", 9),
        ("skills/audit-issue-conflicts/SKILL.md", 205),
        ("skills/audit-issue-conflicts/SKILL.md", 252),
        ("skills/wire-issue/SKILL.md", 148),
        ("skills/manage-issue/SKILL.md", 110),
        ("skills/go-no-go/SKILL.md", 174),
        ("skills/go-no-go/SKILL.md", 274),
        ("commands/refine-issue.md", 186),
        ("commands/tradeoff-review-issues.md", 79),
        ("commands/manage-release.md", 134),
        # scan-codebase.md:95 ("Spawn a single combined agent that scans...") carries
        # no marker token even after widening — pinning it here would force a bare
        # "agent" marker that overmatches broadly across the corpus, which the
        # detector's conservative-by-design contract (Tests, BUG-3209) forbids. The
        # site itself already declares run_in_background: false in the file; only
        # its *detection* as a candidate is the accepted residual gap.
        ("commands/scan-codebase.md", 97),
        ("commands/scan-codebase.md", 101),
        ("commands/audit-architecture.md", 68),
        ("commands/analyze-workflows.md", 102),
    }
)


def _spawn_paragraphs(text: str) -> list[tuple[int, int]]:
    """Blank-line-delimited paragraphs as 1-indexed (start_line, end_line) ranges."""
    lines = text.splitlines()
    paragraphs: list[tuple[int, int]] = []
    start: int | None = None
    for i, line in enumerate(lines, start=1):
        if line.strip():
            if start is None:
                start = i
        elif start is not None:
            paragraphs.append((start, i - 1))
            start = None
    if start is not None:
        paragraphs.append((start, len(lines)))
    return paragraphs


def _find_spawn_candidates(path: Path, project_root: Path) -> list[tuple[int, int]]:
    """Candidate (start_line, end_line) paragraphs: spawn marker + imperative verb, unexempted."""
    text = path.read_text()
    rel = str(path.relative_to(project_root))
    lines = text.splitlines()
    candidates: list[tuple[int, int]] = []
    for start, end in _spawn_paragraphs(text):
        para_text = "\n".join(lines[start - 1 : end])
        # Normalize backticks before marker matching: "`Task` tool" / "`Agent` tool"
        # must match the same as unquoted "Task tool" / "Agent tool" — the corpus
        # mixes both stylings for the identical instruction.
        para_text_no_ticks = para_text.replace("`", "")
        if not any(marker in para_text_no_ticks for marker in _SPAWN_MARKERS):
            continue
        verb_match = _SPAWN_VERB_RE.search(para_text)
        if not verb_match:
            continue
        if verb_match.group(1).lower() == "run" and not _AGENT_WORD_RE.search(para_text):
            continue
        if any(
            rel == exempt_path and exempt_sub in para_text
            for exempt_path, exempt_sub in SPAWN_DETECTOR_EXEMPT
        ):
            continue
        candidates.append((start, end))
    return candidates


def _spawn_corpus(project_root: Path) -> list[Path]:
    files = sorted((project_root / "skills").rglob("*.md"))
    files += sorted((project_root / "commands").glob("*.md"))
    return files


def _run_in_background_satisfied(path: Path, start: int, end: int) -> bool:
    """Explicit run_in_background: true|false within +/-3 lines or the paragraph, line-oriented.

    Line-oriented (not paragraph-normalized) is deliberate: manage-issue/SKILL.md:389
    reads a *prohibition* — "no `run_in_background:\\n  true`" — split across a line
    wrap. Scanning per-line rather than joining wrapped text keeps that negated,
    line-split mention from being read as a satisfying value.
    """
    lines = path.read_text().splitlines()
    lo = max(1, start - 3)
    hi = min(len(lines), end + 3)
    for i in range(lo, hi + 1):
        line = lines[i - 1]
        if "run_in_background: true" in line or "run_in_background: false" in line:
            return True
    return False


def test_skill_run_in_background_true_inventory_pinned(project_root: Path) -> None:
    """`run_in_background: true` across skills/**/*.md + commands/*.md must match the
    recorded carve-out allowlist (BUG-3209 Key Decision 2, Option A: empty)."""
    offenders = {
        str(path.relative_to(project_root))
        for path in _spawn_corpus(project_root)
        if "run_in_background: true" in path.read_text()
    }
    assert offenders == RUN_IN_BACKGROUND_TRUE_ALLOWLIST, (
        "run_in_background: true inventory drifted from the recorded carve-out "
        f"decision. Found: {sorted(offenders)}, expected: "
        f"{sorted(RUN_IN_BACKGROUND_TRUE_ALLOWLIST)}. If this is a deliberate new "
        "carve-out, update the allowlist and record the decision per FEAT-3077's "
        "### Decision Rationale precedent."
    )


def test_run_in_background_directive_present_at_every_spawn_site(project_root: Path) -> None:
    """BUG-3209: every Agent/Task spawn site across skills/**/*.md + commands/*.md
    declares an explicit run_in_background value — nothing relies on the tool's
    background-by-default behavior, which is what let headless turns end with
    subagent results still in flight."""
    missing = []
    for path in _spawn_corpus(project_root):
        for start, end in _find_spawn_candidates(path, project_root):
            if not _run_in_background_satisfied(path, start, end):
                rel = path.relative_to(project_root)
                missing.append(f"{rel}:{start}-{end}")
    assert not missing, (
        "Agent/Task spawn site(s) with no explicit run_in_background directive "
        f"(BUG-3209): {missing}"
    )


def test_spawn_detector_candidate_set_is_superset_of_known_inventory(project_root: Path) -> None:
    """The detector must still *detect* every known spawn site as a candidate, not
    merely find it satisfied — this is the check that would have caught the five
    marker/verb misses found while scoping BUG-3209."""
    detected: set[tuple[str, int]] = set()
    for path in _spawn_corpus(project_root):
        rel = str(path.relative_to(project_root))
        for start, end in _find_spawn_candidates(path, project_root):
            detected.update((rel, line) for line in range(start, end + 1))
    missing = {site for site in SPAWN_SITE_INVENTORY if site not in detected}
    assert not missing, (
        f"Detector no longer flags known spawn site(s) as candidates: {sorted(missing)}"
    )


def test_spawn_detector_does_not_flag_confidence_check(project_root: Path) -> None:
    """confidence-check/SKILL.md has no Agent/Task spawn site; its Task-tool mention is
    descriptive checklist prose and must stay exempted, not become a false positive."""
    path = project_root / "skills" / "confidence-check" / "SKILL.md"
    assert _find_spawn_candidates(path, project_root) == []
