"""Consolidated doc-wiring tests — Reference documentation wiring (API, COMMANDS, CONFIGURATION, etc.).

Generated by ENH-1963: Audit and Consolidate Doc-Wiring Tests.
All original assertions from 28 source files preserved as parametrized cases.
"""

from __future__ import annotations

from pathlib import Path

import pytest

# =============================================================================
# Shared paths (resolved from project_root fixture)
# =============================================================================


# -- 147 string-presence assertions -------------------------------

DOC_STRINGS_PRESENT: list[tuple[str, str, str]] = [
    # (doc_path, expected_string, issue_id)
    ("docs/reference/API.md", "update_frontmatter", "FEAT-1172"),
    ("docs/reference/ISSUE_TEMPLATE.md", "`completed_at`", "FEAT-1172"),
    ("docs/reference/ISSUE_TEMPLATE.md", "status", "FEAT-1172"),
    ("docs/reference/API.md", "`little_loops.hooks`", "FEAT-1459"),
    ("docs/reference/API.md", "### LLHookEvent", "FEAT-1459"),
    ("docs/reference/API.md", "### LLHookResult", "FEAT-1459"),
    ("docs/reference/API.md", "### LLHookIntentExtension", "FEAT-1459"),
    ("docs/reference/API.md", "provided_hook_intents", "FEAT-1459"),
    ("docs/reference/EVENT-SCHEMA.md", "LLHookEvent", "FEAT-1459"),
    ("docs/reference/EVENT-SCHEMA.md", "`host`", "FEAT-1459"),
    ("docs/reference/EVENT-SCHEMA.md", "`intent`", "FEAT-1459"),
    ("docs/reference/EVENT-SCHEMA.md", "`payload`", "FEAT-1459"),
    ("docs/reference/EVENT-SCHEMA.md", "`session_id`", "FEAT-1459"),
    ("docs/reference/EVENT-SCHEMA.md", "`cwd`", "FEAT-1459"),
    ("docs/reference/EVENT-SCHEMA.md", "LLHookResult", "FEAT-1459"),
    ("docs/reference/EVENT-SCHEMA.md", "`exit_code`", "FEAT-1459"),
    ("docs/reference/EVENT-SCHEMA.md", "`feedback`", "FEAT-1459"),
    ("docs/reference/EVENT-SCHEMA.md", "`decision`", "FEAT-1459"),
    ("docs/reference/EVENT-SCHEMA.md", "`data`", "FEAT-1459"),
    ("docs/reference/EVENT-SCHEMA.md", "`stdout`", "FEAT-1459"),
    ("docs/reference/EVENT-SCHEMA.md", "`ts`", "FEAT-1459"),
    ("docs/reference/EVENT-SCHEMA.md", '"intent"', "FEAT-1459"),
    ("docs/reference/EVENT-SCHEMA.md", "pre_compact", "FEAT-1459"),
    ("docs/reference/EVENT-SCHEMA.md", "session_start", "FEAT-1459"),
    ("docs/reference/EVENT-SCHEMA.md", "LLEvent", "FEAT-1459"),
    ("docs/reference/CONFIGURATION.md", "LLHookIntentExtension", "FEAT-1459"),
    ("docs/reference/API.md", "loop-specialist", "FEAT-1532"),
    ("docs/reference/COMMANDS.md", "**Arguments:**", "ENH-1362"),
    ("docs/reference/COMMANDS.md", "issues", "ENH-1362"),
    ("docs/guides/ISSUE_MANAGEMENT_GUIDE.md", "status:", "ENH-1421"),
    ("docs/reference/API.md", "{open,in_progress,blocked,deferred,done,cancelled,all}", "ENH-1428"),
    ("docs/guides/ISSUE_MANAGEMENT_GUIDE.md", "in_progress", "ENH-1428"),
    ("docs/guides/ISSUE_MANAGEMENT_GUIDE.md", "`done`", "ENH-1428"),
    ("docs/guides/ISSUE_MANAGEMENT_GUIDE.md", "`cancelled`", "ENH-1428"),
    ("docs/reference/ISSUE_TEMPLATE.md", "| `parent`", "ENH-1433"),
    ("docs/reference/ISSUE_TEMPLATE.md", "parent: EPIC-NNN", "ENH-1433"),
    ("docs/reference/API.md", "parent: str | None", "ENH-1433"),
    ("docs/reference/API.md", "depends_on: list[str]", "ENH-1433"),
    ("docs/reference/API.md", "relates_to: list[str]", "ENH-1433"),
    ("docs/reference/API.md", "duplicate_of: str | None", "ENH-1433"),
    ("docs/reference/API.md", "db_path", "ENH-1734"),
    ("docs/reference/API.md", "label_filter", "ENH-1734"),
    ("docs/reference/API.md", "preview_full", "ENH-1734"),
    ("docs/reference/API.md", "list[str] | set[str] | None", "ENH-1734"),
    ("docs/reference/API.md", "SQLiteTransport", "ENH-1734"),
    ("docs/reference/API.md", "complete_issue_lifecycle", "ENH-1734"),
    ("docs/reference/API.md", "defer_issue", "ENH-1734"),
    ("docs/reference/API.md", "in-place", "ENH-1734"),
    ("docs/reference/EVENT-SCHEMA.md", "| `issue.skipped`", "ENH-1734"),
    ("docs/reference/EVENT-SCHEMA.md", "| `issue.started`", "ENH-1734"),
    ("docs/reference/EVENT-SCHEMA.md", "### `issue.skipped`", "ENH-1734"),
    ("docs/reference/EVENT-SCHEMA.md", "### `issue.started`", "ENH-1734"),
    ("docs/reference/EVENT-SCHEMA.md", '"event": "issue.skipped"', "ENH-1734"),
    ("docs/reference/EVENT-SCHEMA.md", '"event": "issue.started"', "ENH-1734"),
    ("docs/reference/CONFIGURATION.md", "ENH-1691", "ENH-1734"),
    ("docs/reference/CONFIGURATION.md", "historical", "ENH-1734"),
    ("docs/reference/API.md", "## little_loops.history_reader", "ENH-1753"),
    ("docs/reference/API.md", "find_user_corrections", "ENH-1753"),
    ("docs/reference/API.md", "sessions_for_issue", "ENH-1753"),
    ("docs/reference/API.md", "include_stale", "ENH-1753"),
    ("docs/reference/API.md", "SessionRef", "ENH-1753"),
    ("docs/reference/COMMANDS.md", "EPIC", "ENH-1859"),
    ("docs/reference/API.md", "tree", "ENH-1866"),
    ("docs/reference/COMMANDS.md", "orch-router", "ENH-1912"),
    ("docs/reference/API.md", "little_loops.testing", "FEAT-1045"),
    ("docs/reference/COMMANDS.md", "Decisions log", "FEAT-948"),
    ("docs/reference/API.md", "rate_limits: RateLimitsConfig", "circuit-breaker"),
    ("docs/reference/API.md", "rate_limits:", "circuit-breaker"),
    # REMOVED (stale/false-positive): ("docs/reference/API.md", "circuit_breaker_enabled", "circuit-breaker"),
    ("docs/reference/API.md", "signal_detector", "ENH-1138"),
    ("docs/reference/API.md", "handoff_handler", "ENH-1138"),
    ("docs/reference/API.md", "loops_dir", "ENH-1138"),
    ("docs/reference/API.md", "circuit: RateLimitCircuit | None = None", "ENH-1138"),
    ("docs/reference/API.md", "### little_loops.fsm.rate_limit_circuit", "ENH-1138"),
    ("docs/reference/API.md", "RateLimitCircuit,", "ENH-1138"),
    ("docs/reference/API.md", "# Rate Limiting", "ENH-1138"),
    # REMOVED (stale/false-positive): ("docs/reference/API.md", "circuit_breaker_path", "ENH-1138"),
    ("docs/reference/CONFIGURATION.md", "circuit_breaker_enabled", "ENH-1138"),
    ("docs/reference/CONFIGURATION.md", "recursive_refine.max_depth", "ENH-1345"),
    ("docs/guides/ISSUE_MANAGEMENT_GUIDE.md", "ll-init", "ENH-1982"),
    ("docs/reference/CONFIGURATION.md", "ll-init", "ENH-1982"),
    ("docs/reference/API.md", "in_progress", "ENH-1428"),
    ("docs/reference/API.md", "`done`", "ENH-1428"),
    # REMOVED (stale): ("docs/guides/ISSUE_MANAGEMENT_GUIDE.md", "action: \"ll-issues list --status open", "ENH-1428"),
    # REMOVED (stale/false-positive): ("docs/reference/ISSUE_TEMPLATE.md", "parent: str | None", "ENH-1433"),
    # REMOVED (stale/false-positive): ("docs/reference/ISSUE_TEMPLATE.md", "depends_on: list[str]", "ENH-1433"),
    (
        "docs/guides/ISSUE_MANAGEMENT_GUIDE.md",
        "scan-product discovers goals from existing docs",
        "ENH-1443",
    ),
    # REMOVED (stale/false-positive): ("docs/guides/ISSUE_MANAGEMENT_GUIDE.md", "using goals file if present, or auto-discovering goals", "ENH-1443"),
    ("docs/reference/CONFIGURATION.md", "ll-goals.md` is optional", "ENH-1443"),
    (
        "docs/reference/CONFIGURATION.md",
        "These settings are active when `ll-goals.md` is absent",
        "ENH-1443",
    ),
    ("docs/reference/CONFIGURATION.md", "never block analysis", "ENH-1443"),
    ("docs/guides/ISSUE_MANAGEMENT_GUIDE.md", "silently coerced to canonical values", "ENH-1550"),
    # REMOVED (stale/false-positive): ("docs/guides/ISSUE_MANAGEMENT_GUIDE.md", "argparse validates choices before normalization runs", "ENH-1550"),
    # REMOVED (stale/false-positive): ("docs/reference/API.md", "| `issue.skipped`", "ENH-1734"),
    # REMOVED (stale/false-positive): ("docs/reference/API.md", "| `issue.started`", "ENH-1734"),
    ("docs/reference/EVENT-SCHEMA.md", 'event": "issue.skipped', "ENH-1734"),
    ("docs/reference/EVENT-SCHEMA.md", 'event": "issue.started', "ENH-1734"),
    ("docs/reference/EVENT-SCHEMA.md", "`ll-auto`", "ENH-1734"),
    ("docs/reference/EVENT-SCHEMA.md", "issue.skipped", "ENH-1734"),
    # REMOVED (stale/false-positive): ("docs/reference/CONFIGURATION.md", "issue.completed", "ENH-1734"),
    ("docs/reference/CONFIGURATION.md", "AutoManager", "ENH-1734"),
    ("docs/reference/COMMANDS.md", "EPIC-NNN", "ENH-1859"),
    # REMOVED (stale/false-positive): ("docs/reference/API.md", "ll-deps tree --epic", "ENH-1866"),
    ("docs/reference/API.md", "issue_effort", "ENH-1905"),
    ("docs/reference/API.md", "recent_issue_velocity", "ENH-1905"),
    ("docs/reference/CONFIGURATION.md", "### `history`", "ENH-1916"),
    ("docs/reference/CONFIGURATION.md", "velocity_window", "ENH-1916"),
    ("docs/reference/CONFIGURATION.md", "max_age_days", "ENH-1916"),
    ("docs/reference/CONFIGURATION.md", "session_digest", "ENH-1916"),
    ("docs/reference/CONFIGURATION.md", "evolution", "ENH-1916"),
    ("docs/reference/CONFIGURATION.md", "go_no_go", "ENH-1916"),
    ("docs/reference/CONFIGURATION.md", "capture_issue", "ENH-1916"),
    ("docs/reference/API.md", "LLHookIntentExtension", "FEAT-1457"),
    ("docs/reference/API.md", "_HOOK_INTENT_REGISTRY", "FEAT-1457"),
    ("docs/reference/EVENT-SCHEMA.md", "intent", "FEAT-1459"),
    # REMOVED (stale/false-positive): ("docs/reference/EVENT-SCHEMA.md", "`little_loops.hooks`", "FEAT-1459"),
    # REMOVED (stale/false-positive): ("docs/reference/EVENT-SCHEMA.md", "### LLHookEvent", "FEAT-1459"),
    # REMOVED (stale/false-positive): ("docs/reference/CONFIGURATION.md", "hooks/scripts/context-monitor.sh", "FEAT-1459"),
    ("docs/reference/API.md", "host_runner", "FEAT-1462"),
    ("docs/reference/API.md", "resolve_host", "FEAT-1462"),
    ("docs/reference/API.md", "HostInvocation", "FEAT-1462"),
    ("docs/reference/API.md", "HostNotConfigured", "FEAT-1462"),
    ("docs/reference/API.md", "CapabilityNotSupported", "FEAT-1462"),
    ("docs/reference/API.md", "CapabilityReport", "FEAT-1462"),
    ("docs/reference/API.md", "CapabilityEntry", "FEAT-1462"),
    ("docs/reference/API.md", "HookEntry", "FEAT-1462"),
    ("docs/reference/API.md", "describe_capabilities", "FEAT-1462"),
    ("docs/reference/API.md", "Orchestration", "FEAT-1462"),
    ("docs/reference/COMMANDS.md", "### `/ll:review-epic`", "FEAT-1856"),
    ("docs/reference/COMMANDS.md", "| `review-epic`", "FEAT-1856"),
    ("docs/reference/COMMANDS.md", "### `/ll:scope-epic`", "FEAT-1857"),
    ("docs/reference/COMMANDS.md", "| `scope-epic`", "FEAT-1857"),
    # REMOVED (stale/false-positive): ("docs/reference/COMMANDS.md", "ll-generate-schemas", "FEAT-1045"),
    ("docs/reference/API.md", "DecisionsConfig", "FEAT-1045"),
    ("docs/reference/COMMANDS.md", "decisions.yaml", "FEAT-1045"),
    ("docs/reference/CONFIGURATION.md", "### `design_tokens`", "FEAT-1758"),
    ("docs/reference/CONFIGURATION.md", "design_tokens", "FEAT-1758"),
    ("docs/reference/CONFIGURATION.md", "`enabled`", "FEAT-1758"),
    ("docs/reference/CONFIGURATION.md", ".ll/design-tokens", "FEAT-1758"),
    ("docs/reference/CONFIGURATION.md", "primitives_file", "FEAT-1758"),
    ("docs/reference/CONFIGURATION.md", "semantic_file", "FEAT-1758"),
    ("docs/reference/CONFIGURATION.md", "themes_dir", "FEAT-1758"),
    ("docs/reference/CONFIGURATION.md", "active_theme", "FEAT-1758"),
    # REMOVED (stale/false-positive): ("docs/reference/CONFIGURATION.md", "#### DesignTokensConfig", "FEAT-1758"),
    # REMOVED (stale/false-positive): ("docs/reference/CONFIGURATION.md", "DesignTokensConfig", "FEAT-1758"),
    ("docs/reference/API.md", "#### DesignTokensConfig", "FEAT-1758"),
    ("docs/reference/API.md", "DesignTokensConfig", "FEAT-1758"),
]


@pytest.mark.parametrize("doc_rel, needle, issue_id", DOC_STRINGS_PRESENT)
def test_string_present_in_doc(
    project_root: Path, doc_rel: str, needle: str, issue_id: str
) -> None:
    """Verify that expected strings appear in documentation files."""
    content = (project_root / doc_rel).read_text()
    assert needle in content, "[{issue_id}] {doc_rel} must contain: {needle!r}"


# -- 19 string-absence assertions --------------------------------

DOC_STRINGS_ABSENT: list[tuple[str, str, str]] = [
    # (doc_path, forbidden_string, issue_id)
    ("docs/guides/ISSUE_MANAGEMENT_GUIDE.md", "Directory location determines", "ENH-1421"),
    ("docs/reference/API.md", "{active,completed,deferred,all}", "ENH-1428"),
    ("docs/reference/API.md", "default: `active`)", "ENH-1428"),
    (
        "docs/reference/API.md",
        "Searches all active category directories and the completed directory",
        "ENH-1428",
    ),
    ("docs/reference/API.md", "active, completed, and/or deferred", "ENH-1428"),
    ("docs/guides/ISSUE_MANAGEMENT_GUIDE.md", "| `active` |", "ENH-1428"),
    ("docs/guides/ISSUE_MANAGEMENT_GUIDE.md", "| `completed` |", "ENH-1428"),
    (
        "docs/guides/ISSUE_MANAGEMENT_GUIDE.md",
        "Directory location determines CLI bucketing",
        "ENH-1428",
    ),
    ("docs/reference/ISSUE_TEMPLATE.md", "| `parent_issue`", "ENH-1433"),
    ("docs/reference/ISSUE_TEMPLATE.md", "parent_issue: EPIC-NNN", "ENH-1433"),
    ("docs/reference/COMMANDS.md", "installs/shows/validates", "BUG-863"),
    (
        "docs/guides/ISSUE_MANAGEMENT_GUIDE.md",
        "create `ll-goals.md` by copying `templates/ll-goals-template.md`",
        "ENH-1401",
    ),
    ("docs/guides/ISSUE_MANAGEMENT_GUIDE.md", "COMPLETED[.issues/completed/]", "ENH-1421"),
    ("docs/guides/ISSUE_MANAGEMENT_GUIDE.md", "--status active", "ENH-1428"),
    ("docs/reference/COMMANDS.md", "Goals file exists", "ENH-1443"),
    ("docs/reference/COMMANDS.md", "Requires a product goals file", "ENH-1443"),
    ("docs/guides/ISSUE_MANAGEMENT_GUIDE.md", "Goals file exists", "ENH-1443"),
    ("docs/reference/CONFIGURATION.md", "enables /ll:scan-product", "ENH-1443"),
    ("docs/reference/API.md", "Resolve `${CLAUDE_PLUGIN_ROOT}` by substituting", "FEAT-1045"),
]


@pytest.mark.parametrize("doc_rel, needle, issue_id", DOC_STRINGS_ABSENT)
def test_string_absent_from_doc(
    project_root: Path, doc_rel: str, needle: str, issue_id: str
) -> None:
    """Verify that stale/forbidden strings do NOT appear in documentation files."""
    content = (project_root / doc_rel).read_text()
    assert needle not in content, "[{issue_id}] {doc_rel} must NOT contain: {needle!r}"


# -- 3 file-existence assertions -----------------------------------

DOC_FILES_MUST_EXIST: list[tuple[str, str]] = [
    # (file_path, issue_id)
    ("docs/guides/ISSUE_MANAGEMENT_GUIDE.md", "ENH-1401"),
    ("docs/reference/CONFIGURATION.md", "ENH-1401"),
    ("docs/reference/COMMANDS.md", "ENH-1859"),
]


@pytest.mark.parametrize("doc_rel, issue_id", DOC_FILES_MUST_EXIST)
def test_file_exists(project_root: Path, doc_rel: str, issue_id: str) -> None:
    """Verify that expected documentation files exist."""
    assert (project_root / doc_rel).exists(), "[{issue_id}] File must exist: {doc_rel}"
