"""Tests for FEAT-1856: review-epic skill wiring and doc count updates.

Asserts that the review-epic skill file exists, documentation surfaces reference it,
and config-schema.json declares the commands.review_epic block.
"""

from __future__ import annotations

import json
from pathlib import Path

PROJECT_ROOT = Path(__file__).parent.parent.parent

README = PROJECT_ROOT / "README.md"
CONTRIBUTING = PROJECT_ROOT / "CONTRIBUTING.md"
ARCHITECTURE = PROJECT_ROOT / "docs" / "ARCHITECTURE.md"
HELP_CMD = PROJECT_ROOT / "commands" / "help.md"
CLAUDE_MD = PROJECT_ROOT / ".claude" / "CLAUDE.md"
COMMANDS_MD = PROJECT_ROOT / "docs" / "reference" / "COMMANDS.md"
CONFIG_SCHEMA = PROJECT_ROOT / "config-schema.json"
SKILL_REVIEW_EPIC = PROJECT_ROOT / "skills" / "review-epic" / "SKILL.md"
OPENAI_YAML = PROJECT_ROOT / "skills" / "review-epic" / "agents" / "openai.yaml"


class TestReviewEpicSkillExists:
    """skills/review-epic/SKILL.md and agents/openai.yaml must exist."""

    def test_skill_file_exists(self) -> None:
        assert SKILL_REVIEW_EPIC.exists(), (
            "skills/review-epic/SKILL.md must be created (FEAT-1856)"
        )

    def test_openai_yaml_exists(self) -> None:
        assert OPENAI_YAML.exists(), (
            "skills/review-epic/agents/openai.yaml must be generated by ll-adapt-skills-for-codex"
        )


class TestReadmeSkillCount:
    """README.md hero page must reflect 60 skills."""

    def test_skill_count_updated(self) -> None:
        content = README.read_text()
        assert "60 skills" in content, "README.md must show '60 skills'"


class TestContributingWiring:
    """CONTRIBUTING.md must reflect 32 skills and list review-epic/ in the skills tree."""

    def test_skill_count_updated(self) -> None:
        content = CONTRIBUTING.read_text()
        assert "32 skill definitions" in content, (
            "CONTRIBUTING.md skill count line must show '32 skill definitions'"
        )

    def test_review_epic_in_skills_tree(self) -> None:
        content = CONTRIBUTING.read_text()
        assert "review-epic/" in content, (
            "CONTRIBUTING.md skills tree must include 'review-epic/'"
        )


class TestArchitectureSkillCount:
    """docs/ARCHITECTURE.md must reflect 32 skills in both the Mermaid node and tree."""

    def test_mermaid_skill_count_updated(self) -> None:
        content = ARCHITECTURE.read_text()
        assert "32 composable skills" in content, (
            "ARCHITECTURE.md Mermaid node must show '32 composable skills'"
        )

    def test_tree_skill_count_updated(self) -> None:
        content = ARCHITECTURE.read_text()
        assert "# 32 skill definitions" in content, (
            "ARCHITECTURE.md directory tree must show '# 32 skill definitions'"
        )


class TestHelpCommandWiring:
    """commands/help.md must list /ll:review-epic in the command reference and quick table."""

    def test_review_epic_command_listed(self) -> None:
        content = HELP_CMD.read_text()
        assert "/ll:review-epic" in content, (
            "commands/help.md must include /ll:review-epic in the command reference"
        )

    def test_review_epic_in_quick_reference(self) -> None:
        content = HELP_CMD.read_text()
        assert "review-epic" in content, (
            "commands/help.md quick-reference Planning & Implementation must include review-epic"
        )


class TestClaudeMdWiring:
    """CLAUDE.md Commands & Skills section must mention review-epic."""

    def test_review_epic_in_claude_md(self) -> None:
        content = CLAUDE_MD.read_text()
        assert "review-epic" in content, (
            ".claude/CLAUDE.md Commands & Skills section must mention review-epic"
        )


class TestCommandsMdWiring:
    """docs/reference/COMMANDS.md must have a /ll:review-epic section and Quick Reference row."""

    def test_review_epic_section_exists(self) -> None:
        content = COMMANDS_MD.read_text()
        assert "### `/ll:review-epic`" in content, (
            "docs/reference/COMMANDS.md must include ### `/ll:review-epic` section"
        )

    def test_review_epic_in_quick_reference_table(self) -> None:
        content = COMMANDS_MD.read_text()
        assert "| `review-epic`" in content, (
            "docs/reference/COMMANDS.md Quick Reference table must include review-epic row"
        )


class TestConfigSchemaWiring:
    """config-schema.json must declare commands.review_epic with stale_days and enable_scope_drift_check."""

    def test_commands_review_epic_in_schema(self) -> None:
        data = json.loads(CONFIG_SCHEMA.read_text())
        commands = data["properties"]["commands"]
        assert commands.get("additionalProperties") is False, (
            "commands block is expected to have additionalProperties: false"
        )
        assert "review_epic" in commands["properties"], (
            "commands.review_epic is not declared; configs using it will be "
            "rejected by additionalProperties: false"
        )
        re_ = commands["properties"]["review_epic"]
        assert re_["type"] == "object"
        re_props = re_["properties"]
        assert re_props["stale_days"]["type"] == "integer"
        assert re_props["stale_days"]["minimum"] == 1
        assert re_props["stale_days"]["default"] == 14
        assert re_props["enable_scope_drift_check"]["type"] == "boolean"
        assert re_props["enable_scope_drift_check"]["default"] is True
