"""Tests for /ll:adversarial-verify-loop skill artifacts.

Since /ll:adversarial-verify-loop is a prompt-based skill (markdown instructions
for Claude), we test:

1. Expected emitted YAML structure: 3 probe states + count_probes shell gate
2. Routing: each probe's on_yes chains forward, final probe → count_probes → done
3. Failure routing: every probe's on_no → failed_with_finding
4. count_probes uses output_numeric (non-LLM, MR-1 complement) with target 3
5. Three terminal states: done, failed_with_finding, failed_too_few
6. Generated YAML passes FSM validation via load_and_validate + validate_fsm
"""

from __future__ import annotations

import sys
from pathlib import Path

import pytest
import yaml

from little_loops.fsm.validation import ValidationSeverity, load_and_validate, validate_fsm

# ---------------------------------------------------------------------------
# Fixture — inline YAML representing expected emitted output for a typical issue.
# ---------------------------------------------------------------------------

ADVERSARIAL_YAML = """
name: adversarial-feat-919-add-json-schema-generation
category: verification
description: |
  Adversarial verification loop for FEAT-919: Add JSON schema generation.
  Tries to break the feature via boundary values, malformed/hostile inputs, and failure modes.
  FAIL fires when fewer than 3 probe classes are genuinely attempted (count_probes gate).
  Generated by /ll:adversarial-verify-loop on 2026-06-14.
initial: probe-boundary
max_iterations: 20
timeout: 2700

states:

  probe-boundary:
    action: >
      Probe boundary conditions for FEAT-919: Add JSON schema generation.

      Try to break the feature using boundary and extreme values: empty inputs, maximum sizes,
      off-by-one values, Unicode edge cases, very large payloads, zero/negative numbers.
      Attempt at least two distinct boundary probes. For each probe, run a real command or
      exercise the feature concretely — do not just theorize.

      After probing, write a JSON result to ${context.run_dir}/probe-boundary.json:
        {"probe_class": "boundary", "probes_attempted": 2, "break_found": false, "finding": "handled correctly"}

      Report what you tried and what you observed.
    action_type: prompt
    timeout: 300
    evaluate:
      type: llm_structured
      prompt: >
        Did the boundary probe of FEAT-919 survive without exposing a genuine break?

        A genuine break is a reproducible bug, crash, error, or wrong output caused by the probe.
        A probe that did NOT break the feature (the feature handled it correctly) is a PASS.

        Answer YES if the feature survived all boundary probes (no genuine break found).
        Answer NO if the probe found a genuine break — a reproducible failure, crash, or wrong output.
        Provide a one-sentence reason citing what was tried and what was observed.
    on_yes: probe-malformed-hostile
    on_no: failed_with_finding

  probe-malformed-hostile:
    action: >
      Probe malformed and hostile inputs for FEAT-919: Add JSON schema generation.

      Try to break the feature using: wrong types, injection-shaped strings (shell, path-traversal),
      partial or incomplete state, concurrent or duplicate invocations, null/None values,
      unexpected encoding, negative indices.
      Attempt at least two distinct malformed/hostile probes. Run real commands — do not theorize.

      After probing, write a JSON result to ${context.run_dir}/probe-malformed.json:
        {"probe_class": "malformed_hostile", "probes_attempted": 2, "break_found": false, "finding": "handled correctly"}

      Report what you tried and what you observed.
    action_type: prompt
    timeout: 300
    evaluate:
      type: llm_structured
      prompt: >
        Did the malformed/hostile-input probe of FEAT-919 survive without exposing a genuine break?

        Answer YES if the feature survived (handled all malformed/hostile inputs correctly or gracefully).
        Answer NO if a probe found a genuine break — a reproducible failure, crash, or wrong output.
        Provide a one-sentence reason citing what was tried and what was observed.
    on_yes: probe-failure-mode
    on_no: failed_with_finding

  probe-failure-mode:
    action: >
      Probe known failure modes for FEAT-919: Add JSON schema generation.

      Try to break the feature by simulating failure conditions: missing config files,
      absent required files or directories, interrupted or partial runs, corrupted state,
      unavailable dependencies, missing environment variables, permission errors.
      Attempt at least two distinct failure-mode probes. Run real commands — do not theorize.

      After probing, write a JSON result to ${context.run_dir}/probe-failure.json:
        {"probe_class": "failure_mode", "probes_attempted": 2, "break_found": false, "finding": "handled correctly"}

      Report what you tried and what you observed.
    action_type: prompt
    timeout: 300
    evaluate:
      type: llm_structured
      prompt: >
        Did the failure-mode probe of FEAT-919 survive without exposing a genuine break?

        Answer YES if the feature survived (handled failure modes correctly or raised clean errors).
        Answer NO if a probe found a genuine break — a reproducible failure, crash, or wrong output.
        Provide a one-sentence reason citing what was tried and what was observed.
    on_yes: count_probes
    on_no: failed_with_finding

  count_probes:
    action_type: shell
    action: |
      ls "${context.run_dir}"/probe-*.json 2>/dev/null | wc -l | tr -d ' '
    evaluate:
      type: output_numeric
      operator: ge
      target: 3
    on_yes: done
    on_no: failed_too_few

  done:
    terminal: true

  failed_with_finding:
    terminal: true

  failed_too_few:
    terminal: true
"""

# ---------------------------------------------------------------------------
# YAML representing a loop where the boundary probe broke the feature
# (on_no → failed_with_finding)
# ---------------------------------------------------------------------------

ADVERSARIAL_YAML_BREAK_FOUND = """
name: adversarial-feat-919-break-found
category: verification
description: |
  Adversarial verification loop variant — boundary probe finds a break.
initial: probe-boundary
max_iterations: 20
timeout: 2700

states:

  probe-boundary:
    action: >
      Probe boundary conditions for FEAT-919.
      Write result to ${context.run_dir}/probe-boundary.json.
    action_type: prompt
    timeout: 300
    evaluate:
      type: llm_structured
      prompt: >
        Did the boundary probe survive? Answer YES or NO.
    on_yes: probe-malformed-hostile
    on_no: failed_with_finding

  probe-malformed-hostile:
    action: >
      Probe malformed inputs for FEAT-919.
      Write result to ${context.run_dir}/probe-malformed.json.
    action_type: prompt
    timeout: 300
    evaluate:
      type: llm_structured
      prompt: >
        Did the malformed probe survive? Answer YES or NO.
    on_yes: probe-failure-mode
    on_no: failed_with_finding

  probe-failure-mode:
    action: >
      Probe failure modes for FEAT-919.
      Write result to ${context.run_dir}/probe-failure.json.
    action_type: prompt
    timeout: 300
    evaluate:
      type: llm_structured
      prompt: >
        Did the failure-mode probe survive? Answer YES or NO.
    on_yes: count_probes
    on_no: failed_with_finding

  count_probes:
    action_type: shell
    action: |
      ls "${context.run_dir}"/probe-*.json 2>/dev/null | wc -l | tr -d ' '
    evaluate:
      type: output_numeric
      operator: ge
      target: 3
    on_yes: done
    on_no: failed_too_few

  done:
    terminal: true

  failed_with_finding:
    terminal: true

  failed_too_few:
    terminal: true
"""

# ---------------------------------------------------------------------------
# YAML representing a loop where count_probes < 3 (failed_too_few terminal)
# ---------------------------------------------------------------------------

ADVERSARIAL_YAML_TOO_FEW = """
name: adversarial-feat-919-too-few
category: verification
description: |
  Adversarial verification loop variant — fewer than 3 probes attempted (too-few path).
initial: probe-boundary
max_iterations: 20
timeout: 2700

states:

  probe-boundary:
    action: >
      Probe boundary conditions for FEAT-919.
      Write result to ${context.run_dir}/probe-boundary.json.
    action_type: prompt
    timeout: 300
    evaluate:
      type: llm_structured
      prompt: >
        Did the boundary probe survive? Answer YES or NO.
    on_yes: probe-malformed-hostile
    on_no: failed_with_finding

  probe-malformed-hostile:
    action: >
      Probe malformed inputs for FEAT-919.
      Write result to ${context.run_dir}/probe-malformed.json.
    action_type: prompt
    timeout: 300
    evaluate:
      type: llm_structured
      prompt: >
        Did the malformed probe survive? Answer YES or NO.
    on_yes: probe-failure-mode
    on_no: failed_with_finding

  probe-failure-mode:
    action: >
      Probe failure modes for FEAT-919.
      Write result to ${context.run_dir}/probe-failure.json.
    action_type: prompt
    timeout: 300
    evaluate:
      type: llm_structured
      prompt: >
        Did the failure-mode probe survive? Answer YES or NO.
    on_yes: count_probes
    on_no: failed_with_finding

  count_probes:
    action_type: shell
    action: |
      ls "${context.run_dir}"/probe-*.json 2>/dev/null | wc -l | tr -d ' '
    evaluate:
      type: output_numeric
      operator: ge
      target: 3
    on_yes: done
    on_no: failed_too_few

  done:
    terminal: true

  failed_with_finding:
    terminal: true

  failed_too_few:
    terminal: true
"""


# ---------------------------------------------------------------------------
# Structural Tests — adversarial loop shape
# ---------------------------------------------------------------------------


class TestAdversarialLoopStructure:
    """Structural tests for the adversarial verification loop."""

    @pytest.fixture
    def loop(self) -> dict:
        return yaml.safe_load(ADVERSARIAL_YAML)

    def test_parses_as_yaml(self, loop: dict) -> None:
        assert isinstance(loop, dict)

    def test_initial_state_is_probe_boundary(self, loop: dict) -> None:
        assert loop.get("initial") == "probe-boundary"

    def test_category_is_verification(self, loop: dict) -> None:
        assert loop.get("category") == "verification"

    def test_has_all_probe_states(self, loop: dict) -> None:
        states = loop.get("states", {})
        for name in ("probe-boundary", "probe-malformed-hostile", "probe-failure-mode"):
            assert name in states, f"missing probe state: {name}"

    def test_has_count_probes_state(self, loop: dict) -> None:
        assert "count_probes" in loop.get("states", {})

    def test_probe_states_are_prompt_type(self, loop: dict) -> None:
        states = loop["states"]
        for name in ("probe-boundary", "probe-malformed-hostile", "probe-failure-mode"):
            assert states[name].get("action_type") == "prompt", f"{name} must be action_type: prompt"

    def test_probe_states_have_llm_structured_evaluator(self, loop: dict) -> None:
        states = loop["states"]
        for name in ("probe-boundary", "probe-malformed-hostile", "probe-failure-mode"):
            evaluate = states[name].get("evaluate", {})
            assert evaluate.get("type") == "llm_structured", f"{name} must use llm_structured evaluator"

    def test_probe_state_evaluator_prompts_are_substantive(self, loop: dict) -> None:
        states = loop["states"]
        for name in ("probe-boundary", "probe-malformed-hostile", "probe-failure-mode"):
            prompt = states[name].get("evaluate", {}).get("prompt", "")
            assert len(prompt) > 20, f"llm_structured prompt for {name} too short"

    def test_probe_boundary_routes_on_yes_to_malformed(self, loop: dict) -> None:
        states = loop["states"]
        assert states["probe-boundary"].get("on_yes") == "probe-malformed-hostile"

    def test_probe_malformed_routes_on_yes_to_failure_mode(self, loop: dict) -> None:
        states = loop["states"]
        assert states["probe-malformed-hostile"].get("on_yes") == "probe-failure-mode"

    def test_probe_failure_mode_routes_on_yes_to_count_probes(self, loop: dict) -> None:
        states = loop["states"]
        assert states["probe-failure-mode"].get("on_yes") == "count_probes"

    def test_every_probe_routes_on_no_to_failed_with_finding(self, loop: dict) -> None:
        states = loop["states"]
        for name in ("probe-boundary", "probe-malformed-hostile", "probe-failure-mode"):
            assert states[name].get("on_no") == "failed_with_finding", (
                f"{name}.on_no must route to failed_with_finding"
            )

    def test_count_probes_is_shell_type(self, loop: dict) -> None:
        state = loop["states"]["count_probes"]
        assert state.get("action_type") == "shell"

    def test_count_probes_uses_output_numeric_evaluator(self, loop: dict) -> None:
        evaluate = loop["states"]["count_probes"].get("evaluate", {})
        assert evaluate.get("type") == "output_numeric"

    def test_count_probes_operator_is_ge(self, loop: dict) -> None:
        evaluate = loop["states"]["count_probes"].get("evaluate", {})
        assert evaluate.get("operator") == "ge"

    def test_count_probes_target_is_3(self, loop: dict) -> None:
        evaluate = loop["states"]["count_probes"].get("evaluate", {})
        assert evaluate.get("target") == 3

    def test_count_probes_routes_on_yes_to_done(self, loop: dict) -> None:
        assert loop["states"]["count_probes"].get("on_yes") == "done"

    def test_count_probes_routes_on_no_to_failed_too_few(self, loop: dict) -> None:
        assert loop["states"]["count_probes"].get("on_no") == "failed_too_few"

    def test_has_terminal_done(self, loop: dict) -> None:
        states = loop.get("states", {})
        assert "done" in states
        assert states["done"].get("terminal") is True

    def test_has_terminal_failed_with_finding(self, loop: dict) -> None:
        states = loop.get("states", {})
        assert "failed_with_finding" in states
        assert states["failed_with_finding"].get("terminal") is True

    def test_has_terminal_failed_too_few(self, loop: dict) -> None:
        states = loop.get("states", {})
        assert "failed_too_few" in states
        assert states["failed_too_few"].get("terminal") is True

    def test_no_discover_state(self, loop: dict) -> None:
        assert "discover" not in loop.get("states", {})

    def test_no_advance_state(self, loop: dict) -> None:
        assert "advance" not in loop.get("states", {})


# ---------------------------------------------------------------------------
# Routing scenario tests
# ---------------------------------------------------------------------------


class TestAdversarialLoopRoutingScenarios:
    """Tests that all three outcome scenarios have correct routing."""

    def test_break_found_variant_has_failed_with_finding_terminal(self) -> None:
        """Variant representing a break found: failed_with_finding must be terminal."""
        loop = yaml.safe_load(ADVERSARIAL_YAML_BREAK_FOUND)
        states = loop.get("states", {})
        assert "failed_with_finding" in states
        assert states["failed_with_finding"].get("terminal") is True

    def test_too_few_variant_has_failed_too_few_terminal(self) -> None:
        """Variant representing too-few probes: failed_too_few must be terminal."""
        loop = yaml.safe_load(ADVERSARIAL_YAML_TOO_FEW)
        states = loop.get("states", {})
        assert "failed_too_few" in states
        assert states["failed_too_few"].get("terminal") is True

    def test_all_probes_pass_path_ends_at_done(self) -> None:
        """Happy path: probe-boundary→probe-malformed-hostile→probe-failure-mode→count_probes→done."""
        loop = yaml.safe_load(ADVERSARIAL_YAML)
        states = loop["states"]
        # Walk the on_yes chain
        path = []
        state = "probe-boundary"
        for _ in range(10):
            path.append(state)
            nxt = states[state].get("on_yes")
            if nxt is None or states.get(nxt, {}).get("terminal"):
                if nxt:
                    path.append(nxt)
                break
            state = nxt
        assert path == [
            "probe-boundary",
            "probe-malformed-hostile",
            "probe-failure-mode",
            "count_probes",
            "done",
        ]


# ---------------------------------------------------------------------------
# Validation Tests — generated YAML passes FSM validation
# ---------------------------------------------------------------------------


class TestAdversarialLoopValidation:
    """Tests that generated YAML passes ll-loop validate (via load_and_validate)."""

    @pytest.fixture
    def loops_dir(self, tmp_path: Path) -> Path:
        loops = tmp_path / ".loops"
        loops.mkdir()
        return loops

    def test_passes_fsm_validation(self, loops_dir: Path, monkeypatch: pytest.MonkeyPatch) -> None:
        """Adversarial YAML passes FSM structural validation."""
        path = loops_dir / "adversarial-feat-919-add-json-schema-generation.yaml"
        path.write_text(ADVERSARIAL_YAML)
        monkeypatch.chdir(loops_dir.parent)

        fsm, _ = load_and_validate(path)
        errors = validate_fsm(fsm)
        hard_errors = [e for e in errors if e.severity == ValidationSeverity.ERROR]
        assert not hard_errors, f"FSM errors: {[str(e) for e in hard_errors]}"

    def test_passes_via_cli(self, loops_dir: Path, monkeypatch: pytest.MonkeyPatch) -> None:
        """Adversarial YAML passes ll-loop validate CLI (exit 0)."""
        name = "adversarial-feat-919-add-json-schema-generation"
        (loops_dir / f"{name}.yaml").write_text(ADVERSARIAL_YAML)
        monkeypatch.chdir(loops_dir.parent)

        with pytest.MonkeyPatch.context() as mp:
            mp.setattr(sys, "argv", ["ll-loop", "validate", name])
            from little_loops.cli import main_loop

            result = main_loop()

        assert result == 0
