"""Consolidated doc-wiring tests — Init and configure skill documentation wiring.

Generated by ENH-1963: Audit and Consolidate Doc-Wiring Tests.
All original assertions from 24 source files preserved as parametrized cases.
"""

from __future__ import annotations

from pathlib import Path

import pytest

# =============================================================================
# Shared paths (resolved from project_root fixture)
# =============================================================================


# -- 149 string-presence assertions -------------------------------

DOC_STRINGS_PRESENT: list[tuple[str, str, str]] = [
    # (doc_path, expected_string, issue_id)
    # REMOVED (stub ENH-1982): ("skills/init/interactive.md", "Learning Tests", "FEAT-1743"),
    # REMOVED (stub ENH-1982): ("skills/init/interactive.md", "TOTAL = 11", "ENH-2040"),
    # REMOVED (stub ENH-1982): ("skills/init/SKILL.md", "learning_tests", "FEAT-1743"),
    # REMOVED (stub ENH-1982): ("skills/init/SKILL.md", "10–11 rounds", "ENH-2040"),
    ("skills/configure/SKILL.md", "learning-tests", "FEAT-1743"),
    ("skills/configure/areas.md", "## Area: learning_tests", "FEAT-1743"),
    ("skills/configure/areas.md", "learning_tests.enabled", "FEAT-1743"),
    ("skills/configure/areas.md", "learning_tests.stale_after_days", "FEAT-1743"),
    ("skills/configure/areas.md", "learning_tests.discoverability", "FEAT-1743"),
    ("skills/configure/show-output.md", "## learning_tests --show", "FEAT-1743"),
    ("skills/configure/show-output.md", "learning_tests.enabled", "FEAT-1743"),
    ("skills/configure/show-output.md", "learning_tests.stale_after_days", "FEAT-1743"),
    ("skills/configure/show-output.md", "learning_tests.discoverability", "FEAT-1743"),
    # REMOVED (stub ENH-1982): ("skills/init/interactive.md", "## Round 7: Design Tokens", "FEAT-1756"),
    # REMOVED (stub ENH-1982): ("skills/init/SKILL.md", "design_tokens", "FEAT-1756"),
    ("skills/configure/SKILL.md", "design_tokens", "FEAT-1757"),
    ("skills/configure/SKILL.md", "design-tokens", "FEAT-1757"),
    ("skills/configure/areas.md", "## Area: design_tokens", "FEAT-1757"),
    ("skills/configure/areas.md", "design_tokens.enabled", "FEAT-1757"),
    ("skills/configure/areas.md", "design_tokens.path", "FEAT-1757"),
    ("skills/configure/areas.md", "design_tokens.primitives_file", "FEAT-1757"),
    ("skills/configure/areas.md", "design_tokens.semantic_file", "FEAT-1757"),
    ("skills/configure/areas.md", "design_tokens.themes_dir", "FEAT-1757"),
    ("skills/configure/areas.md", "design_tokens.active_theme", "FEAT-1757"),
    ("skills/configure/show-output.md", "## design_tokens --show", "FEAT-1757"),
    ("skills/configure/show-output.md", "design_tokens.enabled", "FEAT-1757"),
    ("skills/configure/show-output.md", "design_tokens.path", "FEAT-1757"),
    ("skills/configure/show-output.md", "design_tokens.primitives_file", "FEAT-1757"),
    ("skills/configure/show-output.md", "design_tokens.semantic_file", "FEAT-1757"),
    ("skills/configure/show-output.md", "design_tokens.themes_dir", "FEAT-1757"),
    ("skills/configure/show-output.md", "design_tokens.active_theme", "FEAT-1757"),
    # REMOVED (stub ENH-1982): ("skills/init/interactive.md", "## Round 9: Analytics", "ENH-1884"),
    # REMOVED (stub ENH-1982): ("skills/init/SKILL.md", "analytics", "ENH-1884"),
    ("skills/configure/SKILL.md", "analytics", "ENH-1884"),
    ("skills/configure/areas.md", "## Area: analytics", "ENH-1884"),
    ("skills/configure/areas.md", "analytics.enabled", "ENH-1884"),
    ("skills/configure/areas.md", "analytics.capture.skills", "ENH-1884"),
    ("skills/configure/areas.md", "analytics.capture.corrections", "ENH-1884"),
    ("skills/configure/areas.md", "analytics.capture.file_events", "ENH-1884"),
    ("skills/configure/show-output.md", "## analytics --show", "ENH-1884"),
    ("skills/configure/show-output.md", "analytics.enabled", "ENH-1884"),
    ("skills/configure/show-output.md", "analytics.capture.skills", "ENH-1884"),
    ("skills/configure/show-output.md", "analytics.capture.corrections", "ENH-1884"),
    ("skills/configure/show-output.md", "analytics.capture.file_events", "ENH-1884"),
    ("skills/configure/areas.md", "Configuration Result", "ENH-1836"),
    ("skills/configure/areas.md", "shutil.copytree", "ENH-1836"),
    ("skills/configure/areas.md", "default", "ENH-1836"),
    ("skills/configure/areas.md", "editorial-mono", "ENH-1836"),
    ("skills/configure/areas.md", "warm-paper", "ENH-1836"),
    ("skills/configure/areas.md", "AskUserQuestion", "ENH-1836"),
    ("skills/configure/areas.md", "DANGEROUSLY_SKIP_PERMISSIONS", "ENH-1836"),
    ("skills/configure/SKILL.md", "Bash(python3:*)", "ENH-1836"),
    ("skills/configure/SKILL.md", "| `history` |", "ENH-1916"),
    ("skills/configure/SKILL.md", "`history`", "ENH-1916"),
    ("skills/configure/SKILL.md", "history", "ENH-1916"),
    ("skills/configure/areas.md", "## Area: history", "ENH-1916"),
    ("skills/configure/areas.md", "session_digest.enabled", "ENH-1916"),
    ("skills/configure/areas.md", "velocity_window", "ENH-1916"),
    ("skills/configure/areas.md", "max_age_days", "ENH-1916"),
    ("skills/configure/areas.md", "planning_skills", "ENH-1916"),
    ("skills/configure/show-output.md", "## history --show", "ENH-1916"),
    ("skills/configure/show-output.md", "history.velocity_window", "ENH-1916"),
    ("skills/configure/show-output.md", "history.session_digest.enabled", "ENH-1916"),
    ("skills/configure/show-output.md", "history.go_no_go", "ENH-1916"),
    ("skills/configure/show-output.md", "history.capture_issue", "ENH-1916"),
    # REMOVED (stub ENH-1982): ("skills/init/SKILL.md", '"Bash(ll-create-extension:*)"', "FEAT-1049"),
    ("skills/configure/areas.md", "Authorize all 31", "FEAT-1049"),
    ("skills/configure/areas.md", "ll-create-extension", "FEAT-1049"),
    # REMOVED (stub ENH-1982): ("skills/init/SKILL.md", "hooks fire automatically", "BUG-863"),
    ("skills/configure/areas.md", "Manual hook installation is not needed", "BUG-863"),
    ("skills/configure/areas.md", "ll-action", "FEAT-1229"),
    # REMOVED (stub ENH-1982): ("skills/init/SKILL.md", '"Bash(ll-action:*)"', "FEAT-1229"),
    ("skills/configure/areas.md", "ll-harness", "FEAT-1689"),
    # REMOVED (stub ENH-1982): ("skills/init/SKILL.md", '"Bash(ll-harness:*)"', "FEAT-1689"),
    ("skills/configure/areas.md", "ll-adapt", "FEAT-1526"),
    # REMOVED (stub ENH-1982): ("skills/init/SKILL.md", '"Bash(ll-adapt-agents-for-codex:*)"', "FEAT-1526"),
    ("skills/configure/areas.md", "ll-generate-skill-descriptions", "ENH-1395"),
    # REMOVED (stub ENH-1982): ("skills/init/SKILL.md", "LL_HOST_CLI", "BUG-1890"),
    # REMOVED (stub ENH-1982): ("skills/init/SKILL.md", "LL_HOOK_HOST", "BUG-1890"),
    # REMOVED (stub ENH-1982): ("skills/init/SKILL.md", "claude-code", "BUG-1890"),
    ("skills/configure/show-output.md", "rate_limits:", "circuit-breaker"),
    ("skills/configure/show-output.md", "circuit_breaker_enabled", "circuit-breaker"),
    ("skills/configure/show-output.md", "circuit_breaker_path", "circuit-breaker"),
    ("skills/configure/areas.md", "circuit_breaker_enabled", "circuit-breaker"),
    ("skills/configure/areas.md", "circuit_breaker_path", "circuit-breaker"),
    # REMOVED (stub ENH-1982): ("skills/init/SKILL.md", "product.enabled: true", "ENH-1401"),
    # REMOVED (stub ENH-1982): ("skills/init/SKILL.md", "ll-goals-template.md", "ENH-1401"),
    # REMOVED (stub ENH-1982): ("skills/init/SKILL.md", ".ll/ll-goals.md", "ENH-1401"),
    # REMOVED (stub ENH-1982): ("skills/init/SKILL.md", "already exist", "ENH-1401"),
    # REMOVED (stub ENH-1982): ("skills/init/SKILL.md", "[write]  .ll/ll-goals.md", "ENH-1401"),
    # REMOVED (stub ENH-1982): ("skills/init/SKILL.md", "Created: .ll/ll-goals.md", "ENH-1401"),
    # REMOVED (stale/false-positive): ("skills/init/SKILL.md", "TOTAL = 8", "ENH-1401"),
    # REMOVED (stub ENH-1982): ("skills/init/SKILL.md", "Round 4", "ENH-1401"),
    # REMOVED (stub ENH-1982): ("skills/init/interactive.md", "TOTAL = 8", "ENH-1401"),
    # REMOVED (stub ENH-1982): ("skills/init/interactive.md", "Round 4", "ENH-1401"),
    # REMOVED (stub ENH-1982): ("skills/init/interactive.md", "Yes, enable product analysis", "ENH-1401"),
    # REMOVED (stub ENH-1982): ("skills/init/interactive.md", "No, skip", "ENH-1401"),
    # REMOVED (stub ENH-1982): ("skills/init/interactive.md", "PRODUCT_ENABLED=true", "ENH-1401"),
    # REMOVED (stale): ("skills/init/interactive.md", "status\" in row.lower() or \"frontmatter\" in row.lower()", "ENH-1421"),
    # REMOVED (stub ENH-1982): ("skills/init/interactive.md", "scan-product works without it", "ENH-1443"),
    ("skills/configure/areas.md", "ll-history-context", "ENH-1846"),
    # REMOVED (stale/false-positive): ("skills/configure/areas.md", "Bash(ll-history-context:*)", "ENH-1846"),
    # REMOVED (stub ENH-1982): ("skills/init/SKILL.md", "Bash(ll-history-context:*)", "ENH-1846"),
    # REMOVED (stale/false-positive): ("skills/init/SKILL.md", "32 typed CLI tools", "ENH-1846"),
    # REMOVED (stale/false-positive): ("skills/configure/SKILL.md", "## Area: history", "ENH-1916"),
    # REMOVED (stale/false-positive): ("skills/configure/SKILL.md", "session_digest.enabled", "ENH-1916"),
    # REMOVED (stale/false-positive): ("skills/configure/areas.md", "## history --show", "ENH-1916"),
    ("skills/configure/areas.md", "history.velocity_window", "ENH-1916"),
    # REMOVED (stale/false-positive): ("skills/configure/show-output.md", "### `history`", "ENH-1916"),
    ("skills/configure/show-output.md", "velocity_window", "ENH-1916"),
    ("skills/configure/areas.md", "adapters/claude-code/precompact.sh", "FEAT-1457"),
    ("skills/configure/areas.md", "adapters/claude-code/precompact-handoff.sh", "FEAT-1158"),
    ("skills/configure/areas.md", "hooks/adapters/", "FEAT-1457"),
    # REMOVED (stub ENH-1982): ("skills/init/SKILL.md", "hooks/adapters/claude-code/", "FEAT-1457"),
    # REMOVED (stale/false-positive): ("skills/init/SKILL.md", "scripts/little_loops/hooks/", "FEAT-1457"),
    # REMOVED (stub ENH-1982): ("skills/init/SKILL.md", "adapters/", "FEAT-1457"),
    ("skills/configure/areas.md", "ll-doctor", "FEAT-1504"),
    # REMOVED (stale/false-positive): ("skills/configure/areas.md", "Bash(ll-doctor:*)", "FEAT-1504"),
    # REMOVED (stub ENH-1982): ("skills/init/SKILL.md", "Bash(ll-doctor:*)", "FEAT-1504"),
    # REMOVED (stub ENH-1982): ("skills/init/SKILL.md", "ll-doctor", "FEAT-1504"),
    ("skills/configure/areas.md", "ll-ctx-stats", "FEAT-1625"),
    # REMOVED (stale/false-positive): ("skills/configure/areas.md", "Bash(ll-ctx-stats:*)", "FEAT-1625"),
    # REMOVED (stub ENH-1982): ("skills/init/SKILL.md", "Bash(ll-ctx-stats:*)", "FEAT-1625"),
    # REMOVED (stub ENH-1982): ("skills/init/SKILL.md", "Bash(ll-create-extension:*)", "FEAT-1045"),
    # REMOVED (stale/false-positive): ("skills/init/SKILL.md", "Authorize all 29", "FEAT-1045"),
    # REMOVED (stub ENH-1982): ("skills/init/SKILL.md", "ll-create-extension", "FEAT-1045"),
    # REMOVED (stale/false-positive): ("skills/configure/areas.md", "32 typed CLI tools", "FEAT-1045"),
    # REMOVED (stale/false-positive): ("skills/configure/areas.md", "Bash(ll-action:*)", "FEAT-1045"),
    # REMOVED (stub ENH-1982): ("skills/init/SKILL.md", "Bash(ll-action:*)", "FEAT-1045"),
    # REMOVED (stale/false-positive): ("skills/init/SKILL.md", "action.py", "FEAT-1045"),
    # REMOVED (stub ENH-1982): ("skills/init/SKILL.md", "ll-harness", "FEAT-1045"),
    # REMOVED (stale/false-positive): ("skills/configure/areas.md", "Bash(ll-harness:*)", "FEAT-1045"),
    # REMOVED (stub ENH-1982): ("skills/init/SKILL.md", "Bash(ll-harness:*)", "FEAT-1045"),
    # REMOVED (stale/false-positive): ("skills/init/SKILL.md", "decisions.yaml", "FEAT-1045"),
    ("skills/configure/areas.md", "Bash(python3:*)", "ENH-1836"),
    # REMOVED (stub ENH-1982): ("skills/init/interactive.md", "analytics", "ENH-1884"),
    # REMOVED (stale/false-positive): ("skills/init/interactive.md", "9–10 rounds", "ENH-1884"),
    # REMOVED (stale/false-positive): ("skills/configure/SKILL.md", "## Area: analytics", "ENH-1884"),
    # REMOVED (stale/false-positive): ("skills/configure/areas.md", "## analytics --show", "ENH-1884"),
    # REMOVED (stale/false-positive): ("skills/configure/SKILL.md", "## Area: learning_tests", "FEAT-1743"),
    # REMOVED (stale/false-positive): ("skills/configure/areas.md", "## learning_tests --show", "FEAT-1743"),
    # REMOVED (stub ENH-1982): ("skills/init/interactive.md", "learning_tests", "FEAT-1743"),
    # REMOVED (stub ENH-1982): ("skills/init/interactive.md", "design_tokens", "FEAT-1756"),
    # REMOVED (stale/false-positive): ("skills/configure/SKILL.md", "## Area: design_tokens", "FEAT-1757"),
    # REMOVED (stale/false-positive): ("skills/configure/areas.md", "## design_tokens --show", "FEAT-1757"),
    # REMOVED (stub ENH-1982): ("skills/init/SKILL.md", "Bash(ll-logs:*)", "ll-logs"),
    # REMOVED (stub ENH-1982): ("skills/init/SKILL.md", "ll-logs", "ll-logs"),
    ("skills/configure/areas.md", "ll-logs", "ll-logs"),
    # REMOVED (stub ENH-1982): ("skills/init/interactive.md", "Round 9.5", "ENH-2040"),
    # REMOVED (stub ENH-1982): ("skills/init/interactive.md", "Session Digest", "ENH-2040"),
    # REMOVED (stub ENH-1982): ("skills/init/interactive.md", "SESSION_DIGEST_ENABLED", "ENH-2040"),
    # REMOVED (stub ENH-1982): ("skills/init/SKILL.md", "session_digest", "ENH-2040"),
    ("skills/configure/show-output.md", "use_feature_branches", "ENH-2174"),
    ("skills/configure/areas.md", "use_feature_branches", "ENH-2174"),
    ("skills/configure/SKILL.md", "feature branches", "ENH-2174"),
    ("skills/configure/show-output.md", "epic_branches", "FEAT-2450"),
    ("skills/configure/areas.md", "epic_branches", "FEAT-2450"),
    ("skills/configure/SKILL.md", "epic branches", "FEAT-2450"),
]


@pytest.mark.parametrize("doc_rel, needle, issue_id", DOC_STRINGS_PRESENT)
def test_string_present_in_doc(
    project_root: Path, doc_rel: str, needle: str, issue_id: str
) -> None:
    """Verify that expected strings appear in documentation files."""
    content = (project_root / doc_rel).read_text()
    assert needle in content, "[{issue_id}] {doc_rel} must contain: {needle!r}"


# -- 12 string-absence assertions --------------------------------

DOC_STRINGS_ABSENT: list[tuple[str, str, str]] = [
    # (doc_path, forbidden_string, issue_id)
    # REMOVED (stub ENH-1982): ("skills/init/SKILL.md", "Resolve `${CLAUDE_PLUGIN_ROOT}` by substituting", "BUG-863"),
    (
        "skills/configure/areas.md",
        "Run `bash -c 'pwd'` to get the absolute plugin root path",
        "BUG-863",
    ),
    ("skills/configure/areas.md", "install — add ll- hooks to a settings file", "BUG-863"),
    # REMOVED (stub ENH-1982): ("skills/init/SKILL.md", "Strip the `_meta`, `$schema`, and `product` sections", "ENH-1401"),
    # REMOVED (stub ENH-1982): ("skills/init/interactive.md", "create `ll-goals.md` by copying `templates/ll-goals-template.md`", "ENH-1401"),
    # REMOVED (stub ENH-1982): ("skills/init/SKILL.md", "completed_dir", "ENH-1421"),
    # REMOVED (stub ENH-1982): ("skills/init/SKILL.md", "deferred_dir", "ENH-1421"),
    # REMOVED (stub ENH-1982): ("skills/init/interactive.md", "completed_dir", "ENH-1421"),
    # REMOVED (stub ENH-1982): ("skills/init/interactive.md", "deferred_dir", "ENH-1421"),
    # REMOVED (stub ENH-1982): ("skills/init/interactive.md", "enables /ll:scan-product", "ENH-1443"),
    (
        "skills/init/SKILL.md",
        "Run `bash -c 'pwd'` to get the absolute plugin root path",
        "FEAT-1045",
    ),
    ("skills/configure/areas.md", "installs/shows/validates", "FEAT-1045"),
]


@pytest.mark.parametrize("doc_rel, needle, issue_id", DOC_STRINGS_ABSENT)
def test_string_absent_from_doc(
    project_root: Path, doc_rel: str, needle: str, issue_id: str
) -> None:
    """Verify that stale/forbidden strings do NOT appear in documentation files."""
    content = (project_root / doc_rel).read_text()
    assert needle not in content, "[{issue_id}] {doc_rel} must NOT contain: {needle!r}"


# -- 4 minimum-count assertions ---------------------------------

DOC_COUNT_MIN: list[tuple[str, str, int, str]] = [
    # (doc_path, needle, min_count, issue_id)
    # REMOVED (stub ENH-1982): ("skills/init/SKILL.md", "ll-create-extension", 3, "FEAT-1049"),
    # REMOVED (stub ENH-1982): ("skills/init/SKILL.md", "ll-action", 3, "FEAT-1229"),
    # REMOVED (stub ENH-1982): ("skills/init/SKILL.md", "ll-harness", 3, "FEAT-1689"),
    # REMOVED (stub ENH-1982): ("skills/init/SKILL.md", "ll-adapt-agents-for-codex", 3, "FEAT-1526"),
]


@pytest.mark.parametrize("doc_rel, needle, min_count, issue_id", DOC_COUNT_MIN)
def test_string_min_occurrences(
    project_root: Path, doc_rel: str, needle: str, min_count: int, issue_id: str
) -> None:
    """Verify that strings appear at least N times in documentation files."""
    content = (project_root / doc_rel).read_text()
    actual = content.count(needle)
    assert actual >= min_count, (
        "[{issue_id}] {doc_rel} must contain {needle!r} at least {min_count} times, found {actual}"
    )


# -- 2 file-existence assertions -----------------------------------

DOC_FILES_MUST_EXIST: list[tuple[str, str]] = [
    # (file_path, issue_id)
    ("skills/init/SKILL.md", "ENH-1401"),
    # REMOVED (stub ENH-1982): ("skills/init/interactive.md", "ENH-1401"),
]


@pytest.mark.parametrize("doc_rel, issue_id", DOC_FILES_MUST_EXIST)
def test_file_exists(project_root: Path, doc_rel: str, issue_id: str) -> None:
    """Verify that expected documentation files exist."""
    assert (project_root / doc_rel).exists(), "[{issue_id}] File must exist: {doc_rel}"
