"""Tests for ll-adapt-agents-for-codex CLI."""

from __future__ import annotations

import sys
from pathlib import Path
from unittest.mock import patch

from little_loops.cli.adapt_agents_for_codex import (
    _emit_agent_toml,
    _extract_agent_frontmatter,
    _extract_short_desc,
    _process_agents,
    main_adapt_agents_for_codex,
)

_MARKER = "# generated by ll-adapt"


def _make_agent(
    tmp_path: Path,
    name: str,
    description: str = "Use when user asks for stuff.",
    model: str = "sonnet",
    body: str = "Agent instructions.",
) -> Path:
    agents_dir = tmp_path / "agents"
    agents_dir.mkdir(parents=True, exist_ok=True)
    agent_md = agents_dir / f"{name}.md"
    agent_md.write_text(
        f"---\nname: {name}\ndescription: |\n  {description}\nmodel: {model}\n"
        f'tools: ["Read"]\n---\n\n{body}'
    )
    return agent_md


def _make_agent_block_scalar(tmp_path: Path, name: str) -> Path:
    agents_dir = tmp_path / "agents"
    agents_dir.mkdir(parents=True, exist_ok=True)
    agent_md = agents_dir / f"{name}.md"
    agent_md.write_text(
        "---\nname: my-agent\ndescription: |\n  Use when asked to do something.\n"
        "  More context here.\n\n  Trigger keywords: foo, bar\nmodel: sonnet\n"
        "---\n\n# My Agent\n"
    )
    return agent_md


# =============================================================================
# _extract_agent_frontmatter / _extract_short_desc
# =============================================================================


class TestExtractAgentFrontmatter:
    def test_returns_dict_with_known_fields(self) -> None:
        text = "---\nname: my-agent\ndescription: Use when stuff.\nmodel: sonnet\n---\n# Body"
        fm = _extract_agent_frontmatter(text)
        assert fm is not None
        assert fm["name"] == "my-agent"
        assert fm["model"] == "sonnet"

    def test_no_frontmatter_returns_none(self) -> None:
        assert _extract_agent_frontmatter("# No frontmatter") is None

    def test_unclosed_frontmatter_returns_none(self) -> None:
        assert _extract_agent_frontmatter("---\nname: x\n") is None

    def test_single_line_description(self) -> None:
        text = "---\ndescription: Use when user asks for stuff.\n---\n# Body"
        assert _extract_short_desc(text) == "Use when user asks for stuff."

    def test_block_scalar_returns_first_line(self) -> None:
        text = (
            "---\ndescription: |\n  Use when asked to do something.\n  More context.\n---\n# Body"
        )
        assert _extract_short_desc(text) == "Use when asked to do something."

    def test_truncates_to_80_chars(self) -> None:
        long_desc = "A" * 100
        text = f"---\ndescription: {long_desc}\n---\n# Body"
        assert len(_extract_short_desc(text)) == 80

    def test_no_frontmatter_returns_empty(self) -> None:
        assert _extract_short_desc("# No frontmatter") == ""

    def test_no_description_field_returns_empty(self) -> None:
        text = "---\nname: my-agent\n---\n# Body"
        assert _extract_short_desc(text) == ""


# =============================================================================
# _emit_agent_toml
# =============================================================================


class TestEmitAgentToml:
    def test_starts_with_marker_comment(self) -> None:
        result = _emit_agent_toml("my-agent", "Short desc.", "sonnet", "Body text.")
        assert result.startswith(_MARKER + "\n")

    def test_contains_name_field(self) -> None:
        result = _emit_agent_toml("my-agent", "Short desc.", "sonnet", "Body text.")
        assert 'name = "my-agent"' in result

    def test_contains_description_field(self) -> None:
        result = _emit_agent_toml("my-agent", "Short desc.", "sonnet", "Body text.")
        assert 'description = "Short desc."' in result

    def test_contains_model_field(self) -> None:
        result = _emit_agent_toml("my-agent", "Short desc.", "opus", "Body text.")
        assert 'model = "opus"' in result

    def test_contains_developer_instructions(self) -> None:
        result = _emit_agent_toml("my-agent", "Short desc.", "sonnet", "Body content here.")
        assert 'developer_instructions = """' in result
        assert "Body content here." in result

    def test_escapes_triple_quotes_in_body(self) -> None:
        body = 'Some """quoted""" text.'
        result = _emit_agent_toml("my-agent", "Short desc.", "sonnet", body)
        assert '"""quoted"""' not in result.split('developer_instructions = """')[1].rstrip('"\n')

    def test_escapes_double_quotes_in_description(self) -> None:
        result = _emit_agent_toml("my-agent", 'Say "hello".', "sonnet", "Body.")
        assert r'description = "Say \"hello\"."' in result

    def test_body_ends_with_closing_triple_quote(self) -> None:
        result = _emit_agent_toml("my-agent", "Short desc.", "sonnet", "Body.")
        assert result.endswith('"""\n')


# =============================================================================
# _process_agents
# =============================================================================


class TestProcessAgents:
    def test_dry_run_does_not_write_files(self, tmp_path: Path) -> None:
        _make_agent(tmp_path, "my-agent")
        codex_dir = tmp_path / ".codex" / "agents"

        adapted, skipped, errors = _process_agents(
            tmp_path / "agents", codex_dir, apply=False, quiet=True, only=None
        )

        assert adapted == 1
        assert skipped == 0
        assert errors == 0
        assert not codex_dir.exists()

    def test_apply_writes_toml_file(self, tmp_path: Path) -> None:
        _make_agent(tmp_path, "my-agent")
        codex_dir = tmp_path / ".codex" / "agents"

        _process_agents(tmp_path / "agents", codex_dir, apply=True, quiet=True, only=None)

        assert (codex_dir / "my-agent.toml").exists()

    def test_toml_contains_marker_comment(self, tmp_path: Path) -> None:
        _make_agent(tmp_path, "my-agent")
        codex_dir = tmp_path / ".codex" / "agents"
        _process_agents(tmp_path / "agents", codex_dir, apply=True, quiet=True, only=None)
        content = (codex_dir / "my-agent.toml").read_text()
        assert content.startswith(_MARKER)

    def test_toml_contains_name(self, tmp_path: Path) -> None:
        _make_agent(tmp_path, "my-agent")
        codex_dir = tmp_path / ".codex" / "agents"
        _process_agents(tmp_path / "agents", codex_dir, apply=True, quiet=True, only=None)
        content = (codex_dir / "my-agent.toml").read_text()
        assert 'name = "my-agent"' in content

    def test_toml_contains_description(self, tmp_path: Path) -> None:
        _make_agent(tmp_path, "my-agent", description="Use when stuff.")
        codex_dir = tmp_path / ".codex" / "agents"
        _process_agents(tmp_path / "agents", codex_dir, apply=True, quiet=True, only=None)
        content = (codex_dir / "my-agent.toml").read_text()
        assert 'description = "Use when stuff."' in content

    def test_toml_contains_model(self, tmp_path: Path) -> None:
        _make_agent(tmp_path, "my-agent", model="opus")
        codex_dir = tmp_path / ".codex" / "agents"
        _process_agents(tmp_path / "agents", codex_dir, apply=True, quiet=True, only=None)
        content = (codex_dir / "my-agent.toml").read_text()
        assert 'model = "opus"' in content

    def test_skips_agent_without_description(self, tmp_path: Path) -> None:
        agents_dir = tmp_path / "agents"
        agents_dir.mkdir(parents=True)
        (agents_dir / "no-desc.md").write_text("---\nname: no-desc\nmodel: sonnet\n---\n# Body\n")
        codex_dir = tmp_path / ".codex" / "agents"

        adapted, skipped, errors = _process_agents(
            agents_dir, codex_dir, apply=False, quiet=True, only=None
        )
        assert adapted == 0
        assert skipped == 1
        assert errors == 0

    def test_only_filter_restricts_to_single_agent(self, tmp_path: Path) -> None:
        for name in ["agent-a", "agent-b", "agent-c"]:
            _make_agent(tmp_path, name, description=f"Use for {name}.")
        codex_dir = tmp_path / ".codex" / "agents"

        adapted, skipped, _ = _process_agents(
            tmp_path / "agents", codex_dir, apply=True, quiet=True, only="agent-b"
        )

        assert adapted == 1
        assert skipped == 0
        assert (codex_dir / "agent-b.toml").exists()
        assert not (codex_dir / "agent-a.toml").exists()
        assert not (codex_dir / "agent-c.toml").exists()

    def test_multiple_agents_all_adapted(self, tmp_path: Path) -> None:
        for name in ["agent-a", "agent-b", "agent-c"]:
            _make_agent(tmp_path, name, description=f"Use for {name}.")
        codex_dir = tmp_path / ".codex" / "agents"

        adapted, skipped, errors = _process_agents(
            tmp_path / "agents", codex_dir, apply=True, quiet=True, only=None
        )

        assert adapted == 3
        assert skipped == 0
        assert errors == 0
        for name in ["agent-a", "agent-b", "agent-c"]:
            assert (codex_dir / f"{name}.toml").exists()

    def test_handles_block_scalar_description(self, tmp_path: Path) -> None:
        _make_agent_block_scalar(tmp_path, "block-agent")
        codex_dir = tmp_path / ".codex" / "agents"
        adapted, _, errors = _process_agents(
            tmp_path / "agents", codex_dir, apply=True, quiet=True, only=None
        )
        assert adapted == 1
        assert errors == 0
        content = (codex_dir / "block-agent.toml").read_text()
        assert 'description = "Use when asked to do something."' in content

    def test_errors_count_incremented_on_unreadable_file(self, tmp_path: Path) -> None:
        _make_agent(tmp_path, "ghost-agent")
        ghost_md = tmp_path / "agents" / "ghost-agent.md"
        codex_dir = tmp_path / ".codex" / "agents"

        import unittest.mock as mock
        from typing import Any

        original_read = Path.read_text

        def raise_on_ghost(self: Path, **kwargs: Any) -> str:
            if self == ghost_md:
                raise OSError("permission denied")
            return original_read(self, **kwargs)

        with mock.patch.object(Path, "read_text", raise_on_ghost):
            _, _, errors = _process_agents(
                tmp_path / "agents", codex_dir, apply=False, quiet=True, only=None
            )

        assert errors == 1


# =============================================================================
# main_adapt_agents_for_codex — entry-point
# =============================================================================


class TestMainAdaptAgentsForCodex:
    def test_dry_run_returns_zero_on_success(self, tmp_path: Path) -> None:
        _make_agent(tmp_path, "my-agent")

        with (
            patch.object(sys, "argv", ["ll-adapt-agents-for-codex", "--quiet"]),
            patch(
                "little_loops.cli.adapt_agents_for_codex._find_plugin_root",
                return_value=tmp_path,
            ),
        ):
            result = main_adapt_agents_for_codex()

        assert result == 0

    def test_missing_agents_dir_returns_one(self, tmp_path: Path) -> None:
        with (
            patch.object(sys, "argv", ["ll-adapt-agents-for-codex"]),
            patch(
                "little_loops.cli.adapt_agents_for_codex._find_plugin_root",
                return_value=tmp_path,
            ),
        ):
            result = main_adapt_agents_for_codex()

        assert result == 1

    def test_apply_flag_writes_files(self, tmp_path: Path) -> None:
        _make_agent(tmp_path, "my-agent")

        with (
            patch.object(sys, "argv", ["ll-adapt-agents-for-codex", "--apply", "--quiet"]),
            patch(
                "little_loops.cli.adapt_agents_for_codex._find_plugin_root",
                return_value=tmp_path,
            ),
        ):
            result = main_adapt_agents_for_codex()

        assert result == 0
        assert (tmp_path / ".codex" / "agents" / "my-agent.toml").exists()

    def test_only_flag_restricts_to_single_agent(self, tmp_path: Path) -> None:
        for name in ["agent-a", "agent-b"]:
            _make_agent(tmp_path, name, description=f"Use for {name}.")

        with (
            patch.object(
                sys,
                "argv",
                ["ll-adapt-agents-for-codex", "--apply", "--only", "agent-a", "--quiet"],
            ),
            patch(
                "little_loops.cli.adapt_agents_for_codex._find_plugin_root",
                return_value=tmp_path,
            ),
        ):
            result = main_adapt_agents_for_codex()

        assert result == 0
        assert (tmp_path / ".codex" / "agents" / "agent-a.toml").exists()
        assert not (tmp_path / ".codex" / "agents" / "agent-b.toml").exists()


# =============================================================================
# Integration guard: real agents (post-apply validation)
# =============================================================================


class TestRealAgentsIntegrationGuard:
    """After ll-adapt-agents-for-codex --apply, all real .codex/agents/*.toml must exist."""

    def test_all_real_agents_have_toml_files(self) -> None:
        agents_dir = Path(__file__).parent.parent.parent / "agents"
        codex_agents_dir = Path(__file__).parent.parent.parent / ".codex" / "agents"
        if not codex_agents_dir.exists():
            return
        for agent_md in sorted(agents_dir.glob("*.md")):
            agent_name = agent_md.stem
            out_toml = codex_agents_dir / f"{agent_name}.toml"
            assert out_toml.exists(), (
                f".codex/agents/{agent_name}.toml missing. Run: ll-adapt-agents-for-codex --apply"
            )

    def test_all_real_toml_files_have_marker(self) -> None:
        codex_agents_dir = Path(__file__).parent.parent.parent / ".codex" / "agents"
        if not codex_agents_dir.exists():
            return
        for toml_path in sorted(codex_agents_dir.glob("*.toml")):
            content = toml_path.read_text()
            assert content.startswith(_MARKER), (
                f".codex/agents/{toml_path.name}: missing marker comment on first line"
            )

    def test_all_real_toml_files_have_required_fields(self) -> None:
        codex_agents_dir = Path(__file__).parent.parent.parent / ".codex" / "agents"
        if not codex_agents_dir.exists():
            return
        for toml_path in sorted(codex_agents_dir.glob("*.toml")):
            content = toml_path.read_text()
            assert 'name = "' in content, f"{toml_path.name}: missing name field"
            assert 'description = "' in content, f"{toml_path.name}: missing description field"
            assert 'model = "' in content, f"{toml_path.name}: missing model field"
            assert 'developer_instructions = """' in content, (
                f"{toml_path.name}: missing developer_instructions field"
            )


# =============================================================================
# Idempotency
# =============================================================================


class TestIdempotency:
    def test_rerun_with_apply_skips_unchanged(self, tmp_path: Path) -> None:
        _make_agent(tmp_path, "my-agent")
        codex_dir = tmp_path / ".codex" / "agents"

        # First run: write
        adapted1, skipped1, _ = _process_agents(
            tmp_path / "agents", codex_dir, apply=True, quiet=True, only=None
        )
        assert adapted1 == 1
        assert skipped1 == 0

        # Second run: should skip (identical content)
        adapted2, skipped2, errors2 = _process_agents(
            tmp_path / "agents", codex_dir, apply=True, quiet=True, only=None
        )
        assert adapted2 == 0
        assert skipped2 == 1
        assert errors2 == 0

    def test_rerun_produces_no_diff(self, tmp_path: Path) -> None:
        _make_agent(tmp_path, "my-agent")
        codex_dir = tmp_path / ".codex" / "agents"
        toml_path = codex_dir / "my-agent.toml"

        _process_agents(tmp_path / "agents", codex_dir, apply=True, quiet=True, only=None)
        first_content = toml_path.read_text()

        _process_agents(tmp_path / "agents", codex_dir, apply=True, quiet=True, only=None)
        assert toml_path.read_text() == first_content

    def test_changed_source_triggers_rewrite(self, tmp_path: Path) -> None:
        agent_md = _make_agent(tmp_path, "my-agent", description="Original description.")
        codex_dir = tmp_path / ".codex" / "agents"
        _process_agents(tmp_path / "agents", codex_dir, apply=True, quiet=True, only=None)

        # Update source
        agent_md.write_text(
            "---\nname: my-agent\ndescription: |\n  Updated description.\nmodel: sonnet\n"
            'tools: ["Read"]\n---\n\nNew body.'
        )

        adapted, skipped, _ = _process_agents(
            tmp_path / "agents", codex_dir, apply=True, quiet=True, only=None
        )
        assert adapted == 1
        assert skipped == 0
        content = (codex_dir / "my-agent.toml").read_text()
        assert 'description = "Updated description."' in content


# =============================================================================
# Marker preservation (user-authored file protection)
# =============================================================================


class TestMarkerPreservation:
    def test_user_authored_file_not_overwritten(self, tmp_path: Path) -> None:
        _make_agent(tmp_path, "my-agent")
        codex_dir = tmp_path / ".codex" / "agents"
        codex_dir.mkdir(parents=True)

        user_content = "# user-authored content\nname = 'my-agent'\n"
        (codex_dir / "my-agent.toml").write_text(user_content)

        adapted, skipped, errors = _process_agents(
            tmp_path / "agents", codex_dir, apply=True, quiet=True, only=None
        )

        assert adapted == 0
        assert skipped == 1
        assert errors == 0
        assert (codex_dir / "my-agent.toml").read_text() == user_content

    def test_generated_file_can_be_updated(self, tmp_path: Path) -> None:
        agent_md = _make_agent(tmp_path, "my-agent", description="Original.")
        codex_dir = tmp_path / ".codex" / "agents"
        _process_agents(tmp_path / "agents", codex_dir, apply=True, quiet=True, only=None)

        # Simulate stale generated file by updating source
        agent_md.write_text(
            "---\nname: my-agent\ndescription: |\n  New desc.\nmodel: sonnet\n"
            'tools: ["Read"]\n---\n\nNew body.'
        )

        adapted, skipped, _ = _process_agents(
            tmp_path / "agents", codex_dir, apply=True, quiet=True, only=None
        )
        assert adapted == 1
        assert skipped == 0
        content = (codex_dir / "my-agent.toml").read_text()
        assert content.startswith(_MARKER)
        assert 'description = "New desc."' in content
