"""Consolidated doc-wiring tests — Individual skill and command file documentation wiring.

Generated by ENH-1963: Audit and Consolidate Doc-Wiring Tests.
All original assertions from 31 source files preserved as parametrized cases.
"""

from __future__ import annotations

from pathlib import Path

import pytest

# =============================================================================
# Shared paths (resolved from project_root fixture)
# =============================================================================


# -- 149 string-presence assertions -------------------------------

DOC_STRINGS_PRESENT: list[tuple[str, str, str]] = [
    # (doc_path, expected_string, issue_id)
    ("skills/capture-issue/SKILL.md", "**Status enum**:", "ENH-1550"),
    ("skills/format-issue/SKILL.md", "**Status enum**:", "ENH-1550"),
    ("skills/manage-issue/SKILL.md", "**Status enum**:", "ENH-1550"),
    ("commands/ready-issue.md", "**Status enum**:", "ENH-1550"),
    ("commands/refine-issue.md", "**Status enum**:", "ENH-1550"),
    ("commands/create-sprint.md", "ll-issues list --json", "BUG-1649"),
    ("skills/create-loop/reference.md", "circuit_breaker_enabled", "circuit-breaker"),
    ("skills/create-loop/reference.md", "circuit_breaker_path", "circuit-breaker"),
    ("skills/create-loop/loop-types.md", "circuit_breaker_enabled", "circuit-breaker"),
    ("skills/create-loop/loop-types.md", "circuit_breaker_path", "circuit-breaker"),
    ("commands/align-issues.md", "--issues", "ENH-1362"),
    ("commands/align-issues.md", "arguments:", "ENH-1362"),
    ("commands/align-issues.md", "name: issues", "ENH-1362"),
    ("commands/align-issues.md", "Bash(ll-issues:*)", "ENH-1362"),
    ("commands/align-issues.md", 'ISSUES_ARG="${issues:-}', "ENH-1362"),
    ("commands/align-issues.md", "ll-issues path", "ENH-1362"),
    ("commands/align-issues.md", "not found (skipping)", "ENH-1362"),
    ("commands/align-issues.md", "None of the specified issue IDs", "ENH-1362"),
    ("commands/tradeoff-review-issues.md", 'argument-hint: "[issue-ids]', "ENH-1363"),
    ("commands/tradeoff-review-issues.md", "arguments:", "ENH-1363"),
    ("commands/tradeoff-review-issues.md", "name: issues", "ENH-1363"),
    ("commands/tradeoff-review-issues.md", "Bash(ll-issues:*)", "ENH-1363"),
    ("commands/tradeoff-review-issues.md", "ll-issues path", "ENH-1363"),
    ("commands/tradeoff-review-issues.md", "not found (skipping)", "ENH-1363"),
    ("commands/scan-product.md", "sole responsible party for deduplication", "ENH-1403"),
    ("skills/product-analyzer/SKILL.md", "## Examples", "ENH-1404"),
    ("commands/manage-release.md", "status: done", "ENH-1421"),
    ("commands/manage-release.md", "completed_at", "ENH-1421"),
    ("skills/manage-issue/SKILL.md", "status: done", "ENH-1421"),
    ("skills/manage-issue/SKILL.md", "status:", "ENH-1421"),
    # REMOVED (self-referential — old doc-wiring file no longer exists after ENH-1963 consolidation):
    # ("scripts/tests/test_feat1172_doc_wiring.py", "status\" in row.lower() or \"frontmatter\" in row.lower()", "ENH-1421"),
    ("skills/issue-size-review/SKILL.md", "parent: [PARENT-ID]", "ENH-1433"),
    # REMOVED (stale/false-positive): ("skills/issue-size-review/SKILL.md", "parent: EPIC-NNN", "ENH-1433"),
    ("skills/confidence-check/SKILL.md", "parent: EPIC-NNN", "ENH-1433"),
    ("skills/manage-issue/SKILL.md", "parent: EPIC-NNN", "ENH-1433"),
    # REMOVED (stale/false-positive): ("skills/manage-issue/SKILL.md", "| `parent`", "ENH-1433"),
    ("skills/product-analyzer/SKILL.md", "goals_content_missing", "ENH-1442"),
    ("commands/scan-product.md", "config.product.goals_discovery.max_files", "ENH-1442"),
    ("commands/scan-product.md", "config.product.goals_discovery.required_files", "ENH-1442"),
    ("mkdocs.yml", "Codex CLI:", "ENH-1495"),
    ("mkdocs.yml", "codex/README.md", "ENH-1495"),
    ("mkdocs.yml", "codex/getting-started.md", "ENH-1495"),
    ("mkdocs.yml", "codex/usage.md", "ENH-1495"),
    ("docs/index.md", "codex/README.md", "ENH-1495"),
    ("docs/index.md", "codex/getting-started.md", "ENH-1495"),
    ("docs/index.md", "codex/usage.md", "ENH-1495"),
    ("docs/index.md", "codex/", "ENH-1495"),
    (
        "docs/reference/loops.md",
        ".ll/runs/harness-optimize/<run-id>/states/<state>/trajectory.jsonl",
        "ENH-1557",
    ),
    ("docs/reference/loops.md", "STATE_NAME", "ENH-1557"),
    ("docs/reference/loops.md", "EXAMPLES_FILE", "ENH-1557"),
    ("docs/reference/loops.md", "dequeue_state", "ENH-1557"),
    ("docs/reference/loops.md", "check_queue", "ENH-1557"),
    ("skills/create-loop/loop-types.md", "timeout: 1500", "ENH-1639"),
    ("skills/create-loop/loop-types.md", "MCP calls", "ENH-1639"),
    # REMOVED (stale/false-positive): ("skills/create-loop/loop-types.md", "MCP tool calls", "ENH-1639"),
    ("docs/generalized-fsm-loop.md", "MCP tool calls", "ENH-1639"),
    ("docs/generalized-fsm-loop.md", "1500", "ENH-1639"),
    ("docs/generalized-fsm-loop.md", "default_timeout", "ENH-1639"),
    ("docs/generalized-fsm-loop.md", "MCP", "ENH-1639"),
    ("docs/guides/AUTOMATIC_HARNESSING_GUIDE.md", "MCP", "ENH-1639"),
    ("docs/guides/AUTOMATIC_HARNESSING_GUIDE.md", "1500", "ENH-1639"),
    ("config-schema.json", "issue.completed", "ENH-1734"),
    ("config-schema.json", "AutoManager", "ENH-1734"),
    ("commands/review-sprint.md", "3f: EPIC Context", "ENH-1859"),
    ("commands/review-sprint.md", "ll-sprint show EPIC-", "ENH-1859"),
    ("commands/review-sprint.md", "ll-deps tree", "ENH-1859"),
    ("commands/review-sprint.md", "ll-sprint edit", "ENH-1859"),
    ("commands/review-sprint.md", "5d", "ENH-1859"),
    ("commands/review-sprint.md", "EPIC", "ENH-1859"),
    ("skills/map-dependencies/SKILL.md", "ll-deps tree --epic", "ENH-1866"),
    ("skills/create-loop/SKILL.md", "Orch: Router (dynamic dispatch)", "ENH-1912"),
    ("skills/create-loop/SKILL.md", "route", "ENH-1912"),
    ("skills/create-loop/SKILL.md", "orch-router", "ENH-1912"),
    # REMOVED (stale/false-positive): ("skills/create-loop/SKILL.md", "Route / compose / supervise", "ENH-1912"),
    # REMOVED (stale): ("skills/create-loop/SKILL.md", "For \"Route / compose / supervise other loops", "ENH-1912"),
    ("skills/create-loop/templates.md", "Route / compose / supervise", "ENH-1912"),
    ("skills/create-loop/templates.md", 'For "Route / compose / supervise other loops', "ENH-1912"),
    ("skills/create-loop/templates.md", "loop-router", "ENH-1912"),
    # REMOVED (stale/false-positive): ("skills/create-loop/templates.md", "## Orchestration Loops", "ENH-1912"),
    # REMOVED (stale/false-positive): ("skills/create-loop/templates.md", "Orch Router Questions", "ENH-1912"),
    ("skills/create-loop/loop-types.md", "## Orchestration Loops", "ENH-1912"),
    ("skills/create-loop/loop-types.md", "Orch Router Questions", "ENH-1912"),
    ("skills/create-loop/loop-types.md", "captured.chosen.output", "ENH-1912"),
    ("skills/create-loop/loop-types.md", "EPIC-1811", "ENH-1912"),
    ("skills/create-loop/loop-types.md", "Orchestration", "ENH-1912"),
    (".issues/epics/P2-EPIC-1707-history-db-as-agent-context-layer.md", "ENH-1909", "ENH-1916"),
    (".issues/epics/P2-EPIC-1707-history-db-as-agent-context-layer.md", "ENH-1911", "ENH-1916"),
    (".issues/epics/P2-EPIC-1707-history-db-as-agent-context-layer.md", "ENH-1913", "ENH-1916"),
    (".issues/epics/P2-EPIC-1707-history-db-as-agent-context-layer.md", "ENH-1914", "ENH-1916"),
    (".issues/epics/P2-EPIC-1707-history-db-as-agent-context-layer.md", "ENH-1916", "ENH-1916"),
    # REMOVED (stale/false-positive): (".issues/epics/P2-EPIC-1707-history-db-as-agent-context-layer.md", "| `history` |", "ENH-1916"),
    (".issues/epics/P2-EPIC-1707-history-db-as-agent-context-layer.md", "`history`", "ENH-1916"),
    ("skills/manage-issue/SKILL.md", "completed_at", "FEAT-1172"),
    ("skills/manage-issue/SKILL.md", 'date -u +"%Y-%m-%dT%H:%M:%SZ', "FEAT-1172"),
    ("skills/manage-issue/SKILL.md", "update_frontmatter", "FEAT-1172"),
    ("commands/create-sprint.md", "--for-skill create-sprint", "ENH-1909"),
    ("skills/scope-epic/SKILL.md", "--for-skill scope-epic", "ENH-1909"),
    ("skills/manage-issue/SKILL.md", "--for-skill manage-issue", "ENH-1909"),
    ("skills/review-epic/SKILL.md", "--for-skill review-epic", "ENH-1909"),
    ("skills/explore-api/SKILL.md", "description:", "FEAT-1287"),
    ("skills/explore-api/SKILL.md", "argument-hint:", "FEAT-1287"),
    ("skills/explore-api/SKILL.md", "ll-learning-tests", "FEAT-1287"),
    ("skills/explore-api/SKILL.md", "--assume", "FEAT-1287"),
    # REMOVED (stale/false-positive): ("skills/explore-api/SKILL.md", "63 skills", "FEAT-1287"),
    # REMOVED (stale/false-positive): ("skills/explore-api/SKILL.md", "63 skill definitions", "FEAT-1287"),
    ("skills/capture-issue/SKILL.md", "EPIC", "FEAT-1407"),
    ("skills/capture-issue/SKILL.md", "epics/", "FEAT-1407"),
    ("commands/normalize-issues.md", "EPIC", "FEAT-1407"),
    ("commands/normalize-issues.md", "epics/", "FEAT-1407"),
    ("skills/format-issue/SKILL.md", "EPIC", "FEAT-1407"),
    ("skills/format-issue/SKILL.md", "epics/", "FEAT-1407"),
    ("skills/issue-workflow/SKILL.md", "epics/", "FEAT-1407"),
    ("skills/issue-workflow/SKILL.md", "EPIC", "FEAT-1407"),
    ("scripts/little_loops/cli/create_extension.py", "LLHookIntentExtension", "FEAT-1457"),
    # REMOVED (stale/false-positive): ("scripts/little_loops/cli/create_extension.py", "hooks/adapters/", "FEAT-1457"),
    ("skills/workflow-automation-proposer/SKILL.md", "LLHookIntentExtension", "FEAT-1457"),
    ("skills/workflow-automation-proposer/SKILL.md", "hooks/adapters/", "FEAT-1457"),
    # REMOVED (stale/false-positive): ("skills/workflow-automation-proposer/SKILL.md", "adapters/claude-code/precompact.sh", "FEAT-1457"),
    ("skills/audit-claude-config/SKILL.md", "hooks/adapters/", "FEAT-1457"),
    ("skills/audit-claude-config/SKILL.md", "scripts/little_loops/hooks/", "FEAT-1457"),
    # REMOVED (stale/false-positive): ("skills/audit-claude-config/SKILL.md", "hooks/adapters/claude-code/", "FEAT-1457"),
    ("docs/claude-code/write-a-hook.md", "LLHookEvent", "FEAT-1457"),
    ("docs/claude-code/write-a-hook.md", "LLHookResult", "FEAT-1457"),
    ("docs/claude-code/write-a-hook.md", "LLHookIntentExtension", "FEAT-1457"),
    ("docs/claude-code/write-a-hook.md", "provided_hook_intents", "FEAT-1457"),
    ("docs/claude-code/write-a-hook.md", "ll-create-extension", "FEAT-1457"),
    ("docs/claude-code/write-a-hook.md", "flowchart LR", "FEAT-1457"),
    # REMOVED (stale/false-positive): ("docs/claude-code/write-a-hook.md", "write-a-hook.md", "FEAT-1457"),
    ("docs/claude-code/automate-workflows-with-hooks.md", "flowchart LR", "FEAT-1457"),
    ("docs/claude-code/automate-workflows-with-hooks.md", "write-a-hook.md", "FEAT-1457"),
    # REMOVED (stale/false-positive): ("docs/claude-code/automate-workflows-with-hooks.md", "Claude Code:", "FEAT-1457"),
    # REMOVED (stale/false-positive): ("docs/claude-code/automate-workflows-with-hooks.md", "claude-code/write-a-hook.md", "FEAT-1457"),
    ("mkdocs.yml", "Claude Code:", "FEAT-1457"),
    ("mkdocs.yml", "claude-code/write-a-hook.md", "FEAT-1457"),
    ("mkdocs.yml", "claude-code/hooks-reference.md", "FEAT-1457"),
    ("mkdocs.yml", "claude-code/automate-workflows-with-hooks.md", "FEAT-1457"),
    ("docs/index.md", "claude-code/write-a-hook.md", "FEAT-1457"),
    ("docs/claude-code/hooks-reference.md", "Intent model", "FEAT-1459"),
    ("docs/claude-code/hooks-reference.md", "write-a-hook.md", "FEAT-1459"),
    ("docs/claude-code/hooks-reference.md", "EVENT-SCHEMA.md", "FEAT-1459"),
    ("docs/claude-code/hooks-reference.md", "LLHookEvent", "FEAT-1459"),
    ("docs/claude-code/hooks-reference.md", "LLHookResult", "FEAT-1459"),
    ("docs/claude-code/write-a-hook.md", "EVENT-SCHEMA.md", "FEAT-1459"),
    ("thoughts/research/codex-command-discovery.md", "~/.codex/skills", "FEAT-1483"),
    ("thoughts/research/codex-command-discovery.md", "stable", "FEAT-1483"),
    ("thoughts/research/codex-command-discovery.md", "codex/skills", "FEAT-1483"),
    ("hooks/adapters/codex/README.md", "codex/skills", "FEAT-1483"),
    ("hooks/adapters/codex/README.md", "FEAT-1483", "FEAT-1483"),
    ("agents/loop-specialist.md", "name: loop-specialist", "FEAT-1532"),
    ("agents/loop-specialist.md", "model:", "FEAT-1532"),
    ("agents/loop-specialist.md", "tools:", "FEAT-1532"),
    ("agents/loop-specialist.md", ".loops/diagnostics/", "FEAT-1532"),
    ("agents/loop-specialist.md", "ll-loop history", "FEAT-1532"),
    ("skills/create-loop/loop-types.md", "assumption_gate", "ENH-2215"),
    ("skills/create-loop/loop-types.md", "assumption-firewall", "ENH-2215"),
    ("skills/create-loop/SKILL.md", "Policy router (decision table)", "ENH-2299"),
    ("skills/create-loop/loop-types.md", "## Policy Router Questions", "ENH-2299"),
    ("skills/create-loop/templates.md", "policy-router", "ENH-2299"),
    ("docs/reference/COMMANDS.md", "policy-router", "ENH-2299"),
]


@pytest.mark.parametrize("doc_rel, needle, issue_id", DOC_STRINGS_PRESENT)
def test_string_present_in_doc(
    project_root: Path, doc_rel: str, needle: str, issue_id: str
) -> None:
    """Verify that expected strings appear in documentation files."""
    content = (project_root / doc_rel).read_text()
    assert needle in content, "[{issue_id}] {doc_rel} must contain: {needle!r}"


# -- 17 string-absence assertions --------------------------------

DOC_STRINGS_ABSENT: list[tuple[str, str, str]] = [
    # (doc_path, forbidden_string, issue_id)
    ("agents/codebase-analyzer.md", "file:line", "ENH-1299"),
    ("agents/codebase-pattern-finder.md", "file:line", "ENH-1299"),
    ("skills/wire-issue/SKILL.md", "file:line", "ENH-1299"),
    ("skills/manage-issue/templates.md", "file:line", "ENH-1299"),
    ("commands/refine-issue.md", "file:line", "ENH-1299"),
    ("skills/product-analyzer/SKILL.md", "Remove findings marked as duplicates", "ENH-1403"),
    ("commands/scan-product.md", "Remove findings marked as duplicates", "ENH-1403"),
    ("skills/issue-size-review/SKILL.md", "parent_issue:", "ENH-1433"),
    ("skills/issue-size-review/SKILL.md", "parent_issue: EPIC-NNN", "ENH-1433"),
    ("skills/confidence-check/SKILL.md", "parent_issue: EPIC-NNN", "ENH-1433"),
    ("skills/manage-issue/SKILL.md", "parent_issue: EPIC-NNN", "ENH-1433"),
    ("skills/manage-issue/SKILL.md", "| `parent_issue`", "ENH-1433"),
    ("skills/product-analyzer/SKILL.md", "goals_file_missing", "ENH-1442"),
    ("skills/product-analyzer/SKILL.md", "Goals file not found", "ENH-1442"),
    ("commands/scan-product.md", "Goals file not found", "ENH-1442"),
    ("docs/reference/loops.md", ".loops/tmp/harness-optimize-trajectory.jsonl", "ENH-1557"),
    ("skills/explore-api/SKILL.md", "29 skills", "FEAT-1287"),
    ("agents/consistency-checker.md", "| hooks/prompts/optimize-prompt-hook.md |", "ENH-2291"),
    (
        ".codex/agents/consistency-checker.toml",
        "| hooks/prompts/optimize-prompt-hook.md |",
        "ENH-2291",
    ),
]


@pytest.mark.parametrize("doc_rel, needle, issue_id", DOC_STRINGS_ABSENT)
def test_string_absent_from_doc(
    project_root: Path, doc_rel: str, needle: str, issue_id: str
) -> None:
    """Verify that stale/forbidden strings do NOT appear in documentation files."""
    content = (project_root / doc_rel).read_text()
    assert needle not in content, "[{issue_id}] {doc_rel} must NOT contain: {needle!r}"


# -- 19 file-existence assertions -----------------------------------

DOC_FILES_MUST_EXIST: list[tuple[str, str]] = [
    # (file_path, issue_id)
    ("commands/align-issues.md", "ENH-1362"),
    ("commands/tradeoff-review-issues.md", "ENH-1363"),
    ("skills/product-analyzer/SKILL.md", "ENH-1402"),
    ("commands/manage-release.md", "ENH-1421"),
    ("skills/manage-issue/SKILL.md", "ENH-1421"),
    # REMOVED (self-referential — old doc-wiring file no longer exists after ENH-1963 consolidation):
    # ("scripts/tests/test_feat1172_doc_wiring.py", "ENH-1421"),
    ("commands/review-sprint.md", "ENH-1859"),
    ("skills/ll-go-no-go/SKILL.md", "ENH-1888"),
    ("skills/ll-capture-issue/SKILL.md", "ENH-1888"),
    ("skills/explore-api/SKILL.md", "FEAT-1287"),
    ("skills/verify-issue-loop/SKILL.md", "FEAT-1447"),
    ("skills/adversarial-verify-loop/SKILL.md", "ENH-2047"),
    ("skills/adversarial-verify-loop/agents/openai.yaml", "ENH-2047"),
    ("docs/claude-code/write-a-hook.md", "FEAT-1457"),
    ("thoughts/research/codex-command-discovery.md", "FEAT-1483"),
    ("agents/loop-specialist.md", "FEAT-1532"),
    (".codex/agents/loop-specialist.toml", "FEAT-1532"),
    ("skills/review-epic/SKILL.md", "FEAT-1856"),
    ("skills/review-epic/agents/openai.yaml", "FEAT-1856"),
    ("skills/scope-epic/SKILL.md", "FEAT-1857"),
    ("skills/scope-epic/agents/openai.yaml", "FEAT-1857"),
    ("skills/create-epics-from-unparented/SKILL.md", "FEAT-2338"),
    ("skills/create-epics-from-unparented/agents/openai.yaml", "FEAT-2338"),
]


@pytest.mark.parametrize("doc_rel, issue_id", DOC_FILES_MUST_EXIST)
def test_file_exists(project_root: Path, doc_rel: str, issue_id: str) -> None:
    """Verify that expected documentation files exist."""
    assert (project_root / doc_rel).exists(), "[{issue_id}] File must exist: {doc_rel}"
