"""FSM loop validation logic (ENH-2774 split from the former flat ``validation.py``).

This package provides validation for FSM loop definitions, ensuring
structural correctness and catching common configuration errors, plus the
harness meta-loop lint rules (MR-1..MR-13, capture-reachability,
session-mode-eval, haiku-gen, policy-table, ...) documented in
``.claude/CLAUDE.md`` § Loop Authoring.

Package layout (ENH-2774 split from the former flat ``validation.py``):
    _base.py:            ValidationSeverity/ValidationError, KNOWN_TOP_LEVEL_KEYS,
                          and cross-rule helpers used by 2+ rule families
                          (_check_param_type, _is_llm_judged, _find_reachable_states,
                          _strip_interpolation_prefix, _effective_session_mode,
                          _SKILL_INVOKE_RE)
    meta_rules.py:        MR-1..MR-6 (meta-loop evaluation, artifact isolation,
                          partial-route dead ends, artifact overwrite,
                          generator-fix discipline, harness multimodal blind spot)
    shell_safety.py:      MR-7, MR-9, MR-11 (bash-default interpolation,
                          over-escaped shell, unsafe context interpolation)
    evaluator_rules.py:   MR-8, MR-10, MR-12, MR-13, haiku-gen, session-mode-eval,
                          classify-route-default, tamper-guard (evidence contract,
                          parse-swallow, pruning-profile, terminal-action/abandonment-verdict,
                          haiku-pinned generator, session-mode inheritance,
                          ENH-2934 tamper_guard value validity)
    reachability.py:      static loop refs, capture-reachability, policy-table,
                          progress-paths-isolation
    structural_rules.py:  entry points (validate_fsm, load_and_validate,
                          is_runnable_loop) plus the un-numbered structural
                          rules (evaluator/parameter/binding/routing/cost-ceiling
                          checks, zero-retry-counter, input-key guard,
                          on-max-steps/iterations, circuit, host-guard,
                          prompt-size-guard)

Public API:
    ValidationError:              structured validation error/warning
    ValidationSeverity:           ERROR | WARNING
    validate_fsm(fsm, ...):       structural + lint-rule dispatcher
    load_and_validate(path, ...): load a loop YAML and validate it
    is_runnable_loop(path):       cheap runnable-loop check for a YAML file
"""

from __future__ import annotations

from little_loops.fsm.validation._base import (
    _INTERPOLATION_PREFIX_RE,
    _SKILL_INVOKE_RE,
    EVALUATOR_REQUIRED_FIELDS,
    KNOWN_TOP_LEVEL_KEYS,
    NON_LLM_EVALUATOR_TYPES,
    STALL_SPECIAL_TOKENS,
    VALID_OPERATORS,
    VALID_PARAMETER_TYPES,
    VALID_VISIBILITY,
    ValidationError,
    ValidationSeverity,
    _check_param_type,
    _effective_session_mode,
    _find_reachable_states,
    _is_llm_judged,
    _strip_interpolation_prefix,
)
from little_loops.fsm.validation.evaluator_rules import (
    _ABANDON_ATTEMPT_CAP_RE,
    _ABANDON_BANG_MARKER_RE,
    _ABANDON_CHECKED_ANNOTATION_RE,
    _ABANDON_COUNTER_REF_RE,
    _ABANDONED_KEY_EMIT_RE,
    _EVIDENCE_CONTRACT_KEYWORDS,
    _HARDCODE_VERDICT_SUCCESS_RE,
    _JSON_PARSE_CALL_RE,
    _PARSE_EXCEPT_CATCHING_RE,
    _ZERO_EXIT_RE,
    _effective_pruning_profile,
    _effective_tamper_guard,
    _validate_abandonment_verdict,
    _validate_classify_route_default,
    _validate_haiku_pinned_generator,
    _validate_llm_evidence_contract,
    _validate_parse_swallow,
    _validate_prepatch_check,
    _validate_pruning_profile,
    _validate_session_mode_evaluator_inheritance,
    _validate_tamper_guard,
    _validate_terminal_action_ok,
)
from little_loops.fsm.validation.meta_rules import (
    _META_LOOP_ACTION_PATTERNS,
    _META_LOOP_ACTION_TOKENS,
    _META_LOOP_IMPORT_TRIGGERS,
    _MULTIMODAL_EVAL_PATTERNS,
    _SHARED_TMP_PATH_RE,
    _find_shared_tmp_writes,
    _has_baseline_reference,
    _is_meta_loop,
    _validate_artifact_isolation,
    _validate_artifact_overwrite,
    _validate_generator_fix_discipline,
    _validate_harness_multimodal_evaluator_blind_spot,
    _validate_meta_loop_evaluation,
    _validate_partial_route_dead_end,
)
from little_loops.fsm.validation.reachability import (
    _CAPTURED_REF_FULL_RE,
    _CAPTURED_REF_RE,
    _SUB_LOOP_CAPTURE_OWN_FIELDS,
    _dominated_by_any,
    _dominates,
    _find_bypass_path,
    _find_bypass_path_any,
    _has_sub_loop_state,
    _unguarded_captured_refs,
    _validate_capture_reachability,
    _validate_loop_references,
    _validate_policy_dimensions_scored,
    _validate_progress_paths_isolation,
)
from little_loops.fsm.validation.shell_safety import (
    _BASH_DEFAULT_RE,
    _OVERESCAPED_SHELL_RE,
    _QUOTED_HEREDOC_START_RE,
    _UNSAFE_CONTEXT_INTERP_RE,
    _find_bash_default_tokens,
    _find_unsafe_context_interpolations,
    _validate_bash_default_interpolation,
    _validate_overescaped_shell,
    _validate_unsafe_context_interpolation,
)
from little_loops.fsm.validation.structural_rules import (
    _COUNTER_FILE_WRITE_RE,
    _COUNTER_INCREMENT_RE,
    _has_cannot_judge_route,
    _has_error_route,
    _is_abstention_capable,
    _is_counter_action,
    _suggested_target,
    _validate_abstention_route,
    _validate_circuit,
    _validate_evaluate_unknown_keys,
    _validate_evaluator,
    _validate_failure_terminal_action,
    _validate_fragment_bindings,
    _validate_host_guard,
    _validate_input_key_without_guard,
    _validate_missing_scope,
    _validate_on_max_iterations,
    _validate_on_max_steps,
    _validate_parameters,
    _validate_prompt_size_guard,
    _validate_state_action,
    _validate_state_cost_ceiling,
    _validate_state_routing,
    _validate_targets,
    _validate_with_bindings,
    _validate_zero_retry_counter,
    is_runnable_loop,
    load_and_validate,
    validate_fsm,
)

__all__ = [
    "EVALUATOR_REQUIRED_FIELDS",
    "KNOWN_TOP_LEVEL_KEYS",
    "NON_LLM_EVALUATOR_TYPES",
    "STALL_SPECIAL_TOKENS",
    "VALID_OPERATORS",
    "VALID_PARAMETER_TYPES",
    "VALID_VISIBILITY",
    "ValidationError",
    "ValidationSeverity",
    "is_runnable_loop",
    "load_and_validate",
    "validate_fsm",
    # Private functions/constants re-exported for test access and for
    # cross-module callers (fsm/executor.py, fsm/persistence.py,
    # fsm/route_table.py) that bypass fsm/__init__.py.
    "_ABANDONED_KEY_EMIT_RE",
    "_ABANDON_ATTEMPT_CAP_RE",
    "_ABANDON_BANG_MARKER_RE",
    "_ABANDON_CHECKED_ANNOTATION_RE",
    "_ABANDON_COUNTER_REF_RE",
    "_BASH_DEFAULT_RE",
    "_CAPTURED_REF_FULL_RE",
    "_CAPTURED_REF_RE",
    "_COUNTER_FILE_WRITE_RE",
    "_COUNTER_INCREMENT_RE",
    "_EVIDENCE_CONTRACT_KEYWORDS",
    "_HARDCODE_VERDICT_SUCCESS_RE",
    "_INTERPOLATION_PREFIX_RE",
    "_JSON_PARSE_CALL_RE",
    "_META_LOOP_ACTION_PATTERNS",
    "_META_LOOP_ACTION_TOKENS",
    "_META_LOOP_IMPORT_TRIGGERS",
    "_MULTIMODAL_EVAL_PATTERNS",
    "_OVERESCAPED_SHELL_RE",
    "_PARSE_EXCEPT_CATCHING_RE",
    "_QUOTED_HEREDOC_START_RE",
    "_SHARED_TMP_PATH_RE",
    "_SKILL_INVOKE_RE",
    "_SUB_LOOP_CAPTURE_OWN_FIELDS",
    "_UNSAFE_CONTEXT_INTERP_RE",
    "_ZERO_EXIT_RE",
    "_check_param_type",
    "_dominated_by_any",
    "_dominates",
    "_effective_pruning_profile",
    "_effective_session_mode",
    "_effective_tamper_guard",
    "_find_bash_default_tokens",
    "_find_bypass_path",
    "_find_bypass_path_any",
    "_find_reachable_states",
    "_find_shared_tmp_writes",
    "_find_unsafe_context_interpolations",
    "_has_baseline_reference",
    "_has_cannot_judge_route",
    "_has_error_route",
    "_has_sub_loop_state",
    "_is_abstention_capable",
    "_is_counter_action",
    "_is_llm_judged",
    "_is_meta_loop",
    "_strip_interpolation_prefix",
    "_suggested_target",
    "_unguarded_captured_refs",
    "_validate_abandonment_verdict",
    "_validate_abstention_route",
    "_validate_artifact_isolation",
    "_validate_artifact_overwrite",
    "_validate_bash_default_interpolation",
    "_validate_capture_reachability",
    "_validate_circuit",
    "_validate_classify_route_default",
    "_validate_evaluate_unknown_keys",
    "_validate_evaluator",
    "_validate_failure_terminal_action",
    "_validate_fragment_bindings",
    "_validate_generator_fix_discipline",
    "_validate_haiku_pinned_generator",
    "_validate_harness_multimodal_evaluator_blind_spot",
    "_validate_host_guard",
    "_validate_input_key_without_guard",
    "_validate_llm_evidence_contract",
    "_validate_loop_references",
    "_validate_meta_loop_evaluation",
    "_validate_missing_scope",
    "_validate_on_max_iterations",
    "_validate_on_max_steps",
    "_validate_overescaped_shell",
    "_validate_parameters",
    "_validate_parse_swallow",
    "_validate_partial_route_dead_end",
    "_validate_policy_dimensions_scored",
    "_validate_progress_paths_isolation",
    "_validate_prompt_size_guard",
    "_validate_prepatch_check",
    "_validate_pruning_profile",
    "_validate_session_mode_evaluator_inheritance",
    "_validate_tamper_guard",
    "_validate_state_action",
    "_validate_state_cost_ceiling",
    "_validate_state_routing",
    "_validate_targets",
    "_validate_terminal_action_ok",
    "_validate_unsafe_context_interpolation",
    "_validate_with_bindings",
    "_validate_zero_retry_counter",
]
