"""CodexEmitter: host adapter for the Codex CLI.

Migrated from ``cli/adapt_skills_for_codex.py`` and
``cli/adapt_agents_for_codex.py`` under FEAT-2391.
"""

from __future__ import annotations

import os
import re
from pathlib import Path

import yaml

from little_loops.adapters.capabilities import HOST_CAPABILITIES
from little_loops.adapters.core import (  # noqa: F401
    AdapterError,
    _extract_body,
    _select_frontmatter_fields,
)

__all__ = ["CodexEmitter"]

_MARKER = "# generated by ll-adapt"
_MAX_SHORT_DESC = 80

# Recognised ll-generated markers for idempotency; includes the legacy value so
# existing files are not treated as user-authored and can be updated in place.
_LL_GENERATED_MARKERS = (
    _MARKER,
    "# generated by ll-adapt-agents-for-codex",
)

_READ_ONLY_TOOLS = frozenset({"Read", "Glob", "Grep", "WebFetch", "WebSearch"})
_WRITE_TOOLS = frozenset({"Edit", "Write", "Bash", "NotebookEdit"})


# ---------------------------------------------------------------------------
# Skill helpers (migrated from adapt_skills_for_codex.py)
# ---------------------------------------------------------------------------


def _truncate_short_desc(text: str, limit: int = _MAX_SHORT_DESC) -> str:
    """Truncate *text* to *limit* chars, preferring a word boundary + ellipsis.

    Falls back to a hard cutoff at *limit* when no word boundary is found
    within the truncation window (e.g. a single long token).
    """
    if len(text) <= limit:
        return text
    ellipsis = "..."
    cut_limit = limit - len(ellipsis)
    truncated = text[:cut_limit]
    boundary = truncated.rfind(" ")
    if boundary > 0:
        return truncated[:boundary].rstrip() + ellipsis
    return text[:limit]


def _extract_skill_short_desc(text: str) -> str:
    """Parse skill/command content and return a short description, ≤80 chars.

    Prefers an explicit ``metadata.short-description`` frontmatter field when
    present; otherwise falls back to the first non-empty line of
    ``description``, truncated at a word boundary with an ellipsis.
    """
    if not text.startswith("---"):
        return ""
    end = text.find("---", 3)
    if end == -1:
        return ""
    fm_raw = text[3:end]
    try:
        fm = yaml.safe_load(fm_raw) or {}
    except yaml.YAMLError:
        return ""

    metadata = fm.get("metadata")
    if isinstance(metadata, dict):
        explicit = metadata.get("short-description")
        if isinstance(explicit, str) and explicit.strip():
            return explicit.strip()[:_MAX_SHORT_DESC]

    desc = fm.get("description", "") or ""
    if not isinstance(desc, str):
        return ""
    for line in desc.splitlines():
        stripped = line.strip()
        if stripped:
            return _truncate_short_desc(stripped)
    return ""


def _insert_skill_fields(content: str, name: str, short_desc: str) -> tuple[str, bool]:
    """Thin back-compat wrapper for the legacy 3-arg signature.

    The field-selection policy itself now lives in
    :func:`little_loops.adapters.core._select_frontmatter_fields`,
    parameterized by ``HOST_CAPABILITIES["codex"].frontmatter_fields_read``
    (ENH-2883). Kept for ``cli/adapt_skills_for_codex.py`` and its tests,
    which import this name directly.
    """
    fields_read = HOST_CAPABILITIES["codex"].frontmatter_fields_read
    return _select_frontmatter_fields(content, name, fields_read, short_desc)


def _title_case(slug: str) -> str:
    """Convert a kebab-case slug to title-cased display name."""
    return " ".join(word.capitalize() for word in slug.replace("-", " ").split())


def _make_openai_yaml_content(display_name: str, short_desc: str) -> str:
    """Return ``agents/openai.yaml`` content for the Codex Skills API."""
    return f'interface:\n  display_name: "{display_name}"\n  short_description: "{short_desc}"\n'


def _synthesized_skill_md(stem: str, description: str, fm: dict, short_desc: str) -> str:
    """Build a minimal synthesized SKILL.md for a bridged command.

    Pass-through only: ``allowed-tools`` and ``argument-hint`` are emitted
    from *fm* (the source command's parsed frontmatter) when present, omitted
    (never emitted as a literal ``null``) when absent. *short_desc* is the
    caller's already-computed value (see ``_extract_skill_short_desc``) — this
    function does not truncate. There is no merge with an existing on-disk
    stub; the output is a pure function of *stem*/*description*/*fm*/
    *short_desc* (ENH-3265).
    """
    if "\n" in description.strip():
        indented = "\n".join(f"  {line}" if line else "" for line in description.splitlines())
        desc_block = f"description: |\n{indented}"
    else:
        desc_block = f"description: {description.strip()}"

    extra_fields = ""
    argument_hint = fm.get("argument-hint")
    if isinstance(argument_hint, str) and argument_hint.strip():
        escaped = argument_hint.replace("\\", "\\\\").replace('"', '\\"')
        extra_fields += f'argument-hint: "{escaped}"\n'

    allowed_tools = fm.get("allowed-tools")
    if isinstance(allowed_tools, list) and allowed_tools:
        items = "\n".join(f"  - {tool}" for tool in allowed_tools)
        extra_fields += f"allowed-tools:\n{items}\n"

    return (
        f"---\n"
        f"name: ll-{stem}\n"
        f"{desc_block}\n"
        f"{extra_fields}"
        # Bridge stubs exist only for Codex Skills API discovery (which reads the
        # agents/openai.yaml sidecar); hide them from the Claude Code skill
        # listing budget — users invoke the /ll:<stem> slash command (ENH-1615).
        f"disable-model-invocation: true\n"
        f"metadata:\n"
        f"  short-description: {short_desc}\n"
        f"---\n"
        f"\n"
        f"# {_title_case(stem)}\n"
        f"\n"
        f"Bridged from `commands/{stem}.md` for Codex Skills API discovery.\n"
        f"See the source command file for the full prompt body.\n"
    )


# ---------------------------------------------------------------------------
# Agent helpers (migrated from adapt_agents_for_codex.py)
# ---------------------------------------------------------------------------


def _extract_agent_short_desc(text: str) -> str:
    """Return first non-empty description line from agent frontmatter, ≤80 chars."""
    if not text.startswith("---"):
        return ""
    end = text.find("---", 3)
    if end == -1:
        return ""
    try:
        fm = yaml.safe_load(text[3:end]) or {}
    except yaml.YAMLError:
        return ""
    desc = fm.get("description", "") or ""
    if not isinstance(desc, str):
        return ""
    for line in desc.splitlines():
        stripped = line.strip()
        if stripped:
            return stripped[:_MAX_SHORT_DESC]
    return ""


# ---------------------------------------------------------------------------
# Rich TOML field derivation (ENH-2121 absorbed into FEAT-2391)
# ---------------------------------------------------------------------------


def _derive_sandbox_mode(tools: list | None) -> str | None:
    """Derive Codex ``sandbox_mode`` from the agent's tools list.

    Returns ``"read-only"`` when all tools are known read-only operations,
    ``"write-to-cwd"`` when any write tool is present, or ``None`` when the
    tools list is absent (field omitted; Codex inherits from the session).
    """
    if not tools:
        return None
    tool_set = set(tools)
    if not (tool_set & _WRITE_TOOLS):
        return "read-only"
    return "write-to-cwd"


def _derive_mcp_servers(tools: list | None) -> list[str] | None:
    """Derive Codex ``mcp_servers`` from MCP tool references in the tools list.

    Returns a deduplicated list of server names extracted from ``mcp__<server>__*``
    patterns, or ``None`` when no MCP tools are present.
    """
    if not tools:
        return None
    servers: list[str] = []
    for tool in tools:
        if isinstance(tool, str) and tool.startswith("mcp__"):
            parts = tool.split("__")
            if len(parts) >= 2:
                server = parts[1]
                if server not in servers:
                    servers.append(server)
    return servers if servers else None


def _format_agent_toml(
    name: str,
    description: str,
    model: str,
    body: str,
    fm: dict,
) -> str:
    """Return TOML content for ``.codex/agents/<name>.toml``.

    Emits the four core fields plus optional rich fields derived from *fm*
    (``sandbox_mode``, ``mcp_servers``) when source data is available.
    """
    escaped_desc = description.replace("\\", "\\\\").replace('"', '\\"')
    escaped_model = model.replace("\\", "\\\\").replace('"', '\\"')
    safe_body = body.replace('"""', '\\"\\"\\"')
    if not safe_body.endswith("\n"):
        safe_body += "\n"

    result = (
        f'{_MARKER}\nname = "{name}"\ndescription = "{escaped_desc}"\nmodel = "{escaped_model}"\n'
    )

    # Resolve tools from frontmatter for rich-field derivation
    tools = fm.get("tools")
    if isinstance(tools, str):
        try:
            tools = yaml.safe_load(tools) or []
        except yaml.YAMLError:
            tools = []

    sandbox_mode = _derive_sandbox_mode(tools)
    if sandbox_mode:
        result += f'sandbox_mode = "{sandbox_mode}"\n'

    mcp_servers = _derive_mcp_servers(tools)
    if mcp_servers:
        servers_str = ", ".join(f'"{s}"' for s in mcp_servers)
        result += f"mcp_servers = [{servers_str}]\n"

    result += f'\ndeveloper_instructions = """\n{safe_body}"""\n'
    return result


# ---------------------------------------------------------------------------
# MCP config helpers (BUG-3178)
# ---------------------------------------------------------------------------


def _codex_home_config_path() -> Path:
    """Return Codex's real global config file path.

    Codex reads MCP server definitions from a single global
    ``~/.codex/config.toml`` (or ``$CODEX_HOME/config.toml`` when that
    environment variable is set, mirroring Codex's own override), not a
    project-local file — confirmed by the ``.ll/learning-tests/codex.md``
    learning test.
    """
    home = os.environ.get("CODEX_HOME")
    base = Path(home) if home else Path.home() / ".codex"
    return base / "config.toml"


def _find_ll_mcp_block(text: str) -> tuple[int, int, bool] | None:
    """Locate the ``[mcp_servers.ll-mcp]`` table in *text*, if present.

    Returns ``(block_start, block_end, marker_owned)``:

    - ``block_start``/``block_end`` bound the table, including its leading
      marker comment line when *marker_owned* is true; the table body runs
      until the next top-level ``[...]`` header or end of file.
    - ``marker_owned`` is true only when the line immediately preceding the
      table header is one of ``_LL_GENERATED_MARKERS`` — i.e. ll-adapt wrote
      this table itself and may safely rewrite it. A table with no marker is
      user-authored and must be left untouched.

    Returns ``None`` when no ``[mcp_servers.ll-mcp]`` table exists.
    """
    header = re.search(r"^\[mcp_servers\.ll-mcp\]\s*$", text, re.MULTILINE)
    if header is None:
        return None

    next_table = re.search(r"^\[", text[header.end() :], re.MULTILINE)
    block_end = header.end() + next_table.start() if next_table else len(text)

    prefix = text[: header.start()]
    for marker in _LL_GENERATED_MARKERS:
        marker_line = marker + "\n"
        if prefix.endswith(marker_line):
            return header.start() - len(marker_line), block_end, True

    return header.start(), block_end, False


# ---------------------------------------------------------------------------
# CodexEmitter
# ---------------------------------------------------------------------------


class CodexEmitter:
    """Output emitter for the Codex host (``--host codex``).

    Each ``emit_*`` method receives a metadata dict built by the core traversal
    functions and returns ``"adapted"``, ``"skipped"``, or ``"error"``.
    """

    name = "codex"

    def emit_skill(self, skill_meta: dict) -> str:
        """Add Codex Skills API frontmatter to one SKILL.md."""
        skill_name: str = skill_meta["skill_name"]
        skill_path: Path = skill_meta["skill_path"]
        content: str = skill_meta["content"]
        apply: bool = skill_meta["apply"]
        quiet: bool = skill_meta["quiet"]

        short_desc = _extract_skill_short_desc(content)
        if not short_desc:
            if not quiet:
                print(f"  SKIP   {skill_name}: no description found")
            return "skipped"

        new_text, skill_changed = _insert_skill_fields(content, skill_name, short_desc)
        openai_yaml = skill_path.parent / "agents" / "openai.yaml"
        new_yaml_content = _make_openai_yaml_content(_title_case(skill_name), short_desc)
        existing_yaml = openai_yaml.read_text() if openai_yaml.exists() else None
        yaml_changed = existing_yaml != new_yaml_content

        if not skill_changed and not yaml_changed:
            if not quiet:
                print(f"  SKIP   {skill_name}: already adapted")
            return "skipped"

        if apply:
            if skill_changed:
                skill_path.write_text(new_text)
            if yaml_changed:
                openai_yaml.parent.mkdir(exist_ok=True)
                openai_yaml.write_text(new_yaml_content)
            if not quiet:
                print(f"  APPLY  {skill_name}: {short_desc[:50]}")
        else:
            if not quiet:
                print(f"  DRY    {skill_name}: {short_desc[:50]}")

        return "adapted"

    def emit_command(self, cmd_meta: dict) -> str:
        """Bridge one command into a Codex-discoverable skills/ll-<stem>/ wrapper."""
        stem: str = cmd_meta["stem"]
        label = f"ll-{stem}"
        content: str = cmd_meta["content"]
        fm: dict = cmd_meta["fm"]
        output_dir: Path = cmd_meta["output_dir"]
        apply: bool = cmd_meta["apply"]
        quiet: bool = cmd_meta["quiet"]

        description = fm.get("description", "") or ""
        if not isinstance(description, str) or not description.strip():
            if not quiet:
                print(f"  SKIP   {label}: no description in frontmatter")
            return "skipped"

        short_desc = _extract_skill_short_desc(content)
        if not short_desc:
            if not quiet:
                print(f"  SKIP   {label}: empty short description")
            return "skipped"

        out_dir = output_dir / f"ll-{stem}"
        out_skill_md = out_dir / "SKILL.md"
        out_openai_yaml = out_dir / "agents" / "openai.yaml"

        new_skill_md = _synthesized_skill_md(stem, description, fm, short_desc)
        new_openai_yaml = _make_openai_yaml_content(_title_case(stem), short_desc)
        existing_skill_md = out_skill_md.read_text() if out_skill_md.exists() else None
        existing_openai_yaml = out_openai_yaml.read_text() if out_openai_yaml.exists() else None
        skill_md_changed = existing_skill_md != new_skill_md
        openai_yaml_changed = existing_openai_yaml != new_openai_yaml

        if not skill_md_changed and not openai_yaml_changed:
            if not quiet:
                print(f"  SKIP   {label}: already adapted")
            return "skipped"

        if apply:
            out_dir.mkdir(parents=True, exist_ok=True)
            if skill_md_changed:
                out_skill_md.write_text(new_skill_md)
            if openai_yaml_changed:
                out_openai_yaml.parent.mkdir(exist_ok=True)
                out_openai_yaml.write_text(new_openai_yaml)
            if not quiet:
                print(f"  APPLY  {label}: {short_desc[:50]}")
        else:
            if not quiet:
                print(f"  DRY    {label}: {short_desc[:50]}")

        return "adapted"

    def emit_agent(self, agent_meta: dict) -> str:
        """Emit ``.codex/agents/<name>.toml`` for one agent definition."""
        agent_name: str = agent_meta["agent_name"]
        content: str = agent_meta["content"]
        fm: dict = agent_meta["fm"]
        output_dir: Path = agent_meta["output_dir"]
        apply: bool = agent_meta["apply"]
        quiet: bool = agent_meta["quiet"]

        if not fm:
            if not quiet:
                print(f"  SKIP   {agent_name}: no parseable frontmatter")
            return "skipped"

        name = str(fm.get("name") or agent_name)
        model = str(fm.get("model") or "")
        short_desc = _extract_agent_short_desc(content)
        if not short_desc:
            if not quiet:
                print(f"  SKIP   {agent_name}: no description found")
            return "skipped"

        body = _extract_body(content)
        out_toml = output_dir / f"{agent_name}.toml"
        new_content = _format_agent_toml(name, short_desc, model, body, fm)

        if out_toml.exists():
            existing = out_toml.read_text()
            if not any(existing.startswith(m) for m in _LL_GENERATED_MARKERS):
                if not quiet:
                    print(f"  SKIP   {agent_name}: user-authored file (no marker)")
                return "skipped"
            if existing == new_content:
                if not quiet:
                    print(f"  SKIP   {agent_name}: already up to date")
                return "skipped"

        if apply:
            output_dir.mkdir(parents=True, exist_ok=True)
            out_toml.write_text(new_content)
            if not quiet:
                print(f"  APPLY  {agent_name}: {short_desc[:50]}")
        else:
            if not quiet:
                print(f"  DRY    {agent_name}: {short_desc[:50]}")

        return "adapted"

    def emit_mcp_config(self, meta: dict) -> str:
        """Merge an ``[mcp_servers.ll-mcp]`` definition into Codex's global config.

        Codex has no project-local MCP config read path (see
        ``_codex_home_config_path``'s docstring), so — unlike every other
        ``HostEmitter`` — this method deliberately ignores
        ``meta["output_dir"]`` (the project-relative directory the CLI
        computes for every host) and targets Codex's real global
        ``config.toml`` instead. The write is a targeted block replace, not a
        full-file overwrite or re-serialization, so unrelated tables
        (other ``[mcp_servers.*]`` entries, ``[projects."..."]`` sections)
        are preserved byte-for-byte.
        """
        apply: bool = meta["apply"]
        quiet: bool = meta["quiet"]

        config_path = _codex_home_config_path()
        new_block = f'{_MARKER}\n[mcp_servers.ll-mcp]\ncommand = "ll-mcp"\nargs = []\n'

        existing = config_path.read_text() if config_path.exists() else ""
        found = _find_ll_mcp_block(existing)

        if found is not None:
            block_start, block_end, marker_owned = found
            if not marker_owned:
                if not quiet:
                    print(
                        "  SKIP   mcp-config: user-authored [mcp_servers.ll-mcp] table (no marker)"
                    )
                return "skipped"
            if existing[block_start:block_end] == new_block:
                if not quiet:
                    print("  SKIP   mcp-config: already up to date")
                return "skipped"
            new_text = existing[:block_start] + new_block + existing[block_end:]
        else:
            if existing and not existing.endswith("\n"):
                existing += "\n"
            if existing and not existing.endswith("\n\n"):
                existing += "\n"
            new_text = existing + new_block

        if apply:
            config_path.parent.mkdir(parents=True, exist_ok=True)
            config_path.write_text(new_text)
            if not quiet:
                print(f"  APPLY  mcp-config: ll-mcp ({config_path})")
        else:
            if not quiet:
                print(f"  DRY    mcp-config: ll-mcp ({config_path})")

        return "adapted"
