"""CodexEmitter: host adapter for the Codex CLI.

Migrated from ``cli/adapt_skills_for_codex.py`` and
``cli/adapt_agents_for_codex.py`` under FEAT-2391.
"""

from __future__ import annotations

import re
from pathlib import Path

import yaml

from little_loops.adapters.core import AdapterError, _extract_body  # noqa: F401

__all__ = ["CodexEmitter"]

_MARKER = "# generated by ll-adapt"
_MAX_SHORT_DESC = 80
_FM_CLOSE_RE = re.compile(r"\n---\s*\n")

# Recognised ll-generated markers for idempotency; includes the legacy value so
# existing files are not treated as user-authored and can be updated in place.
_LL_GENERATED_MARKERS = (
    _MARKER,
    "# generated by ll-adapt-agents-for-codex",
)

_READ_ONLY_TOOLS = frozenset({"Read", "Glob", "Grep", "WebFetch", "WebSearch"})
_WRITE_TOOLS = frozenset({"Edit", "Write", "Bash", "NotebookEdit"})


# ---------------------------------------------------------------------------
# Skill helpers (migrated from adapt_skills_for_codex.py)
# ---------------------------------------------------------------------------


def _extract_skill_short_desc(text: str) -> str:
    """Parse skill/command content and return first non-empty description line, ≤80 chars."""
    if not text.startswith("---"):
        return ""
    end = text.find("---", 3)
    if end == -1:
        return ""
    fm_raw = text[3:end]
    try:
        fm = yaml.safe_load(fm_raw) or {}
    except yaml.YAMLError:
        return ""
    desc = fm.get("description", "") or ""
    if not isinstance(desc, str):
        return ""
    for line in desc.splitlines():
        stripped = line.strip()
        if stripped:
            return stripped[:_MAX_SHORT_DESC]
    return ""


def _insert_skill_fields(content: str, name: str, short_desc: str) -> tuple[str, bool]:
    """Insert ``name:`` and ``metadata.short-description:`` into SKILL.md frontmatter.

    Uses targeted string manipulation — no yaml roundtrip — to preserve
    existing frontmatter formatting.  Returns ``(new_content, changed)``.
    """
    if not content.startswith("---\n"):
        return content, False

    m = _FM_CLOSE_RE.search(content[3:])
    if not m:
        return content, False

    fm_text = content[4 : 3 + m.start()]
    after = content[3 + m.start() :]

    changed = False

    if not re.search(r"^name\s*:", fm_text, re.MULTILINE):
        fm_text = f"name: {name}\n" + fm_text
        changed = True

    if "short-description:" not in fm_text:
        if re.search(r"^metadata\s*:", fm_text, re.MULTILINE):
            fm_text = re.sub(
                r"^(metadata\s*:.*)$",
                lambda mtch: mtch.group(0) + f"\n  short-description: {short_desc}",
                fm_text,
                flags=re.MULTILINE,
                count=1,
            )
        else:
            fm_text += f"\nmetadata:\n  short-description: {short_desc}"
        changed = True

    return f"---\n{fm_text}{after}", changed


def _title_case(slug: str) -> str:
    """Convert a kebab-case slug to title-cased display name."""
    return " ".join(word.capitalize() for word in slug.replace("-", " ").split())


def _make_openai_yaml_content(display_name: str, short_desc: str) -> str:
    """Return ``agents/openai.yaml`` content for the Codex Skills API."""
    return f'interface:\n  display_name: "{display_name}"\n  short_description: "{short_desc}"\n'


def _synthesized_skill_md(stem: str, description: str) -> str:
    """Build a minimal synthesized SKILL.md for a bridged command."""
    short_desc = ""
    for line in description.splitlines():
        stripped = line.strip()
        if stripped:
            short_desc = stripped[:_MAX_SHORT_DESC]
            break

    if "\n" in description.strip():
        indented = "\n".join(f"  {line}" if line else "" for line in description.splitlines())
        desc_block = f"description: |\n{indented}"
    else:
        desc_block = f"description: {description.strip()}"

    return (
        f"---\n"
        f"name: ll-{stem}\n"
        f"{desc_block}\n"
        # Bridge stubs exist only for Codex Skills API discovery (which reads the
        # agents/openai.yaml sidecar); hide them from the Claude Code skill
        # listing budget — users invoke the /ll:<stem> slash command (ENH-1615).
        f"disable-model-invocation: true\n"
        f"metadata:\n"
        f"  short-description: {short_desc}\n"
        f"---\n"
        f"\n"
        f"# {_title_case(stem)}\n"
        f"\n"
        f"Bridged from `commands/{stem}.md` for Codex Skills API discovery.\n"
        f"See the source command file for the full prompt body.\n"
    )


# ---------------------------------------------------------------------------
# Agent helpers (migrated from adapt_agents_for_codex.py)
# ---------------------------------------------------------------------------


def _extract_agent_short_desc(text: str) -> str:
    """Return first non-empty description line from agent frontmatter, ≤80 chars."""
    if not text.startswith("---"):
        return ""
    end = text.find("---", 3)
    if end == -1:
        return ""
    try:
        fm = yaml.safe_load(text[3:end]) or {}
    except yaml.YAMLError:
        return ""
    desc = fm.get("description", "") or ""
    if not isinstance(desc, str):
        return ""
    for line in desc.splitlines():
        stripped = line.strip()
        if stripped:
            return stripped[:_MAX_SHORT_DESC]
    return ""


# ---------------------------------------------------------------------------
# Rich TOML field derivation (ENH-2121 absorbed into FEAT-2391)
# ---------------------------------------------------------------------------


def _derive_sandbox_mode(tools: list | None) -> str | None:
    """Derive Codex ``sandbox_mode`` from the agent's tools list.

    Returns ``"read-only"`` when all tools are known read-only operations,
    ``"write-to-cwd"`` when any write tool is present, or ``None`` when the
    tools list is absent (field omitted; Codex inherits from the session).
    """
    if not tools:
        return None
    tool_set = set(tools)
    if not (tool_set & _WRITE_TOOLS):
        return "read-only"
    return "write-to-cwd"


def _derive_mcp_servers(tools: list | None) -> list[str] | None:
    """Derive Codex ``mcp_servers`` from MCP tool references in the tools list.

    Returns a deduplicated list of server names extracted from ``mcp__<server>__*``
    patterns, or ``None`` when no MCP tools are present.
    """
    if not tools:
        return None
    servers: list[str] = []
    for tool in tools:
        if isinstance(tool, str) and tool.startswith("mcp__"):
            parts = tool.split("__")
            if len(parts) >= 2:
                server = parts[1]
                if server not in servers:
                    servers.append(server)
    return servers if servers else None


def _format_agent_toml(
    name: str,
    description: str,
    model: str,
    body: str,
    fm: dict,
) -> str:
    """Return TOML content for ``.codex/agents/<name>.toml``.

    Emits the four core fields plus optional rich fields derived from *fm*
    (``sandbox_mode``, ``mcp_servers``) when source data is available.
    """
    escaped_desc = description.replace("\\", "\\\\").replace('"', '\\"')
    escaped_model = model.replace("\\", "\\\\").replace('"', '\\"')
    safe_body = body.replace('"""', '\\"\\"\\"')
    if not safe_body.endswith("\n"):
        safe_body += "\n"

    result = (
        f'{_MARKER}\nname = "{name}"\ndescription = "{escaped_desc}"\nmodel = "{escaped_model}"\n'
    )

    # Resolve tools from frontmatter for rich-field derivation
    tools = fm.get("tools")
    if isinstance(tools, str):
        try:
            tools = yaml.safe_load(tools) or []
        except yaml.YAMLError:
            tools = []

    sandbox_mode = _derive_sandbox_mode(tools)
    if sandbox_mode:
        result += f'sandbox_mode = "{sandbox_mode}"\n'

    mcp_servers = _derive_mcp_servers(tools)
    if mcp_servers:
        servers_str = ", ".join(f'"{s}"' for s in mcp_servers)
        result += f"mcp_servers = [{servers_str}]\n"

    result += f'\ndeveloper_instructions = """\n{safe_body}"""\n'
    return result


# ---------------------------------------------------------------------------
# CodexEmitter
# ---------------------------------------------------------------------------


class CodexEmitter:
    """Output emitter for the Codex host (``--host codex``).

    Each ``emit_*`` method receives a metadata dict built by the core traversal
    functions and returns ``"adapted"``, ``"skipped"``, or ``"error"``.
    """

    name = "codex"

    def emit_skill(self, skill_meta: dict) -> str:
        """Add Codex Skills API frontmatter to one SKILL.md."""
        skill_name: str = skill_meta["skill_name"]
        skill_path: Path = skill_meta["skill_path"]
        content: str = skill_meta["content"]
        apply: bool = skill_meta["apply"]
        quiet: bool = skill_meta["quiet"]

        short_desc = _extract_skill_short_desc(content)
        if not short_desc:
            if not quiet:
                print(f"  SKIP   {skill_name}: no description found")
            return "skipped"

        new_text, skill_changed = _insert_skill_fields(content, skill_name, short_desc)
        openai_yaml = skill_path.parent / "agents" / "openai.yaml"
        yaml_exists = openai_yaml.exists()

        if not skill_changed and yaml_exists:
            if not quiet:
                print(f"  SKIP   {skill_name}: already adapted")
            return "skipped"

        if apply:
            if skill_changed:
                skill_path.write_text(new_text)
            if not yaml_exists:
                openai_yaml.parent.mkdir(exist_ok=True)
                openai_yaml.write_text(
                    _make_openai_yaml_content(_title_case(skill_name), short_desc)
                )
            if not quiet:
                print(f"  APPLY  {skill_name}: {short_desc[:50]}")
        else:
            if not quiet:
                print(f"  DRY    {skill_name}: {short_desc[:50]}")

        return "adapted"

    def emit_command(self, cmd_meta: dict) -> str:
        """Bridge one command into a Codex-discoverable skills/ll-<stem>/ wrapper."""
        stem: str = cmd_meta["stem"]
        label = f"ll-{stem}"
        content: str = cmd_meta["content"]
        fm: dict = cmd_meta["fm"]
        output_dir: Path = cmd_meta["output_dir"]
        apply: bool = cmd_meta["apply"]
        quiet: bool = cmd_meta["quiet"]

        description = fm.get("description", "") or ""
        if not isinstance(description, str) or not description.strip():
            if not quiet:
                print(f"  SKIP   {label}: no description in frontmatter")
            return "skipped"

        short_desc = _extract_skill_short_desc(content)
        if not short_desc:
            if not quiet:
                print(f"  SKIP   {label}: empty short description")
            return "skipped"

        out_dir = output_dir / f"ll-{stem}"
        out_skill_md = out_dir / "SKILL.md"
        out_openai_yaml = out_dir / "agents" / "openai.yaml"

        if out_skill_md.exists() and out_openai_yaml.exists():
            if not quiet:
                print(f"  SKIP   {label}: already adapted")
            return "skipped"

        if apply:
            out_dir.mkdir(parents=True, exist_ok=True)
            if not out_skill_md.exists():
                out_skill_md.write_text(_synthesized_skill_md(stem, description))
            if not out_openai_yaml.exists():
                out_openai_yaml.parent.mkdir(exist_ok=True)
                out_openai_yaml.write_text(_make_openai_yaml_content(_title_case(stem), short_desc))
            if not quiet:
                print(f"  APPLY  {label}: {short_desc[:50]}")
        else:
            if not quiet:
                print(f"  DRY    {label}: {short_desc[:50]}")

        return "adapted"

    def emit_agent(self, agent_meta: dict) -> str:
        """Emit ``.codex/agents/<name>.toml`` for one agent definition."""
        agent_name: str = agent_meta["agent_name"]
        content: str = agent_meta["content"]
        fm: dict = agent_meta["fm"]
        output_dir: Path = agent_meta["output_dir"]
        apply: bool = agent_meta["apply"]
        quiet: bool = agent_meta["quiet"]

        if not fm:
            if not quiet:
                print(f"  SKIP   {agent_name}: no parseable frontmatter")
            return "skipped"

        name = str(fm.get("name") or agent_name)
        model = str(fm.get("model") or "")
        short_desc = _extract_agent_short_desc(content)
        if not short_desc:
            if not quiet:
                print(f"  SKIP   {agent_name}: no description found")
            return "skipped"

        body = _extract_body(content)
        out_toml = output_dir / f"{agent_name}.toml"
        new_content = _format_agent_toml(name, short_desc, model, body, fm)

        if out_toml.exists():
            existing = out_toml.read_text()
            if not any(existing.startswith(m) for m in _LL_GENERATED_MARKERS):
                if not quiet:
                    print(f"  SKIP   {agent_name}: user-authored file (no marker)")
                return "skipped"
            if existing == new_content:
                if not quiet:
                    print(f"  SKIP   {agent_name}: already up to date")
                return "skipped"

        if apply:
            output_dir.mkdir(parents=True, exist_ok=True)
            out_toml.write_text(new_content)
            if not quiet:
                print(f"  APPLY  {agent_name}: {short_desc[:50]}")
        else:
            if not quiet:
                print(f"  DRY    {agent_name}: {short_desc[:50]}")

        return "adapted"
