"""ll-adapt-agents-for-codex: Emit .codex/agents/<name>.toml for each agents/*.md.

For each agents/<name>.md, reads name/description/model frontmatter and the
body text, then emits <repo-root>/.codex/agents/<name>.toml for Codex subagent
discovery.  Existing user-authored files (no marker comment) are never
overwritten.

Dry-run by default. Use --apply to write changes.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import yaml

__all__ = ["main_adapt_agents_for_codex"]

_MARKER = "# generated by ll-adapt-agents-for-codex"
_MAX_SHORT_DESC = 80


def _find_plugin_root() -> Path:
    from little_loops.skill_expander import _find_plugin_root as _fpr

    return _fpr()


def _extract_agent_frontmatter(text: str) -> dict | None:
    """Parse agents/*.md and return frontmatter dict, or None on failure."""
    if not text.startswith("---"):
        return None
    end = text.find("---", 3)
    if end == -1:
        return None
    try:
        fm = yaml.safe_load(text[3:end]) or {}
    except yaml.YAMLError:
        return None
    return fm if isinstance(fm, dict) else None


def _extract_short_desc(text: str) -> str:
    """Return first non-empty description line from agent frontmatter, ≤80 chars."""
    fm = _extract_agent_frontmatter(text)
    if not fm:
        return ""
    desc = fm.get("description", "") or ""
    if not isinstance(desc, str):
        return ""
    for line in desc.splitlines():
        stripped = line.strip()
        if stripped:
            return stripped[:_MAX_SHORT_DESC]
    return ""


def _extract_body(text: str) -> str:
    """Return body text after the closing --- of frontmatter."""
    if not text.startswith("---"):
        return ""
    end = text.find("---", 3)
    if end == -1:
        return ""
    after_fm = text[end + 3 :]
    if after_fm.startswith("\n"):
        after_fm = after_fm[1:]
    return after_fm


def _emit_agent_toml(name: str, description: str, model: str, body: str) -> str:
    """Return TOML content for .codex/agents/<name>.toml."""
    escaped_desc = description.replace("\\", "\\\\").replace('"', '\\"')
    escaped_model = model.replace("\\", "\\\\").replace('"', '\\"')
    # TOML multiline basic strings end at """; escape any occurrence in body
    safe_body = body.replace('"""', '\\"\\"\\"')
    if not safe_body.endswith("\n"):
        safe_body += "\n"
    return (
        f"{_MARKER}\n"
        f'name = "{name}"\n'
        f'description = "{escaped_desc}"\n'
        f'model = "{escaped_model}"\n'
        f"\n"
        f'developer_instructions = """\n'
        f"{safe_body}"
        f'"""\n'
    )


def _process_agents(
    agents_dir: Path,
    codex_dir: Path,
    apply: bool,
    quiet: bool,
    only: str | None,
) -> tuple[int, int, int]:
    """Process all agents/*.md files; return (adapted, skipped, errors)."""
    adapted = skipped = errors = 0

    for agent_md in sorted(agents_dir.glob("*.md")):
        agent_name = agent_md.stem

        if only is not None and agent_name != only:
            continue

        try:
            text = agent_md.read_text()
        except OSError as exc:
            if not quiet:
                print(f"  ERROR  {agent_name}: cannot read: {exc}", file=sys.stderr)
            errors += 1
            continue

        fm = _extract_agent_frontmatter(text)
        if not fm:
            if not quiet:
                print(f"  SKIP   {agent_name}: no parseable frontmatter")
            skipped += 1
            continue

        name = str(fm.get("name") or agent_name)
        model = str(fm.get("model") or "")
        short_desc = _extract_short_desc(text)
        if not short_desc:
            if not quiet:
                print(f"  SKIP   {agent_name}: no description found")
            skipped += 1
            continue

        body = _extract_body(text)
        out_toml = codex_dir / f"{agent_name}.toml"
        new_content = _emit_agent_toml(name, short_desc, model, body)

        if out_toml.exists():
            existing = out_toml.read_text()
            if not existing.startswith(_MARKER):
                if not quiet:
                    print(f"  SKIP   {agent_name}: user-authored file (no marker)")
                skipped += 1
                continue
            if existing == new_content:
                if not quiet:
                    print(f"  SKIP   {agent_name}: already up to date")
                skipped += 1
                continue

        if apply:
            codex_dir.mkdir(parents=True, exist_ok=True)
            out_toml.write_text(new_content)
            if not quiet:
                print(f"  APPLY  {agent_name}: {short_desc[:50]}")
        else:
            if not quiet:
                print(f"  DRY    {agent_name}: {short_desc[:50]}")

        adapted += 1

    return adapted, skipped, errors


def main_adapt_agents_for_codex() -> int:
    """Entry point for ll-adapt-agents-for-codex CLI."""
    parser = argparse.ArgumentParser(
        prog="ll-adapt-agents-for-codex",
        description=(
            "Emit .codex/agents/<name>.toml files from agents/*.md for Codex subagent "
            "discovery. Dry-run by default; use --apply to write changes."
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  ll-adapt-agents-for-codex              # Dry-run: preview proposed changes
  ll-adapt-agents-for-codex --apply      # Write .codex/agents/*.toml files
  ll-adapt-agents-for-codex --only codebase-analyzer --apply  # Single agent
  ll-adapt-agents-for-codex --quiet      # Suppress per-entry output
""",
    )
    parser.add_argument(
        "--apply",
        action="store_true",
        default=False,
        help="Write .codex/agents/*.toml files (default: dry-run)",
    )
    parser.add_argument(
        "--only",
        metavar="NAME",
        default=None,
        help="Restrict to a single agent by stem name (e.g. codebase-analyzer)",
    )
    parser.add_argument(
        "--quiet",
        action="store_true",
        default=False,
        help="Suppress per-agent output; only print final summary",
    )

    args = parser.parse_args()

    plugin_root = _find_plugin_root()
    agents_dir = plugin_root / "agents"
    codex_dir = plugin_root / ".codex" / "agents"

    if not agents_dir.exists():
        print(f"ERROR: agents directory not found: {agents_dir}", file=sys.stderr)
        return 1

    mode = "APPLY" if args.apply else "DRY-RUN"
    if not args.quiet:
        print(f"ll-adapt-agents-for-codex [{mode}]")
        print(f"Agents dir: {agents_dir}")
        print(f"Output dir: {codex_dir}")
        if args.only:
            print(f"Filter:     {args.only}")
        print()

    adapted, skipped, errors = _process_agents(
        agents_dir, codex_dir, args.apply, args.quiet, args.only
    )

    print(f"\nDone: {adapted} adapted, {skipped} skipped, {errors} errors")
    return 0 if errors == 0 else 1
